### PR TITLE
Drop button to also accept HTML button props

### LINKED ISSUE #3263: typescript: DropButton should accept button props
DropButton should accept button props
JSX.IntrinsicElements['button']

example to reproduce issue: 
```
<DropButton
  tabIndex={-1}
/>
```

https://github.com/grommet/grommet/blob/02c40eb34dacec20bcd95f2ea8a9cf92f75a7d32/src/js/components/DropButton/index.d.ts#L15

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR starts the clean up of the over use of type definitions 
This PR adds to DropButton to also accept the props of HTML Button for TS
#### Where should the reviewer start?
DropButton/index.d.ts
#### What testing has been done on this PR?
manually tested by branching out to a typescript project
#### How should this be manually tested?
It should work with the following markup

```
         <DropButton
          icon={<Add/>}
          dropContent={<Text>Brittany</Text>}
          href="/test"
          label='Choose'
          open={true}
          tabIndex={-1}
          fill={false}
        />
```
#### What are the relevant issues?
closes #3263  
#### Do the grommet docs need to be updated?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/DropButton/index.d.ts [hunk 1]
```diff
@@ -12,6 +12,6 @@ export interface DropButtonProps {
   open?: boolean;
 }
 
-declare const DropButton: React.ComponentClass<DropButtonProps & ButtonProps>;
+declare const DropButton: React.ComponentClass<DropButtonProps & ButtonProps <JSX.IntrinsicElements['button']>>;
```
Comment (ShimiSun) [inline src/js/components/DropButton/index.d.ts]: Was this working for you? isn't it missing a `&` and shouldn't have `<>`. please create a test to double-check that.

Comment (britt6612) [reply src/js/components/DropButton/index.d.ts]: Yes sorry tested on wrong build you are right!

**Comment by atanasster** [comment]
Any chance you can release to npm after this one is merged, it will help me reduce the amount of hacks to get it going on my side while converting to typescript.

Btw, dont forget to also omit color, as `<DropButton />` inherits the props of `<Button />`

https://github.com/grommet/grommet/blob/396e0129ac74575d16be710092efc514d4267bb4/src/js/components/Button/index.d.ts#L36

**Comment by britt6612** [comment]
> Any chance you can release to npm after this one is merged, it will help me reduce the amount of hacks to get it going on my side while converting to typescript.
> 
> Btw, dont forget to also omit color, as `<DropButton />` inherits the props of `<Button />`
> 
> https://github.com/grommet/grommet/blob/396e0129ac74575d16be710092efc514d4267bb4/src/js/components/Button/index.d.ts#L36

Great catch! Thanks

**Comment by britt6612** [comment]
Tested color after adding the Omit of color with 

```
         color={{light: 'blue', dark: 'pink'}}

```

**Comment by ShimiSun** [comment]
@atanasster 
>Any chance you can release to npm after this one is merged

Let me see what I can do. Thanks.

**Comment by ShimiSun** [comment]
@atanasster available on 2.7.5 👍

**Comment by atanasster** [comment]
Great job, thanks. Kudos to @britt6612  👍
