### PR TITLE
Resolve DateInput incomplete date bug

### LINKED ISSUE #5871: DateInput format="yyyy-mm-dd" converts 2021-11-10 text input as 2021-11-09 (various others too)
When typing in a date between 11/08->11/30 manually, the calendar will jump back one day on the last character typed

### Expected Behavior

When using a yyyy-mm-dd format and the user enters a valid YYYY-MM-DD text, the value shown must match what was entered.

### Actual Behavior

For many valid dates of the form 2021-11-08 through 2021-11-30, the date entered is converted into the day before. Note that not all are incorrectly converted. Probably happens in other situations too, this was just the most obvious.

### URL, screen shot, or Codepen exhibiting the issue

The only difference between working and not working is format="yyyy-mm-dd" (broken) vs format="mm-dd-yyyy" (working).
https://codesandbox.io/s/grommet-v2-template-forked-74ml3?file=/index.js

### Steps to Reproduce

Start typing "2021-11-10". Watch that when you type the last "0", the date is reset to 2021-11-09.

### Your Environment

- Grommet version: 2.18.0. Was happening with 2.17.something also and likely earlier.
- Browser Name and version: Chrome, Safari.
- Operating System and version (desktop or mobile): MacOS, Windows.

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

Resolves a bug where a date with format of `yyyy-mm-dd` or `yyyy/mm/dd` (day at end) was resulting in the date prematurely being considered "complete" and miscalculating the date.

I have also resolved bug in a calculation that converts hours to ms.

Regarding the snapshot change, I believe this is fixing an existing bug in a fairly new test/snapshot (created by https://github.com/grommet/grommet/pull/5837). The date of August 9 should not have been in the snapshot. See screenshot below of the storybook rendering:
Screen Shot 2022-01-13 at 4 55 41 PM

 
#### Where should the reviewer start?

src/js/components/DateInput/utils.js

#### What testing has been done on this PR?

Tested locally with the following:

```
import React from 'react';

import { Box, DateInput } from 'grommet';

export const Format = () => {
  const [value, setValue] = React.useState('');
  const onChange = (event) => {
    const nextValue = event.value;
    console.log('onChange', nextValue);
    setValue(nextValue);
  };
  return (
    <Box align="center" pad="large">
      <Box width="medium">
        <DateInput
          id="item"
          name="item"
          format="yyyy-mm-dd"
          value={value}
          inline
          onChange={onChange}
        />
      </Box>
    </Box>
  );
};

export default {
  title: 'Input/DateInput/Format',
};
```

https://user-images.githubusercontent.com/12522275/149433374-a580bd5e-fddd-4fde-a623-8704c50865fc.mov

#### Do Jest tests follow these best practices?

N/A tests were not touched.

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #5871 

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
Yes. Fixed DateInput bug with yyyy/mm/dd format.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

File: src/js/components/DateInput/utils.js [hunk 1]
```diff
@@ -171,7 +171,12 @@ export const textToValue = (text, schema, range, timestamp) => {
         index += parts.m.length;
       } else if (char === 'd') {
         parts.d = pullDigits(text, index);
-        index += parts.d.length;
+        // when format is something like yyyy/mm/dd,
+        // '0' as incomplete day can cause date to be
+        // prematurely calculated.
+        // ex: 2022/01/0 would reutrn 2021/12/31 in addDate()
+        if (parts.d === '0') delete parts.d;
+        index += parts?.d?.length;
```
Comment (jcfilben) [inline src/js/components/DateInput/utils.js:179]: Fixes lint error
```suggestion
        index += (parts?.d?.length || 0);
```

**Review by jcfilben — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]
