### PR TITLE
DataTable - add `expandLabel` for users to be able to pass aria label to `groupBy` or `rowDetails`

### LINKED ISSUE #6213: a11y: expand is not specific (breaks 3.3.2)
This is basically the same concept as https://github.com/grommet/grommet/issues/6204 but it's for the expand button instead of the onSelect checkbox.

So we we want to make sure that the aria label says "expand ${primaryValue}` instead of "expand" so that we can meet the WCAG's [Success Criterion 3.3.2: Labels or Instructions](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html)

### How to implement this

I think we would want modify the a11yTitle line in ExpanderCell https://github.com/grommet/grommet/blob/04505a6838827267168b75164af799af06e41835/src/js/components/DataTable/ExpanderCell.js#L43

It should follow the same logic as the select line, but we really should wait until we have a clear solution for the NVDA issue describe in https://github.com/grommet/grommet/issues/6204#issuecomment-1170320696. But here's the logic anyway.

https://github.com/grommet/grommet/blob/04505a6838827267168b75164af799af06e41835/src/js/components/DataTable/Body.js#L90

### Expected Behavior

When navigating the [group/on-select example](https://storybook.grommet.io/?path=/story/visualizations-datatable-grouped-and-onselect--grouped-on-select-data-table) with the NVDA screen reader, I would be able to hear context about the row each expand button will be expanding (or collapsing)

### Actual Behavior

It just says "expand"

### URL, screen shot, or Codepen exhibiting the issue

n.a. it's a screen reader

### Steps to Reproduce

Sorry I'm in a rush so I can't provide this step by step. You just need to use the screen reader to navigate to the cell that contains the expand/collapse arrows.

### Your Environment

Grommet version: whatever was in the storybook website on 6/27/2021
Browser Name and version: 101.0.1 (64-bit)
Operating System and version (desktop or mobile): Windows Version 10.0.19042

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
Adds a new `expandLabel` to `rowDetails` or `groupBy` object.

#### Where should the reviewer start?
ExpanderCell.js 
#### What testing has been done on this PR?
Passed `rowExpandLabel` to one of the DataTable stories
How should this be manually tested?
look at the ControlledGrouped story in Storybook
Use a screen reader or inspect the expand/collapse buttons

#### Do Jest tests follow these best practices?
TODO 
- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

Any background context you want to provide?
Previously, group expand/collapse buttons in DataTable only had generic "expand" and "collapse" labels, making it difficult for screen reader users to understand what content they were expanding.

What are the relevant issues?
closes #6213

Screenshots (if appropriate)

Do the grommet docs need to be updated?
Yes

Should this PR be mentioned in the release notes?
Yes 

Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/DataTable/ExpanderCell.js [hunk 1]
```diff
@@ -35,11 +42,17 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
   );
 
   if (onToggle) {
+    let a11yTitle;
```
Comment (taysea) [inline src/js/components/DataTable/ExpanderCell.js:70]: A logic suggestion:

```
let a11yTitle = expanded ? 'collapse' : 'expand';
if (rowExpandedLabel) a11yTitle = `${a11yTitle} ${rowExpandLabel}`;
```

File: src/js/components/DataTable/Body.js [hunk 2]
```diff
@@ -33,6 +33,7 @@ const Row = memo(
     setActive,
     setRowExpand,
     rowExpand,
+    rowExpandLabel,
```
Comment (taysea) [inline src/js/components/DataTable/Body.js]: Thinking about naming suggestions (since this applies for `rowDetails` and `groupBy` and to clarify that its an ariaLabel not a visual label):
- `expandAriaLabel` (my top suggestion)
- `rowExpandAriaLabel` (kinda long)

@jcfilben

**Review by taysea — COMMENTED** [review]
The approach seems reasonable, just a small suggestion on naming of prop

File: src/js/components/DataTable/Body.js (hunk 2 above)
Comment (jcfilben) [reply src/js/components/DataTable/Body.js]: Good idea clarifying that this is an aria label. I think `expandAriaLabel` is clear enough. Agree `rowExpandAriaLabel` starts getting a little long

File: src/js/components/DataTable/ExpanderCell.js (hunk 1 above)
Comment (jcfilben) [reply src/js/components/DataTable/ExpanderCell.js:70]: Should we internationalize the `expand` and `collapse` strings?

File: src/js/components/DataTable/Body.js (hunk 2 above)
Comment (britt6612) [reply src/js/components/DataTable/Body.js]: yeah thats fine `expandAriaLabel` makes sense

**Comment by britt6612** [comment]
> Could we add a jest test?

yes I was kinda holding off on this until we were good with direction and naming but was in my TODO

File: src/js/components/DataTable/ExpanderCell.js (hunk 1 above)
Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js:70]: we can? I think it would help forsure!

File: src/js/components/DataTable/Body.js (hunk 2 above)
Comment (britt6612) [reply src/js/components/DataTable/Body.js]: changed name

**Comment by britt6612** [comment]
> Could we add a jest test?

added the tests @jcfilben

File: src/js/components/DataTable/ExpanderCell.js (hunk 1 above)
Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js:70]: implemented logic suggestion and internationalized the expand and collapse

**Comment by jcfilben** [comment]
I wonder if we should pass back the row and the key to `expandAriaLabel` when it is a function similar to how we pass row through `rowDetails`. That way someone could do something like this: `expandAriaLabel={(row) => 'details for ${row.name}'}`

**Comment by britt6612** [comment]
> I'm not sure I understand the utility of passing a string to expandAriaLabel. It seems like at the moment the string just gets read out exactly as is. I can't think of a case where someone would want each expand/collapse button to have the same arialabel. I could see the string having utility if we did something where we could pass expandAriaLabel="location" and we have a location column and the data in that column gets read out as the aria label.

my thinking here was if they only had one item that was expand/collapse then they can pass a string to just apply to that one aria-label.

**Comment by britt6612** [comment]
> I wonder if we should pass back the row and the key to `expandAriaLabel` when it is a function similar to how we pass row through `rowDetails`. That way someone could do something like this: `expandAriaLabel={(row) => 'details for ${row.name}'}`

I can look at adding this if we think it will benefit

File: src/js/components/DataTable/propTypes.js [hunk 3]
```diff
@@ -130,7 +130,9 @@ if (process.env.NODE_ENV !== 'production') {
     ]),
     messages: PropTypes.shape({
       ascending: PropType.string,
+      collapse: PropType.string,
```
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/DataTable/propTypes.js]: done

File: src/js/components/DataTable/propTypes.js [hunk 4]
```diff
@@ -130,7 +130,9 @@ if (process.env.NODE_ENV !== 'production') {
...
       descending: PropType.string,
+      expand: PropType.string,
```
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/DataTable/propTypes.js]: done

File: src/js/components/DataTable/ExpanderCell.js [hunk 5]
```diff
@@ -35,11 +47,45 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
...
+        id: 'dataTable.collapse',
+        messages: {
+          'dataTable.collapse': 'collapse',
+        },
+      });
+
+    let a11yTitle;
+
+    if (context === 'header') {
+      a11yTitle = expanded ? 'collapse all' : 'expand all';
```
Comment (jcfilben) [inline src/js/components/DataTable/ExpanderCell.js]: Can we internationalize theses strings?

File: src/js/components/DataTable/ExpanderCell.js [hunk 6]
```diff
@@ -35,11 +47,45 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
...
+    } else {
+      a11yTitle = expanded ? collapseText : expandText;
+
+      if (expandAriaLabel) {
+        const ariaLabel =
+          typeof expandAriaLabel === 'function'
+            ? expandAriaLabel(row, groupKey)
+            : expandAriaLabel;
```
Comment (jcfilben) [inline src/js/components/DataTable/ExpanderCell.js]: If expandAriaLabel isn't a function it seems like `ariaLabel` should just be undefined

File: src/js/components/DataTable/index.d.ts [hunk 7]
```diff
@@ -117,6 +119,7 @@ export interface DataTableProps<TRowType = any> {
         expand?: (string | number)[];
         onExpand?: (expandedKeys: (string | number)[], datum: TRowType) => void;
       };
+  expandAriaLabel?: (row: TRowType, groupKey: any) => string;
```
Comment (jcfilben) [inline src/js/components/DataTable/index.d.ts]: Will groupKey always be a string?
```suggestion
  expandAriaLabel?: (row: TRowType, groupKey: string) => string;
```

**Review by jcfilben — COMMENTED** [review]
Could we add an expandAriaLabel to any DataTable story that has groups or rowDetails? That way we show best practice in our stories

File: src/js/components/DataTable/index.d.ts (hunk 7 above)
Comment (britt6612) [reply src/js/components/DataTable/index.d.ts]: Im not sure I wonder if it could also be a number 🤔

File: src/js/components/DataTable/ExpanderCell.js (hunk 5 above)
Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: done

File: src/js/components/DataTable/ExpanderCell.js (hunk 6 above)
Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: in body.js Im passing 

```
    expandAriaLabel={
              expandAriaLabel ? expandAriaLabel(datum) : undefined
            }
```

so because of this in ExpanderCell.js `expandAriaLabel` gets passed a string. If I passed it directly 
`expandAriaLabel={ExpandAriaLabel}` the problem with this is that in ExpanderCell we do not have access to the specific datum of that row. So we need to do this ` expandAriaLabel ? expandAriaLabel(datum)` in which sends the specific row string to expandAriaLabel so in ExpanderCell the `expandAriaLabel` is a string not a func

let me know if this makes sense

File: src/js/languages/default.json [hunk 8]
```diff
@@ -57,6 +57,8 @@
   },
   "dataTable": {
     "ascending": "ascending",
+    "collapse": "collapse",
+    "expand": "expand",
```
Comment (taysea) [inline src/js/languages/default.json]: nit pick, alphabetize

File: src/js/components/DataTable/ExpanderCell.js (hunk 5 above)
Comment (taysea) [reply src/js/components/DataTable/ExpanderCell.js]: The collapse all and expand all don't seem to be internationalized

Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: weird these changes didnt commit

Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: thanks for catching ill push up!

File: src/js/languages/default.json (hunk 8 above)
Comment (britt6612) [reply src/js/languages/default.json]: done

File: src/js/components/DataTable/ExpanderCell.js (hunk 5 above)
Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: @taysea pushed up

File: src/js/components/DataTable/Body.js [hunk 9]
```diff
@@ -176,6 +177,9 @@ const Row = memo(
             }}
             pad={cellProps.pad}
             verticalAlign={verticalAlign}
+            expandAriaLabel={
+              expandAriaLabel ? expandAriaLabel(datum) : undefined
```
Comment (taysea) [inline src/js/components/DataTable/Body.js]: Is it confusing that for the grouped case we pass 2 things to the function but for the body we just pass the datum?

File: src/js/components/DataTable/index.d.ts (hunk 7 above)
Comment (taysea) [reply src/js/components/DataTable/index.d.ts]: The way this is written, the non-grouped case would fail on Typescript because we're only passing it a single argument

File: src/js/components/DataTable/Body.js (hunk 9 above)
Comment (britt6612) [reply src/js/components/DataTable/Body.js]: yes I see your point how this could be confusing.  @taysea 

GROUPED case (GroupedBody):
`expandAriaLabel(row, groupKey)`

ROW DETAILS case (Body):
`expandAriaLabel(datum)`


In the Row Details case what you think if we change to 

```
expandAriaLabel={
  expandAriaLabel ? expandAriaLabel(datum, undefined) : undefined
}
```

File: src/js/components/DataTable/index.d.ts (hunk 7 above)
Comment (britt6612) [reply src/js/components/DataTable/index.d.ts]: see my comment below about updating the non-group case

File: src/js/components/DataTable/propTypes.js [hunk 10]
```diff
@@ -174,6 +178,7 @@ if (process.env.NODE_ENV !== 'production') {
     replace: PropTypes.bool,
     resizeable: PropTypes.bool,
     rowProps: PropTypes.shape({}),
+    expandAriaLabel: PropTypes.oneOfType([PropTypes.func, PropTypes.string]),
```
Comment (taysea) [inline src/js/components/DataTable/propTypes.js]:
```suggestion
    expandAriaLabel: PropTypes.func,
```

File: src/js/components/DataTable/index.d.ts [hunk 11]
```diff
@@ -117,6 +121,7 @@ export interface DataTableProps<TRowType = any> {
         expand?: (string | number)[];
         onExpand?: (expandedKeys: (string | number)[], datum: TRowType) => void;
       };
+  expandAriaLabel?: ({ row }: { row: TRowType }) => string | string;
```
Comment (taysea) [inline src/js/components/DataTable/index.d.ts]: I know I suggested this object approach, but now I'm thinking maybe we just match the structure of `rowDetails` and pass it back as `(row) => `

Comment (britt6612) [reply src/js/components/DataTable/index.d.ts]: changed back!

File: src/js/components/DataTable/ExpanderCell.js [hunk 12]
```diff
@@ -35,11 +46,68 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
...
+        if (typeof expandAriaLabel === 'function') {
+          if (context === 'groupHeader') {
+            ariaLabel = expandAriaLabel(row.datum);
+          } else {
+            ariaLabel = expandAriaLabel(row);
+          }
+        } else {
+          ariaLabel = expandAriaLabel;
+        }
+        a11yTitle = `${a11yTitle} ${ariaLabel}`;
```
Comment (MikeKingdom) [inline src/js/components/DataTable/ExpanderCell.js]: This looks to me like it's trying to compose a phrase by concatenating several parts. This is something we need to avoid when internationalizing. Text should be combined via substitution parameters for the overall phrase so localizers can order things as best makes sense for the language.

File: src/js/components/DataTable/ExpanderCell.js [hunk 13]
```diff
@@ -35,11 +46,68 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
   );
 
   if (onToggle) {
+    const expandText =
+      messages?.expand ||
+      format({
+        id: 'dataTable.expand',
+        messages: {
+          'dataTable.expand': 'expand',
+        },
```
Comment (MikeKingdom) [inline src/js/components/DataTable/ExpanderCell.js]: Why are these basically hardcoding messages? This parameter should simply be `messages`

Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: sorry was testing then forgot to revert back to `messages` changed now

Comment (taysea) [reply src/js/components/DataTable/ExpanderCell.js]: Seems like the commit to revert this back didn't get pushed up

File: src/js/components/DataTable/ExpanderCell.js [hunk 14]
```diff
@@ -35,11 +45,61 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
...
+        values: { label: expandLabel || '' },
+      });
+
+    const collapseText =
+      messages?.collapse ||
+      format({
+        id: 'dataTable.collapse',
+        messages: {
```
Comment (taysea) [inline src/js/components/DataTable/ExpanderCell.js]: Same with here, seems like this should just be messages

**Review by taysea — COMMENTED** [review]
I like the modified direction to include the property in the object of `rowDetails` and `groupBy`. A few small comments.

File: src/js/components/DataTable/ExpanderCell.js (hunk 14 above)
Comment (britt6612) [reply src/js/components/DataTable/ExpanderCell.js]: ah weird thought I pushed up! pushing up now

File: src/js/components/DataTable/ExpanderCell.js [hunk 15]
```diff
@@ -35,11 +45,57 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
...
+      format({
+        id: 'dataTable.collapseAll',
+        messages,
+      });
+
+    let a11yTitle;
+    if (expandLabel) {
+      a11yTitle = format({
+        id: expanded ? 'dataTable.collapse' : 'dataTable.expand',
+        messages: {
```
Comment (taysea) [inline src/js/components/DataTable/ExpanderCell.js]: Should this just be `messages` too?

Comment (taysea) [reply src/js/components/DataTable/ExpanderCell.js]: Pushed a change for this.

File: src/js/components/DataTable/ExpanderCell.js [hunk 16]
```diff
@@ -35,11 +45,54 @@ const ExpanderControl = ({ context, expanded, onToggle, pad, ...rest }) => {
   );
 
   if (onToggle) {
+    const expandText =
+      messages?.expand ||
```
Comment (taysea) [inline src/js/components/DataTable/ExpanderCell.js]: Do we need this `||` condition or can it simply be `format({ ...})`?

Comment (taysea) [reply src/js/components/DataTable/ExpanderCell.js]: Pushed fix.

Comment (MikeKingdom) [reply src/js/components/DataTable/ExpanderCell.js]: Shouldn't need these checks. `format` was designed with the expectation that at least the base messages from grommet has the messages

**Review by taysea — APPROVED** [review]
LGTM, thanks!
