### PR TITLE
RangeSelector - add theme value for the edge size

### LINKED ISSUE #7669: RangeSelector - WCAG 2.5.8 target size
### Is this something you or your team is interested in contributing a pull request towards?

Yes

### Expected Behavior

RangeSelector fails 2.5.8

The circular buttons on either side of the slider do not meet the minimum interactive target size of 24×24. 

once PR is merged need to update DS site.

- [ ] Update DataFilters, DataFilter rule 2.5.8

### Actual Behavior

The circular buttons are 12×12.

### URL, Screenshot, or CodeSandbox

rangeselector component 

### Steps to Reproduce

_No response_

### Your Environment

_No response_

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR adds a theme value for the theme to allow users to pass a value for `edge` size
#### Where should the reviewer start?
EdgeControl.js
#### What testing has been done on this PR?
locally and wrote a test 
#### How should this be manually tested?
pass in a value for `theme.rangeSelector?.edge?.size;`

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
The size needs to be at least 24X24 
right now we have it at 12X12 so we dont break the current size I have added a theme option for us to use in the hpe theme 
#### What are the relevant issues?
closes #7669 
#### Do the grommet docs need to be updated?
yes
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
 backwards compatible

### CODE REVIEW

File: src/js/components/RangeSelector/EdgeControl.js [hunk 1]
```diff
@@ -29,7 +29,11 @@ const EdgeControl = forwardRef(
     const { theme } = useThemeValue();
     const [focus, setFocus] = useState(false);
     const { cursor, fill } = DIRECTION_PROPS[direction];
-    const size = parseMetricToNum(theme.global.spacing) / 2;
+    const themeSize = theme.rangeSelector?.edge?.size;
+    const size =
```
Comment (jcfilben) [inline src/js/components/RangeSelector/EdgeControl.js]: What if they want to pass a px value instead of a t-shirt size?

Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: It still comes through

File: src/js/components/RangeSelector/EdgeControl.js [hunk 2]
```diff
@@ -29,7 +29,11 @@ const EdgeControl = forwardRef(
...
+      typeof themeSize === 'string'
```
Comment (taysea) [inline src/js/components/RangeSelector/EdgeControl.js]: Do we need this check? Can we enforce this in typescript definition and propTypes?

File: src/js/components/RangeSelector/EdgeControl.js [hunk 3]
```diff
@@ -29,7 +29,11 @@ const EdgeControl = forwardRef(
     const { theme } = useThemeValue();
     const [focus, setFocus] = useState(false);
     const { cursor, fill } = DIRECTION_PROPS[direction];
-    const size = parseMetricToNum(theme.global.spacing) / 2;
+    const themeSize = theme.rangeSelector?.edge?.size;
```
Comment (taysea) [inline src/js/components/RangeSelector/EdgeControl.js]: naming suggestion for clarity.
```suggestion
    const themeEdgeSize = theme.rangeSelector?.edge?.size;
```

**Review by taysea — COMMENTED** [review]
Behavior looks good, just some minor comments.

File: src/js/components/RangeSelector/EdgeControl.js (hunk 2 above)
Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: yes we dont need the check

File: src/js/components/RangeSelector/EdgeControl.js [hunk 4]
```diff
@@ -29,7 +29,12 @@ const EdgeControl = forwardRef(
     const { theme } = useThemeValue();
     const [focus, setFocus] = useState(false);
     const { cursor, fill } = DIRECTION_PROPS[direction];
-    const size = parseMetricToNum(theme.global.spacing) / 2;
+    const themeEdgeSize = theme.rangeSelector?.edge?.size;
+    const size = themeEdgeSize
+      ? parseMetricToNum(
+          theme.global.edgeSize?.[themeEdgeSize] || themeEdgeSize,
```
Comment (halocline) [inline src/js/components/RangeSelector/EdgeControl.js]: So this logic says "look up the string to see if it is defined in the theme's global edgeSize, if so, use the referenced value; if not, its probably a CSS value and use it." Is that correct?

Should we be thinking about stronger type safety for `rangeSelector.edge.size`? Something like `EdgeSizeType | string` and introducing `EdgeSizeType`?

File: src/js/components/RangeSelector/__tests__/RangeSelector-test.tsx [hunk 5]
```diff
@@ -22,6 +22,24 @@ describe('RangeSelector', () => {
     expect(container.firstChild).toMatchSnapshot();
   });
 
+  test('basic with theme edge size', () => {
```
Comment (halocline) [inline src/js/components/RangeSelector/__tests__/RangeSelector-test.tsx:25]: Please consider the following options for additional test coverage.



Here are example test cases you can add to further ensure the RangeSelector component correctly supports the edge size theme property:

---

### 1. Test each supported edge size

```js
const edgeSizes = ['small', 'medium', 'large', 'xlarge']; // use all supported sizes

edgeSizes.forEach(size => {
  test(`renders with edge size: ${size}`, () => {
    const theme = {
      rangeSelector: {
        edge: { size },
      },
    };
    const { container } = render(
      <Grommet theme={theme}>
        <RangeSelector values={[10, 40]} />
      </Grommet>
    );
    expect(container.firstChild).toMatchSnapshot();
  });
});
```

---

### 2. Test default edge size

```js
test('renders with default edge size when not specified', () => {
  const theme = {
    rangeSelector: {},
  };
  const { container } = render(
    <Grommet theme={theme}>
      <RangeSelector values={[5, 25]} />
    </Grommet>
  );
  expect(container.firstChild).toMatchSnapshot();
});
```

---

### 3. Test with an invalid edge size

```js
test('renders gracefully with invalid edge size', () => {
  const theme = {
    rangeSelector: {
      edge: { size: 'not-a-real-size' },
    },
  };
  const { container } = render(
    <Grommet theme={theme}>
      <RangeSelector values={[15, 35]} />
    </Grommet>
  );
  expect(container.firstChild).toMatchSnapshot();
});
```

---

File: src/js/themes/base.d.ts [hunk 6]
```diff
@@ -1672,6 +1672,7 @@ export interface ThemeType {
     };
     edge?: {
       type?: string;
+      size?: string;
```
Comment (halocline) [inline src/js/themes/base.d.ts]: See comment about whether `EdgeSizeType` would be a valuable addition.

File: src/js/components/RangeSelector/EdgeControl.js (hunk 4 above)
Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: yes that is correct I added some comments as well

File: src/js/themes/base.d.ts (hunk 6 above)
Comment (britt6612) [reply src/js/themes/base.d.ts]: used our `EdgeSizeType` here

File: src/js/components/RangeSelector/EdgeControl.js [hunk 7]
```diff
@@ -29,7 +29,23 @@ const EdgeControl = forwardRef(
     const { theme } = useThemeValue();
     const [focus, setFocus] = useState(false);
     const { cursor, fill } = DIRECTION_PROPS[direction];
-    const size = parseMetricToNum(theme.global.spacing) / 2;
+    const themeEdgeSize = theme.rangeSelector?.edge?.size;
+    let size;
+    if (themeEdgeSize != null) {
```
Comment (MikeKingdom) [inline src/js/components/RangeSelector/EdgeControl.js]: Any reason this is != rather than !==? Or should it simply be `if (themeEdgeSize)`? According to the type it is supposed to always be a tshirt size or some other string (probably non-empty or 0). So it seems like `if (themeEdgeSize)` should be good. If you need to support 0 it should still be something more robust (it seems like this may be possible given how you default to using `themeEdgeSize` if there's not a mapping in `global.edgeSize`.)

Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: agree it can be simplified

**Review by MikeKingdom — APPROVED** [review]
Thanks!
