### PR TITLE
fix:prevent-extra-div-container-in-drop-component

### LINKED ISSUE #6371: Tip - hovering over child creates empty divs that aren't cleaned up
Hovering over the child component wrapped by Tip will create empty `<div></div>
`
### Expected Behavior

If a div is created for whatever reason, it's also cleaned up afterwards

### Actual Behavior

Hovering over the child component wrapped in Tip will endlessly create more divs

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/bitter-sunset-edyo97?file=/src/App.tsx

### Steps to Reproduce (In the Codesandbox example)

1. Wrap an element with Tip (example uses `<button/>`)
2. Open devtools and inspect elements
3. Navigate to the `<iframe/>`  element of the codesandbox preview window
4. Navigate to the `<body/>` element within that
5. Now hover over the component wrapped in Tip
6. Notice the empty div elements are being appended to the end of the `<body/>`

### Your Environment

- Grommet version:2.26.0 in Codesandbox; Also experienced in 2.25.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): macOS 11.6.5

### PR DESCRIPTION
**Pull request by Locen9**
#### What does this PR do?
It prevent Drop.js Component from creating multiple divs when running App in StrictMode

#### Where should the reviewer start?
From Drop.js in src/js/components/Drop/Drop.js

#### What testing has been done on this PR?
I tested it on a local environment adding Grommet as a library and creating a very simple react App (in StrictMode) with one Tip component that uses the Drop component inside. (I basically reproduced the codebox example of the issue #6371 ). Eventually I ran storybook to see possible regressions and found none.

#### How should this be manually tested?
I was not able to reproduce it without wrapping the App in StrictMode

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
I encountered this issue on  a personal project by using the Tip Component, I found out that only in a dev-build I was seeing this issue and prod build were bug free.

#### What are the relevant issues?
it closes #6371

#### Is this change backwards compatible or is it a breaking change?
it is backwards compatible

### CODE REVIEW

File: src/js/components/Drop/Drop.js [hunk 1]
```diff
@@ -24,13 +30,15 @@ const Drop = forwardRef(
     useEffect(() => setOriginalFocusedElement(document.activeElement), []);
     const [dropContainer, setDropContainer] = useState();
     const containerTarget = useContext(ContainerTargetContext);
-    useEffect(
-      () =>
+    const containerChildNodesLenght = useRef(null);
```
Comment (jcfilben) [inline src/js/components/Drop/Drop.js:33]: Why does this need to be a ref? I think it could just be a regular variable. Also can we rename to `containerChildNodesLength` and add a comment about why we need this check for the Tip component

**Review by jcfilben — COMMENTED** [review]
Nice work so far, just a few comments...

**Comment by jcfilben** [comment]
I realized that strict mode intentionally renders things twice so I wonder if this issue is to be expected or if it is still something that should be fixed

File: src/js/components/Drop/Drop.js (hunk 1 above)
Comment (Locen9) [reply src/js/components/Drop/Drop.js]: Hi jcfilben, thanks for your feedback!

I added a comment and changed the misspelled variable name.

Unfortunately using a variable will not resolve this: 

- if we define the variable inside the useEffect and then assign it inside the if condition, the issue will not be solved when the component is destroyed and then re-created, as everytime the useEffect runs,  the variable will be initialised again and the if condition will always be true.
- if we define the variable outside the useEffect and assign a value inside, it will lose its assignment after each render which will fix this issue as long as the drop component is without any side-effects.(A tooltip generating plain text will work fine). 
In a bit more complex case in which the parent element of the Drop component has sideEffects that updates the dropped element (i.e. a Calendar), the variable will be re-initialised and we will incur in the bug again.

I would prefer useRef as it is guaranteed not to change between render(s)

**Comment by Locen9** [comment]
> I realized that strict mode intentionally renders things twice so I wonder if this issue is to be expected or if it is still something that should be fixed

Regarding this, as in the future React may apply [new features](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state), in order to maintain a reusable state and to prevent future headaches, I would go ahed and resolve it.

File: src/js/components/Drop/Drop.js (hunk 1 above)
Comment (jcfilben) [reply src/js/components/Drop/Drop.js]: Thanks for the explanation, that makes sense

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by ericsoderberghp — APPROVED** [review]
