### PR TITLE
Create TabsContext to fix Tab issue

### LINKED ISSUE #4224: Props not being passed from Tabs to Tab when using custom Tab component
I have a component that uses Tab at the top level:
```
const MyTabComponent = props => (
  <Tab title="Tab 2" {...props}>
      <Text>Content for the Second tab</Text>
  </Tab>
);
```

When I render it within tabs like this:
```
<Tabs>
      <Tab title="Tab 1">
         <Text>Content for the First tab</Text>
      </Tab>

      <MyTabComponent />
</Tabs>
```

"Content for the First tab" is displayed in Tab 1 but "Content for the Second tab" is not displayed within Tab 2.

### URL, screen shot, or Codepen exhibiting the issue

Code: https://codesandbox.io/s/grommet-sandbox-tab-composition-issue-447vm?file=/src/Tabs.js
Demo: https://447vm.csb.app/tabs

### Your Environment

- Grommet version: 2.14.0

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?
Creates `TabsContext` which stores the `activeIndex` (needed to properly assign `activeTitle`), if tab is `active` (previously passed to Tab as a prop via clone child), `onActivate` (previously passed to individual Tab as a prop via clone child), `setActiveContent` (allows Tab to assign its children as the active content to be rendered by Tabs, and `setActiveTitle` (for screen reader accessibility).

Previously, Tabs was looking into its children to find what should be the active content displayed. If `Tab` was not the direct descendant of `Tabs`, it wouldn't render the child properly. Now, `Tab` takes more control by assigning its children to the activeContent. This hand-off is done using `TabsContext`.

Closes #4224 

#### Where should the reviewer start?
src/js/components/Tabs/Tabs.js

#### What testing has been done on this PR?
In local storybook, I recreated the setup causing the bug in the filed issue:

```
const MyTabComponent = props => (
  <Tab title="Tab 2" {...props}>
      <Text>Content for the Second tab</Text>
  </Tab>
);
...
...
<Tabs>
      <Tab title="Tab 1">
         <Text>Content for the First tab</Text>
      </Tab>
      <MyTabComponent />
</Tabs>
```

Prior to this change, the content inside of `MyTabComponent` wasn't rendering, but after this change it renders properly.

#### How should this be manually tested?
Same as above.

#### Any background context you want to provide?
Solves [this issue](https://github.com/grommet/grommet/issues/4224), when users created custom Tab component, the tab itself would render but its child content wouldn't.

#### What are the relevant issues?
https://github.com/grommet/grommet/issues/4224

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
No.

#### Is this change backwards compatible or is it a breaking change?
Yes, this is backwards compatible.

### CODE REVIEW

File: src/js/components/Tab/Tab.js [hunk 1]
```diff
@@ -7,30 +7,48 @@ import { Box } from '../Box';
 import { Button } from '../Button';
 import { Text } from '../Text';
 import { normalizeColor } from '../../utils';
+import { TabsContext } from '../Tabs/TabsContext';
```
Comment (halocline) [inline src/js/components/Tab/Tab.js:10]: Nit: Recommend keeping Grommet's component imports grouped alphabetically and util functions can follow.

```suggestion
import { TabsContext } from '../Tabs/TabsContext';
import { normalizeColor } from '../../utils';
```

File: src/js/components/Tab/Tab.js [hunk 2]
```diff
@@ -7,30 +7,48 @@ import { Box } from '../Box';
...
-    },
+    { children, icon, plain, title, onMouseOver, onMouseOut, reverse, ...rest },
     ref,
   ) => {
+    const {
+      active,
+      activeIndex,
+      setActiveContent,
+      setActiveTitle,
+      onActivate,
```
Comment (halocline) [inline src/js/components/Tab/Tab.js:24]: Nit: recommend alphabetical order

```suggestion
      active,
      activeIndex,
      onActivate,
      setActiveContent,
      setActiveTitle,
```

File: src/js/components/Tab/Tab.js [hunk 3]
```diff
@@ -7,30 +7,48 @@ import { Box } from '../Box';
...
 
+    useEffect(() => {
+      if (active) {
+        setActiveContent(children);
+        let activeTitle;
+        if (typeof title === 'string') {
+          activeTitle = title;
+        } else {
+          activeTitle = activeIndex + 1;
+        }
```
Comment (halocline) [inline src/js/components/Tab/Tab.js:40]:
```suggestion
        const activeTitle = typeof title === 'string' ? title : activeIndex + 1;
```

File: src/js/components/Tabs/Tabs.js [hunk 4]
```diff
@@ -49,33 +44,7 @@ const Tabs = forwardRef(
...
-        }
-
-        return cloneElement(tab, {
-          active: isTabActive,
-          onActivate: () => activateTab(index),
-        });
-      },
-      this,
-    );
+    const [activeTitle, setActiveTitle] = useState();
```
Comment (halocline) [inline src/js/components/Tabs/Tabs.js:47]: This seems disconnected from its usage. Recommend either placing together with together rest of state declarations, or directly ahead of its usage.

File: src/js/components/Tabs/Tabs.js [hunk 5]
```diff
@@ -114,7 +83,21 @@ const Tabs = forwardRef(
           gap={theme.tabs.gap}
           {...tabsHeaderStyles}
         >
-          {tabs}
```
Comment (halocline) [inline src/js/components/Tabs/Tabs.js:117]: For readability, I kind of liked having `tabs` defined above.

Consider `const tabs = React.Children.map( ...`

File: src/js/components/Tabs/Tabs.js [hunk 6]
```diff
@@ -114,7 +83,21 @@ const Tabs = forwardRef(
...
+          {React.Children.map(children, (child, index) => (
+            <TabsContext.Provider
+              // eslint-disable-next-line react/no-array-index-key
+              key={index}
```
Comment (halocline) [inline src/js/components/Tabs/Tabs.js:89]: `key` does not need to be specified here. `React.Children.map()` is already generating unique keys. So `key` can be removed.
```suggestion
```

File: src/js/components/Tabs/Tabs.js [hunk 7]
```diff
@@ -114,7 +83,21 @@ const Tabs = forwardRef(
           gap={theme.tabs.gap}
           {...tabsHeaderStyles}
         >
-          {tabs}
+          {React.Children.map(children, (child, index) => (
+            <TabsContext.Provider
+              // eslint-disable-next-line react/no-array-index-key
```
Comment (halocline) [inline src/js/components/Tabs/Tabs.js:88]: This could be removed as well if the key={index} is removed. Missed this before.

```suggestion
```

File: src/js/components/Tabs/Tabs.js (hunk 5 above)
Comment (taysea) [reply src/js/components/Tabs/Tabs.js:117]: Good clean up idea.

File: src/js/components/Tabs/Tabs.js (hunk 6 above)
Comment (taysea) [reply src/js/components/Tabs/Tabs.js:89]: Good clean up, thanks!

**Comment by ericsoderberghp** [comment]
> Thoughts on tests? A snapshot test for supplying a custom component as a child of Tabs might be beneficial.

+1

File: src/js/components/Tabs/Tabs.js (hunk 4 above)
Comment (taysea) [reply src/js/components/Tabs/Tabs.js:47]: Agreed, will group it with the other declarations.

**Comment by taysea** [comment]
> Nice improvements @taysea! Minor comments / suggestions.
> 
> Thoughts on tests? A snapshot test for supplying a custom component as a child of Tabs might be beneficial.
> 
> Lastly, does the custom component need to be a `<Tab />`? What happens if `<Tab />` isn't supplied as the custom component?

The custom component still needs to be a tab. If you supply a box or other component, it will place that in the Tab header. However, I think we are okay with this because this is being placed inside `Tabs`, so if you never supply a `Tab` it seems like it would be expected not to work.

**Comment by ShimiSun** [comment]
>The custom component still needs to be a tab. If you supply a box or other component, it will place that in the Tab header. However, I think we are okay with this because this is being placed inside Tabs, so if you never supply a Tab it seems like it would be expected not to work.

Is there a way to document it? maybe add a warning? just throwing ideas.

**Comment by taysea** [comment]
> > The custom component still needs to be a tab. If you supply a box or other component, it will place that in the Tab header. However, I think we are okay with this because this is being placed inside Tabs, so if you never supply a Tab it seems like it would be expected not to work.
> 
> Is there a way to document it? maybe add a warning? just throwing ideas.

I like the idea of adding a console warning. In addition, something could be added to Tabs documentation?

**Comment by taysea** [comment]
> Nice work! The testing coverage didn't change and overall it looks good to be. Also, I agree that we should add a warning for when the custom component is not a `Tab`, and perhaps a test to go with it too.

Thanks, @JoeButler7! Do you have any suggestions re: the console warning? In my above comment I just added a description of what I tried but I'm not sure it's the best approach.

**Comment by JoeButler7** [comment]
> > Nice work! The testing coverage didn't change and overall it looks good to be. Also, I agree that we should add a warning for when the custom component is not a `Tab`, and perhaps a test to go with it too.
> 
> Thanks, @JoeButler7! Do you have any suggestions re: the console warning? In my above comment I just added a description of what I tried but I'm not sure it's the best approach.

If we can't access the children of a custom component then it might be better to just put a note in the documentation about it. Checking the children was the only approach that I could think of and I got the same result that you did

**Comment by ericsoderberghp** [comment]
I don't think we need a warning. It's problematic for a parent to assert something about a child.
