### PR TITLE
Button - allow caller to specify icon for kind in theme and enhance kind padding

### LINKED ISSUE #6271: Button theme should support specification of icon for kind
### Expected Behavior

Should be apply to specify `button[kind].icon` so that specific button kinds can have an icon built in. 

### Actual Behavior

Not possible.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

Adds `theme.button[kind].icon`, `theme.button.hover[kind].icon`, `theme.button.active[kind].icon`, `theme.button.disabled[kind].icon` to allow theme to include a specific icon in a button kind.

Additionally, enhances `theme.button.size` to accept kind specific padding. This allows certain button kinds to take on different padding than other button kinds.

Also, in addition to adding relevant tests for this functionality, I fixed a `size` test that was written incorrectly. The snapshot was not showing the desired styling --> this PR updates the test and I have verified the snapshot changes now render the desired styling.

Also, adding `string` as an accepted button size -- based on need from upcoming grommet-theme-hpe changes.

 
#### What testing has been done on this PR?
Locally in storybook by adjusted Themed Button TS story:

```
import React from 'react';

import { Box, Button, Grommet, Heading, Paragraph, Text } from 'grommet';
import { Hpe } from 'grommet-icons';
import { hpe } from 'grommet-theme-hpe';
import { deepMerge } from '../../../../utils';

const kindButtonTheme = deepMerge(hpe, {
  button: {
    size: {
      small: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '4px',
          horizontal: '8px',
        },
        'cta-primary': {
          pad: {
            vertical: '3px',
            horizontal: '12px',
          },
        },
        'cta-alternate': {
          pad: {
            vertical: '3px',
            horizontal: '12px',
          },
        },
      },
      medium: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '6px',
          horizontal: '12px',
        },
        'cta-primary': {
          pad: {
            vertical: '6px',
            horizontal: '16px',
          },
        },
        'cta-alternate': {
          pad: {
            vertical: '6px',
            horizontal: '16px',
          },
        },
      },
      large: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '8px',
          horizontal: '16px',
        },
        'cta-primary': {
          pad: {
            vertical: '8px',
            horizontal: '20px',
          },
        },
        'cta-alternate': {
          pad: {
            vertical: '8px',
            horizontal: '20px',
          },
        },
      },
      xlarge: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '10px',
          horizontal: '20px',
        },
        'cta-primary': {
          pad: {
            vertical: '10px',
            horizontal: '28px',
          },
        },
        'cta-alternate': {
          pad: {
            vertical: '10px',
            horizontal: '28px',
          },
        },
      },
    },
    extend: ({ sizeProp }) => {
      let fontSize = '19px';
      let lineHeight = '24px';
      if (sizeProp === 'small') {
        fontSize = '16px';
        lineHeight = '22px';
      } else if (sizeProp === 'large') {
        fontSize = '20px';
        lineHeight = '26px';
      } else if (sizeProp === 'xlarge') {
        fontSize = '22px';
        lineHeight = '28px';
      }
      return `
    font-size: ${fontSize};
    line-height: ${lineHeight}
    `;
    },
    'cta-primary': {
      background: { color: 'brand' },
      border: {
        radius: '100px',
      },
      color: 'white',
      font: { weight: 'bold' },
      icon: <Hpe />,
      reverse: true,
      size: {
        small: {
          pad: {
            vertical: '3px',
            horizontal: '12px',
          },
        },
      },
    },
    'cta-alternate': {
      background: 'background-contrast',
      border: {
        radius: '100px',
      },
      color: 'text-strong',
      font: {
        weight: 'bold',
      },
      icon: <Hpe color="brand" />,
      reverse: true,
    },
    active: {
      'cta-alternate': {
        icon: <Hpe color="brand" />,
      },
    },
    disabled: {
      'cta-alternate': {
        border: {
          width: '2px',
          color: 'text-xweak',
        },
      },
      'cta-primary': {
        border: {
          width: '2px',
          color: 'text-xweak',
        },
      },
    },
    secondary: {
      border: {
        color: 'brand',
      },
    },
  },
});

const customTheme = {
  global: {
    font: {
      family: 'Arial',
    },
  },
  button: {
    border: {
      radius: undefined,
      color: '#2196f3',
    },
    disabled: {
      color: 'orange',
      border: {
        color: 'orange',
      },
      extend: `border: 10px dashed red;`,
    },
    padding: {
      vertical: '12px',
      horizontal: '24px',
    },
    primary: {
      color: '#2196f3',
      active: {
        border: {
          color: 'red',
        },
        extend: `background: cadetblue;`,
      },
      extend: `background: skyblue; border: 5px dotted green;`,
    },
    extend: (props) => {
      let extraStyles = '';
      if (props.primary) {
        extraStyles = `
            text-transform: uppercase;
          `;
      }
      return `
          font-size: 12px;
          font-weight: bold;
          ${extraStyles}
        `;
    },
  },
};

const coloredButton = {
  button: {
    border: {
      color: 'accent-1',
    },
    color: { dark: 'accent-1', light: 'dark-2' },
    primary: {
      color: 'neutral-2',
    },
  },
};

const PrimaryButtons = () => (
  <Box gap="medium">
    <Button
      alignSelf="start"
      label="Primary small"
      onClick={() => {}}
      color="brand"
      primary
      size="small"
    />
    <Button
      alignSelf="start"
      label="Primary"
      onClick={() => {}}
      primary
      color="brand"
    />
    <Button
      alignSelf="start"
      label="Primary large"
      onClick={() => {}}
      primary
      color="brand"
      size="large"
    />
    <Button
      alignSelf="start"
      label="Primary xlarge"
      onClick={() => {}}
      primary
      color="brand"
      size="xlarge"
    />
    <Button
      alignSelf="start"
      label="Disabled Primary"
      onClick={() => {}}
      primary
      disabled
    />
    <Button
      alignSelf="start"
      label="Active Primary"
      onClick={() => {}}
      primary
      active
    />
  </Box>
);

const DefaultButtons = () => (
  <Box gap="medium">
    <Button
      alignSelf="start"
      label="Default small"
      onClick={() => {}}
      size="small"
    />
    <Button alignSelf="start" label="Default" onClick={() => {}} />
    <Button
      alignSelf="start"
      label="Default large"
      onClick={() => {}}
      size="large"
    />
    <Button label="Default xlarge" onClick={() => {}} size="xlarge" />
    <Button
      alignSelf="start"
      label="Disabled Default"
      onClick={() => {}}
      disabled
    />
    <Button
      alignSelf="start"
      label="Active Default"
      onClick={() => {}}
      active
    />
  </Box>
);

const SecondaryButtons = () => (
  <Box gap="medium">
    <Button
      alignSelf="start"
      label="Secondary small"
      onClick={() => {}}
      secondary
      size="small"
    />
    <Button alignSelf="start" label="Secondary" onClick={() => {}} secondary />
    <Button
      alignSelf="start"
      label="Secondary large"
      onClick={() => {}}
      size="large"
      secondary
    />
    <Button
      label="Secondary xlarge"
      onClick={() => {}}
      size="xlarge"
      secondary
    />
    <Button
      alignSelf="start"
      label="Disabled Secondary"
      onClick={() => {}}
      disabled
      secondary
    />
    <Button
      alignSelf="start"
      label="Active Secondary"
      onClick={() => {}}
      active
      secondary
    />
  </Box>
);

const CTAPrimary = () => (
  <Box gap="medium">
    <Button
      alignSelf="start"
      label="CTA Primary small"
      onClick={() => {}}
      kind="cta-primary"
      size="small"
    />
    <Button
      alignSelf="start"
      label="CTA Primary"
      onClick={() => {}}
      kind="cta-primary"
    />
    <Button
      alignSelf="start"
      label="CTA Primary large"
      onClick={() => {}}
      size="large"
      kind="cta-primary"
    />
    <Button
      label="CTA Primary xlarge"
      onClick={() => {}}
      size="xlarge"
      kind="cta-primary"
    />
    <Button
      alignSelf="start"
      label="Disabled CTA Primary"
      kind="cta-primary"
      onClick={() => {}}
      disabled
    />
    <Button
      alignSelf="start"
      label="Active CTA Primary"
      kind="cta-primary"
      onClick={() => {}}
      active
    />
  </Box>
);

const CTAAlternate = () => (
  <Box gap="medium">
    <Button
      alignSelf="start"
      label="CTA Alternate small"
      onClick={() => {}}
      size="small"
      kind="cta-alternate"
    />
    <Button
      alignSelf="start"
      label="CTA Alternate"
      onClick={() => {}}
      kind="cta-alternate"
    />
    <Button
      alignSelf="start"
      label="CTA Alternate large"
      onClick={() => {}}
      size="large"
      kind="cta-alternate"
    />
    <Button
      label="CTA Alternate xlarge"
      onClick={() => {}}
      size="xlarge"
      kind="cta-alternate"
    />
    <Button
      alignSelf="start"
      label="Disabled CTA Alternate"
      kind="cta-alternate"
      onClick={() => {}}
      disabled
    />
    <Button
      alignSelf="start"
      label="Active CTA Alternate"
      kind="cta-alternate"
      onClick={() => {}}
      active
    />
  </Box>
);

export const ThemedButtons = () => (
    <Grommet theme={kindButtonTheme}>
        <Box direction="row" gap="large">
          <DefaultButtons />
          <SecondaryButtons />
          <PrimaryButtons />
          <CTAPrimary />
          <CTAAlternate />
        </Box>
    </Grommet>
);

ThemedButtons.storyName = 'Themed Buttons';

export default {
  title: 'Controls/Button/Custom Themed/Themed Buttons',
};
```

#### How should this be manually tested?
In storybook. Can 
#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #6271 

#### Do the grommet docs need to be updated?
Yes.

#### Should this PR be mentioned in the release notes?
Yes.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

File: src/js/components/Button/Button.js [hunk 1]
```diff
@@ -94,6 +98,30 @@ const getIconColor = (paths = [], theme, colorProp, kind) => {
...
+const getKindIcon = (paths = [], theme, kind) => {
+  let result;
+  let index = paths.length - 1;
+  // caller has specified a themeObj to use for styling
+  // relevant for cases like pagination which looks to theme.pagination.button
+  if (typeof kind === 'object') index = 0;
+  // stop when we have a color or no more paths
+  while (index >= 0 && !result) {
+    let obj = (typeof kind === 'object' && kind) || theme.button;
+    // find the sub-object under the button them that corresponds with this path
```
Comment (MikeKingdom) [inline src/js/components/Button/Button.js:111]: typo: them -> theme

**Review by MikeKingdom — COMMENTED** [review]
Looks good. Just a minor typo in a comment

**Review by MikeKingdom — APPROVED** [review]

File: src/js/components/Button/Button.js [hunk 2]
```diff
@@ -281,8 +310,17 @@ const Button = forwardRef(
             theme.global.colors.text[isDarkBackground() ? 'dark' : 'light'],
         });
       }
+    } else if (kind && kindIcon && !plain) {
+      const iconColor =
+        (hover && getIconColor(themePaths.hover, theme)) ||
```
Comment (halocline) [inline src/js/components/Button/Button.js:315]: This gets the color of the icon correctly. However, the way we have the icon defined in the theme:
```
icon: <FormNext />
```
when adding hover[kind].icon, my expectation would be that I could specify another icon for the hover state:
```
hover: {
  ...
  icon: <Add color="blue" />
  ...
}
```
that my icon would also change, but only the color swaps.

Do we want to support both? Or should we rethink how the icon property is structured?

Comment (taysea) [reply src/js/components/Button/Button.js:315]: I would think the icon would also change -- let me look into this.

Comment (taysea) [reply src/js/components/Button/Button.js:319]: Updated in recent commit:

https://user-images.githubusercontent.com/12522275/186539652-b734b80b-3780-4e50-b583-ff58b3d5df59.mov

Comment (halocline) [reply src/js/components/Button/Button.js:319]: 👍

**Review by halocline — COMMENTED** [review]
It seems odd to me that we would need to set if I don't want to modify it from its base:
```
    active: {
      'cta-alternate': {
        icon: <Hpe color="brand" />,
      },
    },
```

My expectation would be that if this is undefined, the active state would inherit the kind's base icon color.

Thoughts? Investigate getIconColor logic?

**Comment by taysea** [comment]
> It seems odd to me that we would need to set if I don't want to modify it from its base:
> 
> ```
>     active: {
>       'cta-alternate': {
>         icon: <Hpe color="brand" />,
>       },
>     },
> ```
> 
> My expectation would be that if this is undefined, the active state would inherit the kind's base icon color.
> 
> Thoughts? Investigate getIconColor logic?

I would agree if it doesn't deviate from its base then I don't think we should have to define it again. Let me investigate the getIconColor logic.

File: src/js/components/Button/Button.js [hunk 3]
```diff
@@ -83,9 +84,16 @@ const getIconColor = (paths = [], theme, colorProp, kind) => {
...
+      // with color defined at one higher level
+      else if (paths[index + 1]) {
+        const parts = paths[index + 1].split('.');
+        while (baseObj && parts.length) obj = baseObj[parts.shift()];
+        if (obj?.icon?.props?.color) color = obj.icon.props.color;
+      }
       // use passed in color for text if the theme doesn't have
       // background or border color
-      else
+      if (!color)
```
Comment (halocline) [inline src/js/components/Button/Button.js:96]: Now we are getting an unexpected change in font color, presumably because the background color is now calculated differently?

Screen Shot 2022-08-25 at 3 57 34 PM

Comment (taysea) [reply src/js/components/Button/Button.js:96]: This issue is already existing on master. I have file a separate issue for it: https://github.com/grommet/grommet/issues/6301

Comment (halocline) [reply src/js/components/Button/Button.js:96]: 👍

File: src/js/components/Button/Button.js [hunk 4]
```diff
@@ -281,8 +322,17 @@ const Button = forwardRef(
...
+      const iconColor =
+        (hover && getIconColor(themePaths.hover, theme)) ||
+        getIconColor(themePaths.base, theme, color, kind);
+      if (iconColor)
+        buttonIcon = cloneElement(kindIcon, {
+          color: iconColor,
+        });
     }
 
+    const reverse = reverseProp || theme.button[kind]?.reverse;
```
Comment (ericsoderberghp) [inline src/js/components/Button/Button.js:335]: If `reverseProp` is `false`, this will use the theme prop instead of allowing the property to override the theme. I think maybe:
```suggestion
    const reverse = reverseProp ?? theme.button[kind]?.reverse;
```

File: src/js/components/Button/index.d.ts [hunk 5]
```diff
@@ -64,7 +64,7 @@ export interface ButtonProps {
   primary?: boolean;
   reverse?: boolean;
   secondary?: boolean;
-  size?: 'small' | 'medium' | 'large';
+  size?: 'small' | 'medium' | 'large' | 'xlarge';
```
Comment (halocline) [inline src/js/components/Button/index.d.ts:67]: If we are saying that Button supports 'xlarge' as a valid `size`, should base.js have a corresponding button xlarge defined? 

Or should we remove 'xlarge' and instead accept a string and document that string as a custom property defined in `theme.button.size`?
```suggestion
  size?: 'small' | 'medium' | 'large' | string;
```

File: src/js/components/Button/Button.js [hunk 6]
```diff
@@ -264,7 +300,12 @@ const Button = forwardRef(
       }
     };
 
-    let buttonIcon = icon;
+    const hoverIcon = getKindIcon(themePaths?.hover, theme, kind);
+    const kindIcon =
+      hover && hoverIcon
+        ? hoverIcon
+        : getKindIcon(themePaths?.base, theme, kind);
+    let buttonIcon = icon || kindIcon;
```
Comment (ericsoderberghp) [inline src/js/components/Button/Button.js:308]: The above getKindIcon() calls are a bit inefficient. What about something like?:
`let buttonIcon = icon || (hover && getKindIcon(themePaths?.hover, theme, kind)) || getKindIcon(themePaths?.base, theme, kind);`

File: src/js/components/Button/propTypes.js [hunk 7]
```diff
@@ -68,7 +68,7 @@ if (process.env.NODE_ENV !== 'production') {
     primary: PropTypes.bool,
     reverse: PropTypes.bool,
     secondary: PropTypes.bool,
-    size: PropTypes.oneOf(['small', 'medium', 'large']),
+    size: PropTypes.oneOf(['small', 'medium', 'large', 'xlarge']),
```
Comment (halocline) [inline src/js/components/Button/propTypes.js:71]: See `index.d.ts` comment.

```suggestion
    size: PropTypes.oneOfType([
      PropTypes.oneOf(['small', 'medium', 'large']),
      PropTypes.string,
    ]),
```

Comment (halocline) [inline src/js/components/Button/propTypes.js:71]: Also noticing, that `kind` is not in propTypes definition, nor is it documented. Is that still purposeful?

cc: @jcfilben

**Review by halocline — COMMENTED** [review]
Functionality and implementation are looking good. Small types / theme question.

File: src/js/components/Button/Button.js [hunk 8]
```diff
@@ -281,8 +322,17 @@ const Button = forwardRef(
             theme.global.colors.text[isDarkBackground() ? 'dark' : 'light'],
         });
       }
+    } else if (kind && kindIcon && !plain) {
```
Comment (ericsoderberghp) [inline src/js/components/Button/Button.js:325]: Could this just be `} else if (!plain && !icon.props.color) {`?

File: src/js/components/Button/StyledButtonKind.js [hunk 9]
```diff
@@ -37,7 +37,14 @@ const fontStyle = (props) => {
   `;
 };
 
-const padFromTheme = (size = 'medium', theme, themeObj) => {
+const padFromTheme = (size = 'medium', theme, themeObj, kind) => {
+  if (size && themeObj?.size?.[size]?.[kind]) {
```
Comment (ericsoderberghp) [inline src/js/components/Button/StyledButtonKind.js:41]: I think this might crash if we have `themeObj?.size?.[size]?.[kind]` but not `themeObj?.size?.[size]?.[kind].pad`

File: src/js/components/Button/StyledButtonKind.js [hunk 10]
```diff
@@ -37,7 +37,14 @@ const fontStyle = (props) => {
...
+    return {
```
Comment (ericsoderberghp) [inline src/js/components/Button/StyledButtonKind.js:42]: Can we just directly return `themeObj.size[size][kind].pad`?

File: src/js/components/Button/index.d.ts (hunk 5 above)
Comment (taysea) [reply src/js/components/Button/index.d.ts:67]: I like the string option

File: src/js/components/Button/Button.js (hunk 6 above)
Comment (taysea) [reply src/js/components/Button/Button.js:308]: Let me look into this, thanks for the suggestion!

File: src/js/components/Button/propTypes.js (hunk 7 above)
Comment (taysea) [reply src/js/components/Button/propTypes.js]: We do have it in typescript, so it feels like adding it here would be reasonable but maybe for sake of progressing this PR we can handle that in a small standalone PR (since it's an existing thing)/

File: src/js/components/Button/StyledButtonKind.js (hunk 10 above)
Comment (taysea) [reply src/js/components/Button/StyledButtonKind.js]: Correct, fixed.

File: src/js/components/Button/StyledButtonKind.js (hunk 9 above)
Comment (taysea) [reply src/js/components/Button/StyledButtonKind.js]: Correct, fixed.

File: src/js/components/Button/Button.js (hunk 8 above)
Comment (taysea) [reply src/js/components/Button/Button.js]: This logic doesn't quite work -- we still needed to have a way to check that a `kindIcon` exists before doing this (otherwise was running into snapshot changes on menu, other button components).

But i did simplify slightly.

File: src/js/components/Button/Button.js (hunk 6 above)
Comment (taysea) [reply src/js/components/Button/Button.js:306]: Simplified this in recent commit to a slightly modified but essentially equivalent logic., Left concept of `kindIcon` for reason detailed in below comment re: snapshot changes on other button-related components.

File: src/js/components/Button/propTypes.js (hunk 7 above)
Comment (halocline) [reply src/js/components/Button/propTypes.js]: Yes, I was not intending it for this PR, rather a point of awareness and stimulate discussion.

**Review by halocline — APPROVED** [review]
Thank you, @taysea.

**Review by ericsoderberghp — APPROVED** [review]

File: src/js/components/Button/propTypes.js (hunk 7 above)
Comment (jcfilben) [reply src/js/components/Button/propTypes.js]: > Also noticing, that kind is not in propTypes definition, nor is it documented. Is that still purposeful?

Sorry for slow response, I must of missed this comment when I was originally tagged. Anyway I'm looking into this... It also looks like the TS definition for kind is 'string' but looking at the code I think it could be a 'string' or 'object'. I'm not sure why we aren't documenting this, I can check with Shimi and maybe get more context.
