### PR TITLE
fix  #7579 Pagination aria label

### LINKED ISSUE #7579: Pagination Aria Labels
[Pagination component](https://design-system.hpe.design/components/pagination) is failing 1.3.1, 1.3.6 and 4.1.2  [WCAG Rules](https://www.w3.org/WAI/WCAG22/quickref/?versions=2.2&showtechniques=111%2C131%2C246%2C248%2C2410%2C1412#identify-purpose)

Current screen reader output for the “Items per page” dropdown is unclear.  There is no method to pass a label to the items per page Select step. The ARIA labeling lacks meaningful information and does not effectively convey the purpose of the component to assistive technologies.

It announces “Open drop,” which does not effectively convey the purpose of the control. Consider using a more descriptive and instructive label, such as “Items shown per page – 10 selected,” to better inform users of its function and current state.

### PR DESCRIPTION
**Pull request by Sulaymon333**
#### What does this PR do?

- fixes #7579 

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

### CODE REVIEW

File: src/js/components/Pagination/PaginationStep.js [hunk 1]
```diff
@@ -14,12 +14,14 @@ export const PaginationStep = ({
...
   const { format: formatMessage } = useContext(MessageContext);
   const { theme } = useThemeValue();
+
   return (
     <Box direction="row" align="center" gap="xsmall" {...rest}>
       <Text>{formatMessage({ id: 'pagination.stepLabel', messages })}</Text>
       <Select
         options={options}
         value={step}
+        a11yTitle="Items per Page"
```
Comment (britt6612) [inline src/js/components/Pagination/PaginationStep.js:24]: do we want a `aria-label` here instead then also we should include it in default.json message and allow for internationalization so using our 
```
format({
  id: 'pagination.itemsPerPage',
  messages,
  },
})
```

then add that message in the default.json file

Comment (britt6612) [reply src/js/components/Pagination/PaginationStep.js]: aw yes good catch

File: src/js/components/Pagination/PaginationStep.js [hunk 2]
```diff
@@ -14,12 +14,14 @@ export const PaginationStep = ({
...
   const { format: formatMessage } = useContext(MessageContext);
   const { theme } = useThemeValue();
+
   return (
     <Box direction="row" align="center" gap="xsmall" {...rest}>
       <Text>{formatMessage({ id: 'pagination.stepLabel', messages })}</Text>
       <Select
         options={options}
         value={step}
+        a11yTitle={formatMessage({ id: 'pagination.stepLabel', messages })}
```
Comment (britt6612) [inline src/js/components/Pagination/PaginationStep.js:24]: one last comment can we change this to be 
 aria-label={formatMessage({ id: 'pagination.stepLabel', messages })}

Comment (Sulaymon333) [reply src/js/components/Pagination/PaginationStep.js]: Done

**Review by britt6612 — APPROVED** [review]

**Review by taysea — APPROVED** [review]

**Review by jcfilben — APPROVED** [review]
Looks good!
