### PR TITLE
Fix TextInput placeHolder (fixes #987)

### LINKED ISSUE #987: placeHolder not working as expected
### Expected Behavior
according to the documentation I should be able to use 'placeHolder' in TextInput and Select, but I need to spell this 'placeholder' instead.

### Actual Behavior
warning.js:36 Warning: Unknown DOM property placeHolder. Did you mean placeholder?

### URL, screen shot, or Codepen exhibiting the issue
                    <TextInput
                       onDOMChange={this.handleInputSummary}
                       placeHolder='Type oneliner summary'
                       />

### Your Environment
* Grommet version: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Linux

### PR DESCRIPTION
**Pull request by davidcalhoun**
#### What does this PR do?
Fixes the `placeHolder` prop functionality on the `<TextInput>` component.

#### What testing has been done on this PR?
Tested in Chrome OSX only (since this isn't a browser bug).

#### How should this be manually tested?
Can be tested by opening `TextInputDoc.js` in `grommet-docs` and adding this to the `TextInput` in the `Examples` section:

```html
<TextInput
...
placeHolder="Some placeholder text!"
...
/>
```

#### Any background context you want to provide?
http://codepen.io/franksvalli/pen/bwOzqJ?editors=0010

#### What are the relevant issues?
#987 

#### Screenshots (if appropriate)
Before:
before

After:
after

#### Do the grommet docs need to be updated?
No

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/TextInput.js [hunk 1]
```diff
@@ -303,11 +303,12 @@ export default class TextInput extends Component {
 
   render () {
     const {
-      className, defaultValue, value, ...props
+      className, defaultValue, value, placeHolder, ...props
     } = this.props;
     delete props.suggestions;
     delete props.onDOMChange;
     delete props.onSelect;
+    delete props.placeHolder;
```
Comment (alansouzati) [inline src/js/components/TextInput.js]: I dont think we need to add the delete here. 

```
const {
  className, defaultValue, value, placeHolder, ...props
} = this.props;
```

This will take care of it.

**Comment by davidcalhoun** [comment]
Should be all ready now - please have another look!

Just a heads up - looks like a squash and merge is available from the UI dropdown here, which is convenient: https://github.com/blog/2141-squash-your-commits
