### PR TITLE
fix DateInput format calendar bounds

### LINKED ISSUE #6159: Possible Bug: Is possible to select the last month's day outside DateInput calendarProps bounds.
### Expected Behavior

Disable month day outside DateInput calendarProps bounds.

### Actual Behavior DateInput calendarProps bounds.

Is possible to select the last month's day outside DateInput calendarProps bounds.

### URL, screenshot, or Codepen exhibiting the issue

image

In this example current bounds are: `['2020-07-01', '2020-07-31']`

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: lastest
- Browser Name and version: -
- Operating System and version (desktop or mobile):

### LINKED ISSUE #6415: When the form validation is type of blur , then for the <DateInput />  , we can’t select two different dates
When the form validation is type of blur , then for the <DateInput format="mm/dd/yyyy-mm/dd/yyyy"/>  , we can’t select two different dates ! But it works fine for   validation is type of submit . Is this something expected ? 
### Expected Behavior

When the form validation is type of blur , then for the <DateInput format="mm/dd/yyyy-mm/dd/yyyy"/>  , we  should be able to select two different  dates !

### Actual Behavior

When the form validation is type of blur , then for the <DateInput format="mm/dd/yyyy-mm/dd/yyyy"/>  , we can’t select two different dates 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/dateinput-controlled-forked-t9qf06?file=/index.js

### Steps to Reproduce

1.Create a form with validation type as blur
2. Add a DateInput component with format as  'mm/dd/yyyy-mm/dd/yyyy'
3.  Try selecting two different dates of different months (25th September  2022 and 25th  December 2022)

### Your Environment

- Grommet version:  2.26.0
- Browser Name and version: chrome (106.0.5249.91 (Official Build) (arm64)
- Operating System and version (desktop or mobile): desktop

### PR DESCRIPTION
**Pull request by BrunoViveiros**
#### What does this PR do?

Fix the issue #6159 

#### Where should the reviewer start?

DateInput component

#### What testing has been done on this PR?

- [ ] Test

#### How should this be manually tested?

add  
```js
format="mm/dd/yyyy"
```
 and 
```js
calendarProps={{
  bounds: ['2022-10-10', '2022-10-20'],
}}
``` 

#### Do Jest tests follow these best practices?

- [x] `screen` is used for querying.
- [x] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [x] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?

~~I'll need #6424 to be merged first, because I'll need the `setHoursWithOffset` function to solve a issue with dates with wrong offset~~

#### What are the relevant issues?
closes #6159

### CODE REVIEW

**Comment by jcfilben** [comment]
It looks like this bug may have already been solved in https://github.com/grommet/grommet/pull/6214 I am no longer able to reproduce the issue

**Comment by BrunoViveiros** [comment]
With click the bounds work correctly, the problem occurs when you try to write the date in the input (It lets you select any date). I should have explained better

**Comment by jcfilben** [comment]
> With click the bounds work correctly, the problem occurs when you try to write the date in the input (It lets you select any date). I should have explained better

Ah okay I see thanks for explaining

File: src/js/components/DateInput/DateInput.js [hunk 1]
```diff
@@ -275,14 +278,20 @@ Use the icon prop instead.`,
                   reference,
                   outputFormat,
                 );
-                if (nextValue !== undefined)
-                  setReference(getReference(nextValue));
+
+                const validatedNextValue = validateDateBounds({
+                  dateBounds: bounds,
```
Comment (taysea) [inline src/js/components/DateInput/DateInput.js:283]:
```suggestion
                  dateBounds: calendarProps?.bounds,
```
Then we can remove the variable at line 169

File: src/js/components/DateInput/utils.js [hunk 2]
```diff
@@ -125,6 +125,30 @@ const pullDigits = (text, index) => {
   return text.slice(index, end);
 };
 
+export const validateDateBounds = ({ dateBounds, selectedDate }) => {
```
Comment (taysea) [inline src/js/components/DateInput/utils.js:128]:
```suggestion
export const validateBounds = ({ bounds, selectedDate }) => {
```
This is just a naming recommendation to keep the function naming more concise. Additionally, we try to align with prop names when possible (so simplify to "bounds").

File: src/js/components/DateInput/DateInput.js [hunk 3]
```diff
@@ -275,14 +278,20 @@ Use the icon prop instead.`,
                   reference,
                   outputFormat,
                 );
-                if (nextValue !== undefined)
-                  setReference(getReference(nextValue));
+
+                const validatedNextValue = validateDateBounds({
```
Comment (taysea) [inline src/js/components/DateInput/DateInput.js:282]:
```suggestion
                const validatedNextValue = validateDateBounds(
```
Can we just pass these as function parameters instead of an object?

File: src/js/components/DateInput/utils.js (hunk 2 above)
Comment (taysea) [inline src/js/components/DateInput/utils.js:128]:
```suggestion
export const validateDateBounds = (dateBounds, selectedDate) => {
```
This is related to my comment above about just passing as function parameters which is a little more aligned to other functions in this file.

File: src/js/components/DateInput/utils.js [hunk 4]
```diff
@@ -125,6 +125,30 @@ const pullDigits = (text, index) => {
...
+    ? selectedDate
+    : [selectedDate];
+
+  const isoSelectedDateArray = selectedDateArray.map((date) =>
+    new Date(date).toISOString(),
+  );
+
+  const allDatesOk = isoSelectedDateArray.every(
+    (isoSelectedDate) =>
+      (!endDate && startDate === isoSelectedDate) ||
```
Comment (taysea) [inline src/js/components/DateInput/utils.js:145]: What is this first condition checking for? `!endDate && startDate === isoSelectedDate` It seems like the second condition should be enough .

File: src/js/components/DateInput/utils.js [hunk 5]
```diff
@@ -125,6 +125,30 @@ const pullDigits = (text, index) => {
...
 };
 
+export const validateDateBounds = ({ dateBounds, selectedDate }) => {
+  if (!dateBounds || !selectedDate) return selectedDate;
+
+  const [startDate, endDate] = dateBounds.map((date) =>
+    new Date(date).toISOString(),
+  );
+
+  const selectedDateArray = Array.isArray(selectedDate)
```
Comment (taysea) [inline src/js/components/DateInput/utils.js:135]: This is a small recommendation to simplify having to declare so many variables as well as small naming suggestions:

```
  const isoSelectedDate = (
    Array.isArray(selectedDate) ? selectedDate : [selectedDate]
  ).map((date) => new Date(date).toISOString());
```

Comment (taysea) [reply src/js/components/DateInput/utils.js:135]: This would all you to remove isoSelectedDateArray and just consolidate here.

File: src/js/components/DateInput/utils.js [hunk 6]
```diff
@@ -125,6 +125,30 @@ const pullDigits = (text, index) => {
...
+    ? selectedDate
+    : [selectedDate];
+
+  const isoSelectedDateArray = selectedDateArray.map((date) =>
+    new Date(date).toISOString(),
+  );
+
+  const allDatesOk = isoSelectedDateArray.every(
```
Comment (taysea) [inline src/js/components/DateInput/utils.js:143]:
```suggestion
  const validDate = isoSelectedDateArray.every(
```
```suggestion
  const validSelection = isoSelectedDateArray.every(
```
Small naming suggestions

**Review by taysea — COMMENTED** [review]
Nice work on this! The behavior seems to be working as expected. My comments are more related to some Grommet naming conventions/code cleanups.

File: src/js/components/DateInput/utils.js (hunk 4 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/utils.js:145]: oh this is because the `calendarProps: { bounds: ` can be a array with just one item, and when this happens the only date that can be selected is the same date as in bounds. So if I don't check for this the value will always be false.

File: src/js/components/DateInput/DateInput.js (hunk 1 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/DateInput.js]: fixed 👍🏼

File: src/js/components/DateInput/utils.js (hunk 2 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/utils.js]: sure, fixed 👍🏼

File: src/js/components/DateInput/DateInput.js (hunk 3 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/DateInput.js]: done

File: src/js/components/DateInput/utils.js (hunk 2 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/utils.js]: done

File: src/js/components/DateInput/utils.js (hunk 5 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/utils.js]: changed

File: src/js/components/DateInput/utils.js (hunk 6 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/utils.js]: done

File: src/js/components/DateInput/utils.js (hunk 4 above)
Comment (taysea) [reply src/js/components/DateInput/utils.js:136]: Thank you for the clarification.

File: src/js/components/DateInput/utils.js [hunk 7]
```diff
@@ -118,6 +118,28 @@ const pullDigits = (text, index) => {
...
+
+  const [startDate, endDate] = dateBounds.map((date) =>
+    setHoursWithOffset(date).toISOString(),
+  );
+
+  const isoSelectedDates = (
+    Array.isArray(selectedDate) ? selectedDate : [selectedDate]
+  ).map((date) => date.toISOString());
+
+  console.log({ selectedDate, isoSelectedDates });
```
Comment (taysea) [inline src/js/components/DateInput/utils.js:132]: Looks like a console.log statement snuck through
```suggestion
```

**Review by taysea — COMMENTED** [review]
This is looking really great. The last thing that would be great to add is a unit test so we can make sure not to have regressions in the future.

This test can mirror the set up you used locally to test the behavior. We could want the test to:
- Type in an "invalid" date to the DateInput
- Check that the value is still undefined

Let me know if you need any help writing the test.

File: src/js/components/DateInput/utils.js (hunk 7 above)
Comment (BrunoViveiros) [reply src/js/components/DateInput/utils.js]: good catch, removed 😄

**Comment by BrunoViveiros** [comment]
@taysea  I have created the tests, could you check?

**Review by taysea — APPROVED** [review]
Test looks good to me, thank you!

**Review by ericsoderberghp — APPROVED** [review]
