### PR TITLE
Calendar - typescript + fix first day of the month on Sunday when firstDayOfWeek is Monday

### LINKED ISSUE #3253: Calendar doesn't show first day of month if firstDayOfWeek prop is set to Monday
### Expected Behavior

Calendar should ensure the first day of the month is always shown, regardless of `firstDayOfWeek` prop value.

### Actual Behavior

The first week of the month – _if the first day of the month falls on a Sunday_ – will not appear if the `firstDayOfWeek` prop is set to `1`, or "Monday" (it defaults to `0`, or "Sunday").

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-nqe6q

### Steps to Reproduce

Here's some code:

```
<Calendar
  firstDayOfWeek={1}
  date={(new Date(2019, 9, 0)).toISOString()}
/>
```

Notice that the calendar drops the first week of the month of September 2019.

### Your Environment

- Grommet version: 2.7.4
- Browser Name and version: Chrome 75.0.3770.142, Safari 12.1.1
- Operating System and version (desktop or mobile): macOS 10.14.5

### LINKED ISSUE #3284: ts: Calendar firstDayOfWeek wrong type
Calendar.firstDayOfWeek is declared as a number type (0 or 1) in the doc file for react-desc:
https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Calendar/doc.js#L47

while it is declared a string in the typescript interface:
https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Calendar/index.d.ts#L15

the correct implementation is a number:
https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Calendar/Calendar.js#L43

### PR DESCRIPTION
**Pull request by shabtaisharon**
#### What does this PR do?
1. Fix first day of the month on Sunday when firstDayOfWeek is Monday
1. Added a story to verify the fix
1. Fix typescript issue for firstDayOfWeek
#### Where should the reviewer start?
Calendar.js
#### What testing has been done on this PR?
Added story
#### How should this be manually tested?
Open '1st on Sunday' story on storybook Calendar
#### Any background context you want to provide?
No
#### What are the relevant issues?
closes #3253 
closes #3284 
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
Yes
#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/Calendar/Calendar.js [hunk 1]
```diff
@@ -40,7 +40,14 @@ const headingPadMap = {
 const buildStartEnd = (reference, firstDayOfWeek) => {
   let start = new Date(reference);
   start.setDate(1); // first of month
-  start = subtractDays(start, start.getDay() - firstDayOfWeek); // beginning of week
+
+  // in case Sunday is the first day of the months and the user asked for Monday to be the first day of the week, we need to include Sunday and six days prior.
```
Comment (ShimiSun) [inline src/js/components/Calendar/Calendar.js]:
```suggestion
  // in case Sunday is the first day of the month, and the user asked for Monday to be the first day of the week, we need to include Sunday and six days prior.
```

**Comment by ShimiSun** [comment]
would like another pair of eyes here @ericsoderberghp or @oorestisime

**Comment by oorestisime** [comment]
Everything looks good on my end as well. maybe we could use a ternary operation instead of the if else but that's just syntactic sugar. needs to be rebased to current master and merged :) 

Thanks for the contribution!

File: src/js/components/Calendar/Calendar.js [hunk 2]
```diff
@@ -40,7 +40,12 @@ const headingPadMap = {
 const buildStartEnd = (reference, firstDayOfWeek) => {
   let start = new Date(reference);
   start.setDate(1); // first of month
-  start = subtractDays(start, start.getDay() - firstDayOfWeek); // beginning of week
+
+  start =
+    start.getDay() === 0 && firstDayOfWeek === 1
+      ? (start = subtractDays(start, 6)) // in case Sunday is the first day of the month, and the user asked for Monday to be the first day of the week, we need to include Sunday and six days prior.
```
Comment (ericsoderberghp) [inline src/js/components/Calendar/Calendar.js]: I'm wondering why `prettier` didn't wrap this comment line. We try to keep everything within 80 characters wide, to keep it easy to read in a wide variety of contexts.

Comment (shabtaisharon) [reply src/js/components/Calendar/Calendar.js]: Anything I can do on my end to enforce it?

Comment (shabtaisharon) [reply src/js/components/Calendar/Calendar.js]: Reading about this, I've found out that `prettier` does not wrap comments only code.
A workaround I can offer you is to add a rule to .eslintrc to enforce max line length to 80 and you can mark it as error `"max-len": [2, 80, 4]` or warning `"max-len": [1, 80, 4]` depending on your architecture decision.

Comment (ShimiSun) [reply src/js/components/Calendar/Calendar.js]: True. I've tested it locally and it seems that only lines of code are being wrapped above 80 characters. and not comments. 
I fixed to comment positioning of this PR and it is good to go. 
@shabtaisharon feel free to file a PR with your suggested fix, adding this rule might be a good addition to grommet, thanks for your inputs!

**Comment by ShimiSun** [comment]
thank you for your contribution (h)/(b)uddy 🎉 ❤️
