### PR TITLE
made select column pay attention to table pin property

### LINKED ISSUE #5070: DataTable onSelect does not pin header checkbox
### Expected Behavior

If caller provides `pin` on DataTable while also using `onSelect` or `select`, the checkbox in the header of the table should remain fixed with the rest of the header cells.

### Actual Behavior

The checkbox scrolls away and does not stay pinned/

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/12522275/111372635-215e3c00-8658-11eb-8f75-c406f2cd35f3.mov

### Steps to Reproduce

1. Create DataTable
2. Apply `pin`
3. Apply `onSelect={() => {}}` (to display checkboxes)
4. Scroll

### Your Environment

- Grommet version: Stable
- Browser Name and version: Chrome Version 89.0.4389.82
- Operating System and version (desktop or mobile): Mac OS

### PR DESCRIPTION
**Pull request by MikeKingdom**
When a DataTable has a pinned header and selectable rows, the select checkbox column header cell (and footer cell) doesn't stay pinned on scroll like the other cells.

#### What does this PR do?

This PR changes the select checkbox column to stay pinned like other header/footer cells in a DataTable that has the `pin` property set. The background styling of the header and footer cell for the select checkbox now also comes from the theme `pinned` header and footer styling.

#### Where should the reviewer start?
DataTable/Header.js

#### What testing has been done on this PR?
Manual testing via storybook and Jest.

#### How should this be manually tested?
See the simple example from issue #5070 

#### What are the relevant issues?
Fixes #5070 

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/DataTable/Footer.js [hunk 1]
```diff
@@ -25,34 +49,43 @@ const Footer = forwardRef(
...
-              border={border}
-              context="footer"
-              column={column}
-              datum={footerValues}
-              pad={pad}
-              pin={pin.length ? pin : undefined}
-              primaryProperty={primaryProperty}
+  ) => {
+    const theme = useContext(ThemeContext) || defaultProps.theme;
+    const pin = tablePin ? ['bottom'] : [];
```
Comment (taysea) [inline src/js/components/DataTable/Footer.js:54]: Should it be `: undefined` if not tablePin?

File: src/js/components/DataTable/Header.js [hunk 2]
```diff
@@ -88,6 +88,28 @@ const StyledContentBox = styled(Box)`
   ${props => props.extend}
 `;
 
+const calcBackground = (backgroundProp, pin, theme) => {
```
Comment (taysea) [inline src/js/components/DataTable/Header.js:91]: Any chance we could extract this to a reusable function that also takes `tableContext` as a parameter? then you could say `theme.dataTable.pinned[tableContext]` and re-use across Footer also

File: src/js/components/DataTable/Footer.js (hunk 1 above)
Comment (MikeKingdom) [reply src/js/components/DataTable/Footer.js:54]: calcBackground checks pin.length so it's expecting an array. The body of calcBackground was extracted from the original logic as-is.

File: src/js/components/DataTable/Header.js (hunk 2 above)
Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js:91]: I thought about it although it seems a little odd and obfuscated. Seemed like I had to go look at the function to figure out what it actually did if I had that many args

Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js]: Done

File: src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap [hunk 3]
```diff
@@ -3197,7 +3197,7 @@ exports[`DataTable custom theme 1`] = `
         class="StyledTable__StyledTableRow-sc-1m3u5g-2 "
       >
         <td
-          class="c3"
+          class="c3 "
```
Comment (ShimiSun) [inline src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap:3200]: Can we try to understand the root cause of this extra space and clean it up?

File: src/js/components/DataTable/Header.js [hunk 4]
```diff
@@ -297,27 +298,16 @@ const Header = forwardRef(
                   </Box>
                 );
               }
-              const pin = [];
-              if (tablePin) pin.push('top');
-              if (columnPin) pin.push('left');
+              const cellPin = [...pin];
+              if (columnPin) cellPin.push('left');
```
Comment (ShimiSun) [inline src/js/components/DataTable/Header.js:302]: wouldn't `columnPin` always has a value of at least an empty array? Should this be refined to asking about the array's length?

Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js:302]: columnPin is a boolean property passed in at line 296 of DataTable.js

File: src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap (hunk 3 above)
Comment (MikeKingdom) [reply src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap:3200]: The select column changed to use `StyledDataTableCell` like the other header cells rather than just `TableCell`. If you look at line 3204 which is the first `column` you see it has the same space after the class name so I'm guessing its how `StyledDataTableCell` converts the pin values into CSS (and pre-existing.) I'll poke at it a little but it doesn't seem like it matters.

That does raise this question though:
Currently/pre-existing the select header cell isn't affected by theme.dataTable.header.extend like other header cells.
Should it be?

Comment (ericsoderberghp) [reply src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap:3200]: It should be pulling stuff from the theme.

Comment (MikeKingdom) [reply src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap:3200]: The extra space on 3200 above (and all other existing variations on TableCell) is because TableCell passes along a className prop to StyledTableCell which ends up causing this space when className is undefined. Doesn't seem worth messing with.

Comment (MikeKingdom) [reply src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap:3200]: The select header cell now pays attention to theme.dataTable.header.extend like other header cells

File: src/js/components/DataTable/Header.js [hunk 5]
```diff
@@ -139,10 +136,16 @@ const Header = forwardRef(
...
-            <TableCell
-              background={background || cellProps.background}
+            <StyledDataTableCell
+              background={
+                calcPinnedBackground(backgroundProp, pin, theme, 'header') ||
+                cellProps.background
+              }
               plain="noPad"
               size="auto"
+              context="header"
```
Comment (taysea) [inline src/js/components/DataTable/Header.js:146]: Good catch.

**Review by taysea — APPROVED** [review]
LGTM. Good catch with the `context="header"` on the Header CheckBox.

**Review by ericsoderberghp — APPROVED** [review]
