### PR TITLE
Fix Chart `opacity` prop to allow boolean value

### LINKED ISSUE #2776: Chart opacity issues with code and docs
Chart uses its own logic for color.opacity:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/Chart.js#L198

inconsistent with its doc:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/doc.js#L24

the new theme doc for Chart is using the wrong logic when documenting:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/doc.js#L197

Box and Meter are more consistent (although best to use backgroundStyle for all components, currently its a bit of a wild west)
Box:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Box/doc.js#L359

Meter:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Meter/doc.js#L85

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Updates the Chart `opacity` prop to be more consistent with the documentation. 

The documentation shows that `opacity` can be 'strong', 'medium', 'weak', or a boolean value. Currently boolean values are not accepted. This PR allows boolean values for the `opacity` prop and when setting opacity within the `value` prop. When `opacity={true}` it defaults to the "medium" opacity set by the theme, similar to how Box and Meter handle `opacity={true}`.

#### Where should the reviewer start?
Chart.js

#### What testing has been done on this PR?
Added a jest test and modified the storybook test ValueStyle

#### How should this be manually tested?
Storybook and review jest test

#### What are the relevant issues?
Closes #2776 

#### Screenshots (if appropriate)
Current grommet documentation showing boolean as valid for opacity:
Screen Shot 2021-05-05 at 6 29 12 PM

#### Do the grommet docs need to be updated?
Done

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/Chart/Chart.js [hunk 1]
```diff
@@ -269,7 +269,12 @@ const Chart = React.forwardRef(
               }
               opacity={
                 (valueOpacity && theme.global.opacity[valueOpacity]) ||
-                valueOpacity
+                // eslint-disable-next-line no-nested-ternary
+                (valueOpacity === true
+                  ? theme.global.opacity.medium
+                  : valueOpacity === false
+                  ? undefined
+                  : valueOpacity)
```
Comment (ShimiSun) [inline src/js/components/Chart/Chart.js:277]: Since this code is being duplicated, I'm thinking we should extract it to a function.

File: src/js/components/Chart/doc.js [hunk 2]
```diff
@@ -186,7 +186,11 @@ export const doc = Chart => {
           label: PropTypes.string, // for accessibility of bars and points
           onClick: PropTypes.func,
           onHover: PropTypes.func,
-          opacity: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
+          opacity: PropTypes.oneOfType([
+            PropTypes.string,
+            PropTypes.number,
+            PropTypes.bool,
```
Comment (ShimiSun) [inline src/js/components/Chart/doc.js:192]: Does the TS file needs attention?

Comment (jcfilben) [reply src/js/components/Chart/doc.js:192]: Nope, the typescript definition already includes boolean as an option for both opacity and values.opacity `opacity?: 'weak' | 'medium' | 'strong' | boolean | number;`

File: src/js/components/Chart/Chart.js (hunk 1 above)
Comment (jcfilben) [reply src/js/components/Chart/Chart.js]: Fixed in latest push

**Review by ericsoderberghp — APPROVED** [review]
