### PR TITLE
Fix(MaskedInput): add a default mask

### LINKED ISSUE #4222: <MaskedInput /> doesn't work (onChange event doesn't have a event.currentTarget.value)
### Expected Behavior

If I pass a value and a onChange event handler (event) to a MaskedInput, and start typing I should get a currentTarget.value or a target.value out of the event that is returned.

### Actual Behavior

If I pass a value and a onChange event handler (event) to a MaskedInput, I never get a currentTarget.value or a target.value out of the event that is returned.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/masked-input-error-w3niq?file=/src/App.js

### Steps to Reproduce

Make a component like so:
```javascript
import React from "react";
import "./styles.css";
import { MaskedInput, Paragraph, TextInput } from "grommet";

export default function App() {
  const [brokenText, setBrokenText] = React.useState("hello");
  const [workingText, setWorkingText] = React.useState("hello");

  return (
    <div className="App">
      <Paragraph>Please try entering text in the input below:</Paragraph>
      <MaskedInput
        value={brokenText}
        onChange={event => {
          setBrokenText(event.currentTarget?.value);
        }}
      />
      <Paragraph>This is a text input, so it works:</Paragraph>
      <TextInput
        value={workingText}
        onChange={event => {
          setWorkingText(event.currentTarget?.value);
        }}
      />
    </div>
  );
}
```

### Your Environment

- Grommet version: 2.14.1
- Browser Name and version: Chrome (latest)
- Operating System and version (desktop or mobile): desktop MacOS

### PR DESCRIPTION
**Pull request by netochaves**
#### What does this PR do?
Closes #4222 

#### Where should the reviewer start?
`src/js/components/MaskedInput/MaskedInput.js `
#### What testing has been done on this PR?
Unit tests
#### How should this be manually tested?
Create a story of MaskedInput with no mask

#### What are the relevant issues?
#4222 
#### Do the grommet docs need to be updated?
No.
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/MaskedInput/MaskedInput.js [hunk 1]
```diff
@@ -113,7 +113,12 @@ const parseValue = (mask, value) => {
   return valueParts;
 };
 
-const defaultMask = [];
+const defaultMask = [
+  {
+    regexp: /[^]*/,
```
Comment (ShimiSun) [inline src/js/components/MaskedInput/MaskedInput.js:118]: I'm wondering if instead of setting default value we should enforce the prop to be a required field.

**Comment by ShimiSun** [comment]
Thank you for your contribution!
