### PR TITLE
Data - controlled story invalid prop error

### LINKED ISSUE #6572: Data - controlled story invalid prop error
### Expected Behavior
Stories shouldn't have console errors

### Actual Behavior
The Data/Controlled story has an error:
'Invalid prop `view.properties` of type `array` supplied to `Data`, expected `object`.'

### URL, screen shot, or Codepen exhibiting the issue

Screen Shot 2023-01-10 at 2 22 00 PM

### Steps to Reproduce

Run storybook locally and look at the console output for the Data/controlled story

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by umeshiscreative**
#### What does this PR do?
Fix the bug when checking the data-controlled story in locally 

#### Where should the reviewer start?
components/Data/proptypes.js

#### How should this be manually tested?
I used the storybook to test this component.

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
Added proptype as array type, object and any type.

#### What are the relevant issues?
Closes #6572 

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
backwards compatible.

### CODE REVIEW

File: src/js/components/Data/propTypes.js [hunk 1]
```diff
@@ -1,7 +1,11 @@
 import PropTypes from 'prop-types';
 
 const viewType = PropTypes.shape({
-  properties: PropTypes.shape({}),
+  properties: PropTypes.oneOfType([
+    PropTypes.arrayOf(PropTypes.any),
+    PropTypes.shape({}),
+    PropTypes.any,
```
Comment (ericsoderberghp) [inline src/js/components/Data/propTypes.js:7]: Why is this variation needed? From the typescript typings, it appears that it's either an array of strings or an object.

File: src/js/components/Data/propTypes.js [hunk 2]
```diff
@@ -1,7 +1,11 @@
 import PropTypes from 'prop-types';
 
 const viewType = PropTypes.shape({
-  properties: PropTypes.shape({}),
+  properties: PropTypes.oneOfType([
+    PropTypes.arrayOf(PropTypes.any),
```
Comment (ericsoderberghp) [inline src/js/components/Data/propTypes.js:5]: Why isn't this an array of strings?

**Review by ericsoderberghp — COMMENTED** [review]
Thanks for working on this.

File: src/js/components/Data/propTypes.js (hunk 1 above)
Comment (umeshiscreative) [reply src/js/components/Data/propTypes.js]: @ericsoderberghp, I check the type-definition and added the same.

File: src/js/components/Data/propTypes.js (hunk 2 above)
Comment (umeshiscreative) [reply src/js/components/Data/propTypes.js]: @ericsoderberghp, Now its fixed.

**Review by ericsoderberghp — APPROVED** [review]
Thanks for your contribution!
