### PR TITLE
Fix List layout when it has action and onOrder defined

### LINKED ISSUE #6341: List "action" property doesn't work with "onOrder"
### Expected Behavior

The action should be aligned with the rest of the list, even if you have an `onOrder` property.

### Actual Behavior

`action` and `onOrder` don't work together.

### URL, screen shot, or Codepen exhibiting the issue

CodeSandbox Displaying the Issue: https://codesandbox.io/s/grommet-v2-template-forked-7l1mgp?file=/index.js

With `onOrder`:
image

Without `onOrder`:
image

### Steps to Reproduce

1. Create a `List` component 
2. Add an `action` property
3. Add an `onOrder` property
4. The list will be unaligned

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version:  Google Chrome
- Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by MikeKingdom**
When you have a List with both `action` and `onOrder` specified the action and primary/secondary labels end up in a container that is column layout rather than the typical row layout you have with `action` when `onOrder` isn't used.

#### What does this PR do?
This change uses the same layout for the non onOrder-related elements as it would have used without `onOrder`. In the case of `action`, this puts the action next to the onOrder controls more like you'd expect.

#### Where should the reviewer start?
List.js

#### What testing has been done on this PR?
Manual, storybook and Jest

#### How should this be manually tested?
Manualy add an action to an onOrder example.

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Fixes #6341 

#### Screenshots (if appropriate)
Before:
image

After:
image

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards Compatible

### CODE REVIEW

File: src/js/components/List/__tests__/List-test.js [hunk 1]
```diff
@@ -552,6 +553,39 @@ describe('List onOrder', () => {
...
+          />
+        </Grommet>
+      );
+    };
+  });
+
+  test('Render', () => {
+    const { container } = render(<App />);
+
+    expect(container.firstChild).toMatchSnapshot();
```
Comment (halocline) [inline src/js/components/List/__tests__/List-test.js:585]:
```suggestion
    const { asFragment } = render(<App />);

    expect(asFragment()).toMatchSnapshot();
```

**Review by halocline — COMMENTED** [review]
small test adjustment, otherwise looks good to go. Thanks for jumping on this.

**Review by jcfilben — APPROVED** [review]
Other than the testing comment, everything else looks good!
