### PR TITLE
Box - fix responsive false

### LINKED ISSUE #3252: parameter `responsive` in roundStyle of StyledBox is never used
https://github.com/grommet/grommet/blob/28366f60cda7ace2ff2d3a5d385f9eee8411f73c/src/js/components/Box/StyledBox.js#L239

### PR DESCRIPTION
**Pull request by ShimiSun**
#### What does this PR do?
Fixes border and radius styles for Box when responsive is false
#### Where should the reviewer start?
StyledBox.js
#### What testing has been done on this PR?
I've refactored the stories to support #3212, so it may not be straight forward to find the stories added.
Navigate to Box -> Border story and resize the window to see that border isn't changing when setting responsive to false.
Navigate to Box -> Round story and resize the window to see that the rounded `dark-4` boxes aren't changing when setting responsive to false.

#### Any background context you want to provide?
I've updated jest dependency due to some failures I've experienced.
The snapshots have only semantic changes and no styling changes.
#### What are the relevant issues?
closes #3252 
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backward compatible or is it a breaking change?
backward compatible

### CODE REVIEW

File: src/js/components/Box/stories/Border.js [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        color
+      </Box>
+      <Box direction="row-responsive" gap="small" align="start">
+        {['small', 'medium', 'large'].map(size => (
+          <Box key={size} pad="small" border={{ size }}>
+            {size}
+          </Box>
+        ))}
+      </Box>
+      <Box direction="row-responsive" gap="small" align="start">
```
Comment (ShimiSun) [inline src/js/components/Box/stories/Border.js]: Added this Box to visually see the border impact when responsive is false.

File: src/js/components/Box/stories/Round.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        true
+      </Box>
+      <Grid columns="small" gap="small">
+        {['xsmall', 'small', 'medium', 'large', 'xlarge', 'full'].map(size => (
+          <Box key={size} pad="large" background="brand" round={{ size }}>
+            {size}
+          </Box>
+        ))}
+      </Grid>
+      <Grid columns="small" gap="small">
```
Comment (ShimiSun) [inline src/js/components/Box/stories/Round.js]: Added this Grid to visually see the radius impact when responsive is false. easy to notice and compare with the dark-4 color.
