### PR TITLE
Changed SkipLinks 

### LINKED ISSUE #4360: SkipLink example broken in docs site
### Expected Behavior
When using the examples given on the grommet docs site, I'd expect the skiplink to be working.

### Actual Behavior
The skiplinks don't work in the examples on the grommet site

### URL, screen shot, or Codepen exhibiting the issue
https://v2.grommet.io/skiplinks

### Steps to Reproduce
Try any of the skip link examples on the grommet site.

### Your Environment

- Grommet version: any since v2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac OSX

### PR DESCRIPTION
**Pull request by ShimiSun**
#### What does this PR do?
1. Allows the SkipLinks layer to open by entering Tab on the keyboard once the page loaded.
1. Allows skipping the SkipLinks layer content and tabbing to the header.
1. Allows editing the SkipLinks message and styling the container, layer, and the text message.
1. Allows cyclic navigation of the page that includes the layer using the keyboard.
1. Enabling access to the rest of the interactive elements while the layer is shown.
1. Changing the DOM behavior to prepend the Layer to the DOM so tabIndex order will behave correctly by default.
1. Provides clear examples of how to use the component on Storybook.
1. Tested with typescript.
1. Change initial focus behavior to the first focused link instead of the container.

#### Where should the reviewer start?
SkipLinks.js
#### What testing has been done on this PR?
Manual testing - many.
Typescript local testing - all passed.
#### How should this be manually tested?
Go to the storybook examples of SkipLinks, enter Tab on the keyboard, and follow directions.
#### Any background context you want to provide?
I would like to add one more enhancement on a separate PR, that the first focusable element will be the first SkipLink element and not the container as its behaving now (and always behaved that way). I can file it on a separate PR if agreed.
Edit: this functionality is already done on this PR.
#### What are the relevant issues?
closes #4360 
#### Do the grommet docs need to be updated?
Done
#### Should this PR be mentioned in the release notes?
Yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible as this PR is a bug fix.

### CODE REVIEW

File: src/js/components/SkipLinks/SkipLinks.js [hunk 1]
```diff
@@ -35,29 +37,38 @@ const SkipLinks = ({ children, id, messages }) => {
...
-            cloneElement(element, {
-              key: `skip-link-${index}`,
-              onClick: removeLayer,
-            }),
+      {showLayer && (
+        <Box {...theme.skipLinks.container}>
+          {messages.skipTo && (
+            <Text {...theme.skipLinks.text}>{messages.skipTo}</Text>
           )}
+          <Box align="center">
```
Comment (ericsoderberghp) [inline src/js/components/SkipLinks/SkipLinks.js:55]: What if the theme wants a different alignment?

I'm getting nervous that we're putting more and more theming layout and styling in the JSON theme when they would be better handled via JSX markup. Just thinking out loud.

File: src/js/components/SkipLinks/SkipLinks.js [hunk 2]
```diff
@@ -35,29 +37,38 @@ const SkipLinks = ({ children, id, messages }) => {
...
+            {children.map((element, index) =>
+              cloneElement(element, {
+                key: `skip-link-${index}`,
+                onClick: removeLayer,
```
Comment (ericsoderberghp) [inline src/js/components/SkipLinks/SkipLinks.js:59]: What if the child already has an `onClick` handler?

File: src/js/utils/DOM.js [hunk 3]
```diff
@@ -85,10 +85,15 @@ export const getBodyChildElements = () => {
   return children;
 };
 
-export const getNewContainer = (rootNode = document.body) => {
+export const getNewContainer = (rootNode = document.body, bodyTarget) => {
```
Comment (ericsoderberghp) [inline src/js/utils/DOM.js:88]: I think `rootTarget` would be more aligned with `rootNode`. Although, I think `rootChildPosition` would be even more accurate.

File: src/js/components/SkipLinks/SkipLinks.js [hunk 4]
```diff
@@ -35,29 +37,38 @@ const SkipLinks = ({ children, id, messages }) => {
   return (
     <Layer
       id={id}
-      position={showLayer ? 'top' : 'hidden'}
+      position={showLayer ? theme.skipLinks.position : 'hidden'}
       ref={layerRef}
       onFocus={onFocus}
       onBlur={onBlur}
+      tabIndex={0}
```
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:44]: I agree. 
Until now, that is how it used to behave since the implementation used to have a `modal`.
I've put a comment on the PR description:
> I would like to add one more enhancement on a separate PR, that the first focusable element will be the first SkipLink element and not the container as its behaving now (and always behaved that way). I can file it on a separate PR if agreed.

Let me know what you think.

File: src/js/components/Layer/Layer.js [hunk 5]
```diff
@@ -8,14 +8,15 @@ import { animationDuration } from './StyledLayer';
 import { ContainerTargetContext } from '../../contexts/ContainerTargetContext';
 
 const Layer = forwardRef((props, ref) => {
-  const { animate, animation } = props;
+  const { animate, animation, bodyTarget } = props;
```
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/Layer/Layer.js:11]: I'm pretty sure we closed on `bodyTarget`, feel free to make any other suggestions, it's an internal prop so will be flexible for editing.

File: src/js/components/SkipLinks/SkipLinks.js [hunk 6]
```diff
@@ -35,29 +37,38 @@ const SkipLinks = ({ children, id, messages }) => {
...
+      modal={false}
+      bodyTarget="first" // prepend the Layer on the body container
+      // modal={false} will take the full screen a small breakpoint
```
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:47]: I added this comment because I thought it is valuable to understand why I've assigned `responsive={false}`, do you disagree?

File: src/js/components/SkipLinks/SkipLinks.js [hunk 7]
```diff
@@ -35,29 +37,38 @@ const SkipLinks = ({ children, id, messages }) => {
...
+      responsive={false}
```
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:48]: See my previous comment :)

File: src/js/components/SkipLinks/SkipLinks.js [hunk 8]
```diff
@@ -35,29 +37,38 @@ const SkipLinks = ({ children, id, messages }) => {
...
-        <Box direction="row" align="center" pad={{ bottom: 'medium' }}>
-          {children.map((element, index) =>
-            cloneElement(element, {
-              key: `skip-link-${index}`,
-              onClick: removeLayer,
-            }),
+      {showLayer && (
+        <Box {...theme.skipLinks.container}>
+          {messages.skipTo && (
+            <Text {...theme.skipLinks.text}>{messages.skipTo}</Text>
```
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:53]: Hmmm... it is the text in the Layer, but just the message text.
Would `theme.skipLinks.message.text` be clearer?

File: src/js/components/SkipLinks/SkipLinks.js (hunk 2 above)
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:59]: Not sure, I didn't delve to this part of the functionality, it was always there. I can take a look though.

File: src/js/utils/DOM.js (hunk 3 above)
Comment (ShimiSun) [reply src/js/utils/DOM.js:88]: I like `rootChildPosition`. I'll use that.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ericsoderberghp) [reply src/js/components/SkipLinks/SkipLinks.js:44]: Hmm... is that how skip links work on other sites? I think it's more important to be compatible with the general use of skip links than with prior grommet behavior in this case.

File: src/js/components/Layer/Layer.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (ericsoderberghp) [reply src/js/components/Layer/Layer.js:11]: `targetChildPosition`?

File: src/js/components/SkipLinks/SkipLinks.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (ericsoderberghp) [reply src/js/components/SkipLinks/SkipLinks.js:47]: Ah, it looked more like you had commented out `model={false}` to me. How about something like:

"Non-modal Layer's will take the full screen at small breakpoints by default, which isn't what we want."

File: src/js/components/SkipLinks/SkipLinks.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (ericsoderberghp) [reply src/js/components/SkipLinks/SkipLinks.js:53]: What about `theme.skipLink.label`?

File: src/js/components/SkipLinks/SkipLinks.js (hunk 1 above)
Comment (ericsoderberghp) [reply src/js/components/SkipLinks/SkipLinks.js:55]: We can wait until a need arises.

File: src/js/utils/DOM.js (hunk 3 above)
Comment (ShimiSun) [reply src/js/utils/DOM.js:88]: I actually liked your proposal above to use `targetChildPosition` and used that.

File: src/js/components/SkipLinks/SkipLinks.js [hunk 9]
```diff
@@ -20,12 +23,11 @@ const SkipLinks = ({ children, id, messages }) => {
   const onBlur = () => {
     // timeout needed so it gives enough time for activeElement to be updated
     setTimeout(() => {
-      const layerNode = layerRef.current;
+      // close the layer in case the activeElement isn't an anchor
```
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js]: I agree. Fixed on the recent commit.

File: src/js/components/Layer/Layer.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/Layer/Layer.js]: Yes. done.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js]: Done.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js]: Done.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:55]: Done on the recent commit, and I've updated the PR description.

File: src/js/components/SkipLink/SkipLink.js [hunk 10]
```diff
@@ -1,10 +1,10 @@
-import React from 'react';
+import React, { forwardRef } from 'react';
 
 import { Anchor } from '../Anchor';
 import { Box } from '../Box';
 
-export const SkipLink = ({ id, label, ...rest }) => (
+export const SkipLink = forwardRef(({ id, label, ...rest }, ref) => (
   <Box margin="small">
```
Comment (ericsoderberghp) [inline src/js/components/SkipLink/SkipLink.js:7]: I'm wondering if `SkipLinks` should control all of the layout and use `gap` and `margin` and leave `SkipLink` to be just the `Anchor`?

File: src/js/components/SkipLinks/README.md [hunk 11]
```diff
@@ -23,12 +23,103 @@ node
...
+
+Any valid Text prop for the text message. Expects `object`.
+
+Defaults to
+
+```
+{ margin: 'small', size: 'medium' }
+```
+
+**skipLinks.text.margin**
```
Comment (ericsoderberghp) [inline src/js/components/SkipLinks/README.md:97]: `skipLinks.label.margin`?

Or, maybe I'm misunderstanding something. How does `skipLinks.label.margin` relate to `skipLinks.text.margin`?

File: src/js/components/SkipLinks/SkipLinks.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ericsoderberghp) [reply src/js/components/SkipLinks/SkipLinks.js:55]: I'm still not sure why the Layer needs `tabIndex={0}`. I was thinking that the first `SkipLink` would be what receives the focus already.

File: src/js/components/SkipLinks/SkipLinks.js [hunk 12]
```diff
@@ -35,29 +48,40 @@ const SkipLinks = ({ children, id, messages }) => {
...
     >
-      <Box pad={{ horizontal: 'medium' }}>
-        <Heading level={2}>{messages.skipTo}:</Heading>
-        <Box direction="row" align="center" pad={{ bottom: 'medium' }}>
-          {children.map((element, index) =>
-            cloneElement(element, {
-              key: `skip-link-${index}`,
-              onClick: removeLayer,
-            }),
+      {showLayer && (
```
Comment (ericsoderberghp) [inline src/js/components/SkipLinks/SkipLinks.js:62]: I would have thought we'd always render each `SkipLink` and let the user's tab take care of giving it focus and causing the Layer to remove 'hidden'.

File: src/js/utils/DOM.js [hunk 13]
```diff
@@ -85,10 +85,18 @@ export const getBodyChildElements = () => {
   return children;
 };
 
-export const getNewContainer = (rootNode = document.body) => {
+export const getNewContainer = (
+  rootNode = document.body,
```
Comment (ericsoderberghp) [inline src/js/utils/DOM.js:89]: since we're calling the new argument `targetChildPosition`, I think we should rename `rootNode` to `target` here.

File: src/js/components/SkipLink/SkipLink.js (hunk 10 above)
Comment (ShimiSun) [reply src/js/components/SkipLink/SkipLink.js:7]: You read my mind. 
I actually have code in place that does just that, but then I thought maybe we should keep the Box and SkipLink will have a theme to style this Box container and the user will be able to control margin, padding, or any other Box property for an individual SkipLink. 
Two of the approaches sounded like they could work for me, so I said I should leave it as is and see which need arises :)
If you have a strong preference I'm good either way.

File: src/js/components/SkipLinks/README.md (hunk 11 above)
Comment (ShimiSun) [reply src/js/components/SkipLinks/README.md:97]: Oopsy, good catch.

File: src/js/utils/DOM.js (hunk 13 above)
Comment (ShimiSun) [reply src/js/utils/DOM.js]: Done.

File: src/js/components/SkipLinks/README.md (hunk 11 above)
Comment (ShimiSun) [reply src/js/components/SkipLinks/README.md]: Fixed.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 12 above)
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:62]: I suspect there might be an issue with how Layer is interpolating `position="hidden"` with `modal={false}` that drove this condition.
Even when the Layer is set to the hidden position, it's still being displayed, though removing modal={false} makes the Layer hidden as expected. 
I'll delve into Layer to find the root cause of this issue -- unless you think there should be a good reason for not letting hidden work on `modal={false}`.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:55]: There are comments in SkipLinks `onFocus` that explains how the focus is being addressed, and how this tabIndex is playing an important part in it.
That being said, as part of investigating how to let `position='hidden'` do its thing and addressing the Layer issue that doesn't hide the Layer on `modal={false}`, I might be able to simplify this tabIndex behavior and remove it altogether. 
I'll keep this comment open and circle back to it once I'll have some resolutions.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 12 above)
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js]: Update: 
I pushed a fix for Layer that addresses the issue of hiding the Layer when `position="hidden" && modal={false}` that fixes the issue for SkipLinks, and thanks to this fix I was able to remove this condition and the `tabIndex=0` from the SkipLinks logic.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js]: Update: 
I pushed a fix for Layer that addresses the issue of hiding the Layer when `position="hidden" && modal={false}` and that fixes the issue for SkipLinks. Thanks to this fix I was able to remove `tabIndex=0` so this concern should be out of our way now.

File: src/js/components/SkipLink/SkipLink.js (hunk 10 above)
Comment (ericsoderberghp) [reply src/js/components/SkipLink/SkipLink.js:7]: Since it's a "Link", I think it should just be an "Anchor". I don't think we need to do too much styling for it, since it's designed more for users with sight issues.

File: src/js/components/SkipLinks/SkipLinks.js [hunk 14]
```diff
@@ -35,14 +34,21 @@ const SkipLinks = ({ children, id, messages }) => {
   return (
     <Layer
       id={id}
-      position={showLayer ? 'top' : 'hidden'}
+      position={showLayer ? theme.skipLinks.position : 'hidden'}
       ref={layerRef}
       onFocus={onFocus}
       onBlur={onBlur}
+      modal={false}
+      targetChildPosition="first" // prepend the Layer on the body container
```
Comment (ericsoderberghp) [inline src/js/components/SkipLinks/SkipLinks.js:42]: Can we add just a bit more to this comment to indicate why we are doing this? For example:

"Prepend the Layer so any SkipLink will be the first element that pressing the Tab key reaches"

File: src/js/components/SkipLink/SkipLink.js (hunk 10 above)
Comment (ericsoderberghp) [reply src/js/components/SkipLink/SkipLink.js:7]: I think SkipLink should just be Anchor. Since this is for users with sight issues, I don't think we need to invest a lot for styling it.

Comment (ShimiSun) [reply src/js/components/SkipLink/SkipLink.js:7]: Ok, I'll clean it up.

File: src/js/components/SkipLinks/SkipLinks.js (hunk 14 above)
Comment (ShimiSun) [reply src/js/components/SkipLinks/SkipLinks.js:42]: Absolutely. good comment.

File: src/js/components/SkipLink/SkipLink.js (hunk 10 above)
Comment (ShimiSun) [reply src/js/components/SkipLink/SkipLink.js]: Done.
