### PR TITLE
Pre-commit fails on warning

### LINKED ISSUE #4218: Add no warnings for tests on pre-commit

### PR DESCRIPTION
**Pull request by JoeButler7**
#### What does this PR do?
Makes jest tests fail on `console.warn`, which in turn makes the pre-commit fail on warnings. Does this by adding a `setupTests.js` file and including this file as a config file for jest in `package.json`. Relevant documentation  https://create-react-app.dev/docs/running-tests/#initializing-test-environment
#### Where should the reviewer start?
`src/setupTests.js` and `package.json` line 140
#### What testing has been done on this PR?
I added an example `console.warn` in one of the tests and then ran `yarn test` as well as `git commit` to ensure that the test will fail which will cause the pre-commit checks to fail
#### How should this be manually tested?
See above
#### What are the relevant issues?
Closes #4218 
#### Screenshots (if appropriate)
Commit failing because of warning
Screen Shot 2020-07-01 at 3 26 57 PM

#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No
#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/setupTests.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+global.console.warn = message => {
+  throw message;
+};
+
+global.console.error = message => {
+  throw message;
+};
```
Comment (ShimiSun) [inline src/setupTests.js:7]: Pre-commit already used to fail on error, why is this needed?

Comment (JoeButler7) [reply src/setupTests.js]: I just included it because of the documentation I was looking at but you're right it is redundant. It has been removed on the most recent push

Comment (JoeButler7) [reply src/setupTests.js]: I just included it because of the documentation I was looking at but you're right it is redundant. It has been removed on the most recent push

Comment (ShimiSun) [reply src/setupTests.js]: Thanks. without this definition, how does the pre-commit knew until now to block the commits with errors?

Comment (JoeButler7) [reply src/setupTests.js]: Its because jest automatically fails tests if they throw errors and the pre-commit blocks the commit if any tests fail

**Comment by JoeButler7** [comment]
### Update:
Added back the code that will cause tests to fail on `console.error`. This was not previously implemented which can be shown by the following screen shot showing a test passing on pre-commit despite an error. 
Screen Shot 2020-07-07 at 3 03 07 PM
Jest will automatically fail on an unhandled exception but not `console.error` or `console.warn`. Adding this code in will turn `console.error` and `console.warn` into thrown exceptions which will thus make the test fail and cause the precommit to fail. Below is a screenshot of the same error from the previous screenshot but it fails due to the new code added
Screen Shot 2020-07-07 at 3 22 37 PM

File: src/setupTests.js (hunk 1 above)
Comment (ShimiSun) [reply src/setupTests.js:6]: Post discussion on this matter:
Currently, pre-commit fails because jest is throwing an exception with exit code 1 in case a test fail. 
This PR is enhancing this behavior so the pre-commit will fail not just for exceptions but for `console.error` and `console.warnings` messages.

**Comment by ShimiSun** [comment]
Is the new config file also published on the production files?

**Comment by JoeButler7** [comment]
> Is the new config file also published on the production files?

No it is not

**Comment by ShimiSun** [comment]
Thank you for addressing this issue!
