### PR TITLE
fix: modify implementation of parseMetricToNum mixin

### LINKED ISSUE #3124: Using shorthand properties for input padding produces wrong and huge padding
### Expected Behavior

```js
const myTheme = {
  global: {
    input: {
      padding: "20px 10px"
    }
  }
};
```

Using this configuration, I would expect my input to have a vertical padding of `20px` and a horizontal one of `10px`

### Actual Behavior

Instead, the padding generated is `2009px`

Screen Shot 2019-05-28 at 1 29 05 PM

Sandbox: https://codesandbox.io/s/grommetsandbox-s9u7z

### PR DESCRIPTION
**Pull request by crashuniverse**
The previous implementation of `parseMetricToNum` was it modifies "12px 20px" to 1220.
For "12px 20px", `fontAsString.replace(/[^0-9/.]/g, ''` removes all strings leaving "1220" and works what it was specified for.

The problem occurs when this function is used in `StyledTextInput` at [code that decides left padding](https://github.com/crashuniverse/grommet/blob/master/src/js/components/TextInput/StyledTextInput.js#L65). The user, while overriding theme variables for padding tries "12px 20px" imagining that css shorthand syntax is supported, [while documentation suggests only 1 value is supported](https://v2.grommet.io/textinput#global.input.padding). The side-effect is left padding becomes 1220px.

Fixes #3124

#### What does this PR do?
It modifies how `parseMetricToNum` works. The new regex `/\d+(\.\d+)?/` to extract value from string is:
```
/                         // start
 \d                       // a digit
   +                      // and its 0 or more occurrences
    (                     // start of an optional group to support 12.567px
      \.                  // decimal
       \d+                // more digits
          )?              // end of optional group
            /             // end
```
So now it just extracts the first match (no global regex) and "12px 20px" is still 12. The user's expectation can be managed by a console warning suggested by @oorestisime. It retains all the initial features of function.

#### Where should the reviewer start?
With a critical mindset to increase safety as this fn is used at several places and helping me understand how does `-20px` is used with these functions as I could not understand it. I wrote tests to support all occurrences of usage I saw in code.

#### What testing has been done on this PR?
Besides adding unit tests, while running storybook, I see the problem for `TextInput` by adding this code in `src/js/components/TextInput/stories/textinput.stories.js` line 88
```
const customTheme = deepMerge(grommet, {
  global: {
    input: {
      padding: '12px 20px', // breaks layout and left padding becomes 1220px
    }
  },
  textInput: {
```
When I change to my branch, the problem disappears and console has a warning.

#### How should this be manually tested?
Same as the previous point.

#### Any background context you want to provide?
#3124

#### What are the relevant issues?
#3124

#### Screenshots (if appropriate)
Screen Shot 2019-06-08 at 19 27 39

#### Do the grommet docs need to be updated?
No. However while running tests, a small change is introduced possibly because of updates in libraries yesterday in `master`.

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
Yes, it is backwards compatible.

### CODE REVIEW

File: src/js/utils/__tests__/mixins-test.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+describe('Mixins parseMetricToNum', () => {
+  global.console = {
+    warn: jest.fn(),
+  };
+
+  test('coverts "12px" to 12', () => {
+    const number = parseMetricToNum('12px');
+
+    expect(number).toBe(12);
```
Comment (oorestisime) [inline src/js/utils/__tests__/mixins-test.js]: can we test that it doesn't warn here?

File: src/js/utils/__tests__/mixins-test.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  test('coverts "12px 20px" to 12', () => {
+    const number = parseMetricToNum('12px 20px');
+
+    expect(number).toBe(12);
+  });
+
+  test('warns when caller expects "12px 20px" in a theme override', () => {
+    const warn = jest.spyOn(global.console, 'warn');
+    parseMetricToNum('12px 20px');
+
```
Comment (oorestisime) [inline src/js/utils/__tests__/mixins-test.js]: we can merge this test and the previous one no?

File: src/js/utils/__tests__/mixins-test.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+afterAll(() => {
+  jest.clearAllMocks();
+});
+
+describe('Mixins parseMetricToNum', () => {
+  global.console = {
+    warn: jest.fn(),
+  };
+
+  test('coverts "12px" to 12', () => {
```
Comment (oorestisime) [inline src/js/utils/__tests__/mixins-test.js]: typo converts :) same with the other tests :)

File: src/js/components/__tests__/__snapshots__/README-test.js.snap [hunk 4]
```diff
@@ -4136,10 +4136,10 @@ string
 **children**
 
 Function that will be called when each value is rendered. Defaults to \`function children(value) {
-    return _react[\\"default\\"].createElement(_Box.Box, {
+    return _react.default.createElement(_Box.Box, {
```
Comment (oorestisime) [inline src/js/components/__tests__/__snapshots__/README-test.js.snap]: hm, why do we have these changes?

Comment (crashuniverse) [reply src/js/components/__tests__/__snapshots__/README-test.js.snap]: This was an error, I just removed these now from changes. I wonder how I got there.

File: src/js/utils/__tests__/mixins-test.js (hunk 2 above)
Comment (crashuniverse) [reply src/js/utils/__tests__/mixins-test.js]: Yes - modified. I have the same input and 2 expect statements now. Also improved with `expect(warn).toHaveBeenCalledWith('This feature takes only 1 value and should have no spaces');` to check if the message part is alright.

File: src/js/utils/__tests__/mixins-test.js (hunk 3 above)
Comment (crashuniverse) [reply src/js/utils/__tests__/mixins-test.js]: Fixed.

File: src/js/utils/__tests__/mixins-test.js (hunk 1 above)
Comment (crashuniverse) [reply src/js/utils/__tests__/mixins-test.js]: Great point, done.

File: src/js/utils/mixins.js [hunk 5]
```diff
@@ -1,7 +1,11 @@
 import { css } from 'styled-components';
 
-export const parseMetricToNum = fontAsString =>
-  parseFloat(fontAsString.replace(/[^0-9/.]/g, ''), 10);
+export const parseMetricToNum = fontAsString => {
+  if (fontAsString.match(/\s/)) {
+    console.warn('This feature takes only 1 value and should have no spaces');
```
Comment (oorestisime) [inline src/js/utils/mixins.js]: another thing i thought today, the message is not clear. The user won't be able to know what happened. maybe we can give some more context (This feature = ?) and even mention the value we tried to parse.

On a side note i also think we should warn only in development mode so we don't pollute user console in production. What do you think?

Comment (crashuniverse) [reply src/js/utils/mixins.js]: I like the idea of keeping warning to `development`only for now. About the message I made it more abstract in language & including argument:
https://github.com/crashuniverse/grommet/blob/fix/mixins-parseMetricToNum/src/js/utils/mixins.js#L4:L7

File: src/js/utils/mixins.js [hunk 6]
```diff
@@ -1,7 +1,13 @@
 import { css } from 'styled-components';
 
-export const parseMetricToNum = fontAsString =>
-  parseFloat(fontAsString.replace(/[^0-9/.]/g, ''), 10);
+export const parseMetricToNum = fontAsString => {
+  if (fontAsString.match(/\s/) && process.env.NODE_ENV !== 'production') {
+    console.warn(
+      `This utility of parsing text received "${fontAsString}" as an argument but takes only 1 argument and should have no spaces`,
```
Comment (ericsoderberghp) [inline src/js/utils/mixins.js]: Perhaps: `Invalid single measurement value: "${fontAsString}"`?

Comment (crashuniverse) [reply src/js/utils/mixins.js]: Lot better, I updated it. Many thanks.

**Comment by oorestisime** [comment]
Merged! thanks a lot for the contribution and your updates!

**Comment by crashuniverse** [comment]
Thank you @oorestisime & @ericsoderberghp for your suggestions and review 🙂
