### PR TITLE
Fix button padding to be based on the size

### LINKED ISSUE #4754: Ideate approaches to Button sizing
Explore possible approaches to ensure Button's size, state, and kind styling all work together.

### Expected Behavior

A button implemented as:
```
<Button secondary size="large" label="Large" icon={<FormNext />} reverse />
```
And a theme defined as:
```
button: {
    default: {
      ...
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
    secondary: {
      border: {
        color: 'green',
        width: '2px',
      },
      color: 'text-strong',
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '10px',
        vertical: '4px',
      },
    },
    size: {
      ...
      large: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '8px',
          horizontal: '16px',
        },
      },
    },
  },
```
should apply the button kind's styling as well as be able to be sized.

### Actual Behavior

Related: https://github.com/grommet/grommet-theme-hpe/issues/139#issuecomment-724901504

Instead, the button's kind styling ("secondary" in this case) trumps any size styling when in conflict and does not render desired results:
**Large secondary button, not large**
Screen Shot 2020-11-16 at 1 11 21 PM

**Resulting CSS shows padding being set multiple times on same component:**
Screen Shot 2020-11-16 at 1 11 32 PM

**Solution should also account for:**
- Buttons at different states (e.g. hover state such as`button.hover.secondary` can also have styling specified)
Screen Shot 2020-11-16 at 1 22 36 PM
- Gap between label and icon
- Icon scaling

### Steps to Reproduce

**Theme definition:**
```
button: {
    default: {
      color: 'text-strong',
      border: undefined,
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
    primary: {
      background: {
        color: 'green',
      },
      border: undefined,
      color: 'text-strong',
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
    secondary: {
      border: {
        color: 'green',
        width: '2px',
      },
      color: 'text-strong',
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '10px',
        vertical: '4px',
      },
    },
    option: {
      color: 'text',
      border: {
        radius: '0px',
      },
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
      font: {
        weight: 400,
      },
    },
    active: {
      background: {
        color: 'background-contrast',
      },
      color: 'text',
      secondary: {
        border: {
          color: 'transparent',
        },
      },
      option: {
        background: {
          color: 'active-background',
        },
      },
    },
    selected: {
      option: {
        background: 'selected-background',
        color: 'selected-text',
      },
    },
    disabled: {
      background: {
        color: 'transparent',
      },
      color: 'text-weak',
      primary: {
        border: {
          color: 'border-weak',
          width: '2px',
        },
        padding: {
          horizontal: '10px',
          vertical: '4px',
        },
      },
      secondary: {
        border: {
          color: 'border-weak',
        },
      },
      opacity: 1.0,
    },
    hover: {
      default: {
        background: {
          color: 'background-contrast',
        },
        color: undefined,
      },
      secondary: {
        border: {
          width: '3px',
        },
        padding: {
          horizontal: '9px',
          vertical: '3px',
        },
      },
      option: {
        background: 'active-background',
        color: 'active-text',
      },
    },
    size: {
      small: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '4px',
          horizontal: '8px',
        },
      },
      medium: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '6px',
          horizontal: '12px',
        },
      },
      large: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '8px',
          horizontal: '16px',
        },
      },
    },
    border: {
      radius: '4px',
    },
    color: 'text-strong',
    padding: {
      vertical: '4px',
      horizontal: '10px',
    },
  },
```
**JSX:**
<Button secondary label="Default" icon={<FormNext />} reverse />
<Button secondary size="small" label="Small" icon={<FormNext />} reverse />
<Button secondary size="medium" label="Medium" icon={<FormNext />} reverse />
<Button secondary size="large" label="Large" icon={<FormNext />} reverse />
```

### Your Environment

<!--- Include as many relevant details about the environment you experienced the bug in -->

- Grommet version: 2.15.2 / Stable
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by MikeKingdom**
Fix button padding coming from the size in the theme to adjust for border width defined in the kind section of theme

Currently any button padding defined in the button.kind specific part of the theme overrides the padding defined for the button size.

#### What does this PR do?
Changes the button padding based on the button size to be adjusted to account for a kind-specific border. If the button.kind part of the theme specifies a padding, it won't be adjusted (for backward compatibility.)
 
#### Where should the reviewer start?
StyledButtonKind.js

#### What testing has been done on this PR?
1. Compare storybook examples of button
2. Tested with modified HPE theme (removed kind-specific padding)
3. Tested with current HPE theme (no differences without removing kind-specific padding.)
4. Jest tests - Note one Jest test snapshot modified to account for how a kind with a border causes the padding from the button.size part of the theme gets adjusted to account for the border.

#### How should this be manually tested?
Storybook

#### What are the relevant issues?
Fixes #4754 

#### Screenshots (if appropriate)
image

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Yes, just in case someone encounters some unexpected behavior in this area, and to advertise the new capabilities in order to take advantage of them.

#### Is this change backwards compatible or is it a breaking change?
Backward Compatible

### CODE REVIEW

File: src/js/components/Button/StyledButtonKind.js [hunk 1]
```diff
@@ -68,36 +79,69 @@ const basicStyle = props => css`
   }
 `;
 
+// could replace this with a call in lodash
```
Comment (ericsoderberghp) [inline src/js/components/Button/StyledButtonKind.js:82]: We've tried to reduce the number of dependencies and just keep simple enough things like this inline.

File: src/js/components/Button/StyledButtonKind.js [hunk 2]
```diff
@@ -68,36 +79,69 @@ const basicStyle = props => css`
...
+  let obj;
+  if (path) {
+    obj = theme;
+    const parts = path.split('.');
+    while (obj && parts.length) obj = obj[parts.shift()];
+  }
+  return obj;
+};
+
+const dimensionToNumber = d => parseInt(d.replace('px', ''), 10);
```
Comment (ericsoderberghp) [inline src/js/components/Button/StyledButtonKind.js:93]: Can we use the existing `parseMetricToNum`?

**Review by ericsoderberghp — COMMENTED** [review]
Nice, just a few comments.

File: src/js/components/Button/StyledButtonKind.js (hunk 2 above)
Comment (MikeKingdom) [reply src/js/components/Button/StyledButtonKind.js:93]: Looks like I probably can. I didn't think it would strip off the units.

File: src/js/components/Button/StyledButtonKind.js (hunk 1 above)
Comment (MikeKingdom) [reply src/js/components/Button/StyledButtonKind.js]: Removed the comment and kept the function.

File: src/js/components/Button/StyledButtonKind.js (hunk 2 above)
Comment (MikeKingdom) [reply src/js/components/Button/StyledButtonKind.js]: replaced with parseMetricToNum

File: src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap [hunk 3]
```diff
@@ -20,6 +20,7 @@ exports[`Button kind border on default button 1`] = `
   border-style: solid;
   border-width: 2px;
   border-color: green;
+  padding: 2px 20px;
```
Comment (ShimiSun) [inline src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap:23]: This change might be problematic for users of the HPE theme in terms of backward compatibility. The button padding for the kind Button will immediately increase if the users upgrade to a grommet version that includes this PR unless we release the theme with a complimentary fix at the same time.

Comment (MikeKingdom) [reply src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap:23]: If I remember correctly it doesn't because line 17 which comes from the 'kind' part of the theme is overriding it (really the aspect of the original problem.)

**Review by ericsoderberghp — APPROVED** [review]

**Review by ShimiSun — APPROVED** [review]
