### PR TITLE
Box props added to RadioButtonGroup theme

### LINKED ISSUE #4184: Would like ability for RadioButtonGroup styling to be set in theme
### Expected Behavior

I'd like to be able to specify styling for RadioButtonGroup in a theme, specifically the options `gap`.

### Actual Behavior

Theme not currently referenced.
RadioButtonGroup styling can not be set in theme (e.g. desired gap size)
  - Same applies to CheckBoxGroup

Use case. HPE Design System designs desire a gap of none between RadioButtonGroup and CheckBoxGroup options. Implementers can achieve this by setting the `gap` property for each instance, however for the Design System, this specification would make sense to live in the theme.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by IanKBovard**
#### What does this PR do?
closes #4184 
Adds boxprops to RadioButtonGroup in theme

#### Where should the reviewer start?
RadioButtonGroup.js
base.js
base.d.ts
RadioButtonGroup Stories - CustomTheme.js
RadioButtonGroup doc.js

#### What testing has been done on this PR?
Storybook, tested with and without custom theme.
Used none, xxsmall, small, medium, large, xlarge, and px values to test gap within custom theme.
Also, tested other box props, like animation, to see if they applied.

#### How should this be manually tested?
same as above

#### Any background context you want to provide?
RadioButtonGroup did not have the ability to set box props within theme.

#### What are the relevant issues?
#4341 

#### Do the grommet docs need to be updated?
Yes, they are in this pr

#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/RadioButtonGroup/stories/CustomTheme.js [hunk 1]
```diff
@@ -6,6 +6,12 @@ import { grommet } from 'grommet/themes';
 import { deepMerge } from 'grommet/utils';
 
 const customTheme = deepMerge(grommet, {
+  radioButtonGroup: {
+    container: {
+      gap: 'xlarge',
+      animation: 'fadeIn',
```
Comment (ShimiSun) [inline src/js/components/RadioButtonGroup/stories/CustomTheme.js:12]: Due to this animation chromatic isn't picking up the changes.
Can you disable chromatic for this file? https://www.chromatic.com/snapshot?appId=5d9774839a6eff00203f5cbf&id=5f2c55d4f321ca0022245fa1

Comment (IanKBovard) [reply src/js/components/RadioButtonGroup/stories/CustomTheme.js:12]: gotcha
