### PR TITLE
fixes #7287 - Bug when set JSX elements in Select options prop

### LINKED ISSUE #7287: Bug when set JSX elements in Select options prop
### Context
I recently update to the last grommet version from (<= v2.25.2). When I set JSX elems in options props in Select component, then it doesn't show any option.

Looks like this stopped working v2.25.2 which does seem like a bug.

Example of code:
```javascript
    // color is a hexa value
    <Select
      options={colors.map((color) => (<StatusGoodSmall size="small" color={color} />))}
      value={<StatusGoodSmall size="large" color={initialColor} />}
      onChange={({ option }) => setColor(option.props.color)}
    />
```

### Is this something you or your team is interested in contributing a pull request towards?

No by now.

### Expected Behavior

Should show options rendering jsx elements (eg: Icon from grommet-icons) 

[Codesandbox with expected behavior using previous versions](https://codesandbox.io/p/sandbox/selectmultiple-8h7hcp?file=%2Fsrc%2FApp.js%3A14%2C34-14%2C39)

### Actual Behavior

Do not show any option but handle onChange function successfully.

### URL, screen shot, or Codepen exhibiting the issue

[Codesandbox with issue](https://codesandbox.io/p/sandbox/selectmultiple-forked-jrdwf2)

### Steps to Reproduce

1. Code this component with some JSX element
2. Open Select input
3. No option is shown

### Your Environment

- Grommet version:` 2.39.0`
- Browser Name and version: `Chrome - Version 127.0.6533.89 (Official Build) (64-bit)`
- Operating System and version (desktop or mobile): `Windows 10 desktop`

### PR DESCRIPTION
**Pull request by avantika-codes**
#### What does this PR do?
This PR fixes a bug in the Select component where JSX elements passed in the options prop were not being handled correctly. It adds a check to ensure that valid React elements are returned as-is in the applyKey function.

#### Where should the reviewer start?
The reviewer should review the changes in src/js/components/Select/utils.js, particularly the applyKey function.

#### What testing has been done on this PR?
Unit tests were run to ensure that JSX elements, along with other types of options (like strings and objects), are properly handled. 

#### How should this be manually tested?
To manually test:

Pass different types of options (strings, objects, and JSX elements) to the Select component.
Verify that all types are rendered correctly in the dropdown and can be selected.

#### Do Jest tests follow these best practices?
N/A

#### Any background context you want to provide?
Previously, the Select component didn't account for JSX elements in the options prop, causing issues when JSX was used. This PR adds a check to handle JSX properly.

#### What are the relevant issues?
closes #7287.

#### Screenshots (if appropriate)
Screenshot from 2024-10-03 10-25-06

#### Do the grommet docs need to be updated?
No updates to the Grommet documentation are required.

#### Should this PR be mentioned in the release notes?
Yes, this PR should be mentioned to highlight the fix for JSX handling in Select options.

#### Is this change backwards compatible or is it a breaking change?
This change is backwards compatible. It adds support for JSX elements without affecting other option types.

### CODE REVIEW

**Review by britt6612 — COMMENTED** [review]
The changes look good to me is there anyway we can add a jest test for this?

**Comment by avantika-codes** [comment]
> The changes look good to me is there anyway we can add a jest test for this?

Yes working on it, trying to wrap ASAP.

**Comment by avantika-codes** [comment]
Hi @britt6612, I have added the test file for the changes made by me. Do let me know if they are placed correctly. Also attaching screenshot of the test below.
Screenshot 2024-10-06 at 10 28 34 AM

**Comment by britt6612** [comment]
> Hi @britt6612, I have added the test file for the changes made by me. Do let me know if they are placed correctly. Also attaching screenshot of the test below. Screenshot 2024-10-06 at 10 28 34 AM

can you move to be under Select so we don't make a new folder?

**Comment by avantika-codes** [comment]
> > Hi @britt6612, I have added the test file for the changes made by me. Do let me know if they are placed correctly. Also attaching screenshot of the test below. Screenshot 2024-10-06 at 10 28 34 AM
> 
> can you move to be under Select so we don't make a new folder?

Yes let me do the needful.

**Review by britt6612 — APPROVED** [review]

File: src/js/components/Select/__tests__/Select-test.js [hunk 1]
```diff
@@ -1714,3 +1713,38 @@ describe('Select', () => {
   window.scrollTo.mockRestore();
   window.HTMLElement.prototype.scrollIntoView.mockRestore();
 });
+
+describe('applyKey function', () => {
```
Comment (jcfilben) [inline src/js/components/Select/__tests__/Select-test.js:1717]: Thanks for taking the time to write tests. One note here, usually we try to test behavior of the component rather than implementation details. This allows more flexibility over time as we may change how the applyKey function works but we know we always want the Select to support options that are JSX elements. Could we change the tests so that we are testing the Select component with JSX elements as options rather than testing the applyKey function?

**Review by jcfilben — COMMENTED** [review]
Functionality looks good, just one comment about the tests

File: src/js/components/Select/__tests__/Select-test.js (hunk 1 above)
Comment (avantika-codes) [reply src/js/components/Select/__tests__/Select-test.js]: Thanks for the feedback! I've updated the tests to focus on the behavior of the Select component with JSX options, rather than testing the applyKey function directly. Let me know if any further changes are required?

**Comment by jcfilben** [comment]
I added the hacktoberfest-accepted label, we are holding off merging this PR until after our next release.
