### PR TITLE
Fix Tip behavior after getting focus back from another element

### LINKED ISSUE #5569: Tip displays after getting focus back from another element
### Expected Behavior

Tip shouldn't appear again and persist after a button with tip receives focus programmatically after a Layer closes, etc.

### Actual Behavior

Tip is persisting until user clicks somewhere else in screen.

### URL, screen shot, or Codepen exhibiting the issue

https://design-system.hpe.design/templates/filtering

### Steps to Reproduce

1. Click filtering button
2. Click "Close" button on filtering layer
3. Notice how "Open filters" tip appears again and stays open even as you move your mouse around the screen.
4. 

### Your Environment

- Grommet version: stable
- Browser Name and version: Chrome Mac
- Operating System and version (desktop or mobile): MacOS BigSur

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Fixes an issue where the Tip would display after getting focus back (ex. when Tip is on a Button and the Button opens a Layer the Tip would display when the Layer closes).

Now the Tip only displays after getting focus back from another element when navigating with the keyboard. This maintains accessibility while removing the behavior for mouse users.

#### What testing has been done on this PR?
Tested with the following story:
```javascript
import React from 'react';
import { Add } from 'grommet-icons';
import { Box, Button, Grommet, Layer, Text, Tip } from 'grommet';
import { grommet } from 'grommet/themes';

export const Test = () => {
  const [open, setOpen] = React.useState();
  const onOpen = () => setOpen(true);
  const onClose = () => setOpen(undefined);

  return (
    <Grommet theme={grommet} full>
      <Box fill align="center" justify="center" gap="medium">
        <Tip
          plain
          dropProps={{ align: { left: 'right' } }}
          content={
            <Box
              align="center"
              background="accent-1"
              margin="xsmall"
              pad="xsmall"
              round="medium"
              flex={false}
            >
              <Text color="brand">Tooltip</Text>
            </Box>
          }
        >
          <Button
            icon={<Add color="brand" />}
            label={
              <Text>
                <strong>Add Corner Layer</strong>
              </Text>
            }
            onClick={onOpen}
            plain
            focusIndicator
          />
        </Tip>
        <Tip
          plain
          dropProps={{ align: { left: 'right' } }}
          content="tip"
        >
          <Button
            icon={<Add color="brand" />}
            label={
              <Text>
                <strong>Add Corner Layer</strong>
              </Text>
            }
            onClick={onOpen}
            plain
            focusIndicator
          />
        </Tip>
      </Box>
      {open && (
        <Layer position="top-right" onClickOutside={onClose}>
            <Box pad="large" margin="small">This is a Layer</Box>
            <Button label="Close" onClick={onClose} />
        </Layer>
      )}
    </Grommet>
  );
};

export default {
  title: 'Layout/Layer/Test',
};
```

#### How should this be manually tested?
With storybook stories using Tip and Layer

#### What are the relevant issues?
Closes #5569 

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Maybe

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap [hunk 1]
```diff
@@ -204,30 +204,6 @@ exports[`Tip focus and blur events on the Tip's child 1`] = `
   -webkit-font-smoothing: antialiased;
 }
 
-@media only screen and (max-width:768px) {
```
Comment (taysea) [inline src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap:207]: Any thoughts on why these lines were removed?

**Review by taysea — COMMENTED** [review]
Behavior looks great, tested locally with the storybook example you provided. Just one small comment via snapshot changes.

File: src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap (hunk 1 above)
Comment (jcfilben) [reply src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap:207]: I'm not sure why they were removed in this PR, but seems like they shouldn't have been there in the first place. Related issue in styled components where empty media queries are added to snapshots: https://github.com/styled-components/jest-styled-components/issues/276

**Review by ericsoderberghp — APPROVED** [review]

**Review by taysea — APPROVED** [review]
