### PR TITLE
use `forwardref` and change `buttonref`

### LINKED ISSUE #6539: DropButton loses drop target location when badge changes while the menu is open
### Expected Behavior
When the badge state gets modified with the dropdown menu activated, the expectation is that the component stays anchored to the drop target

### Actual Behavior
When the menu is open and the badge state changes, the drop down menu gets moved to the start of the document.

### URL, screen shot, or Codepen exhibiting the issue
Here is an example.  Open the drop down menu and click on one of the items.  The item will change the badge state and the dropdown menu will be moved away from the original location.
(https://codesandbox.io/s/awesome-allen-ygcdnq?file=/src/App.js)](https://codesandbox.io/s/awesome-allen-ygcdnq?file=/src/App.js)

### Steps to Reproduce
Add a DropButton to the page with kind = 'toolbar' to match other toolbar icons
Change badge state while the dropdown is selected

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Chromium 108.0.5359.71
- Operating System and version (desktop or mobile): Mac (desktop)

### PR DESCRIPTION
**Pull request by britt6612**
#### Where should the reviewer start?
DropContainer.js
DropButton.js
#### What testing has been done on this PR?
storybook
#### How should this be manually tested?
```

      <Box margin={{ left: 'large', top: '200px' }} direction="row">
        <DropButton
          badge={badge}
          dropAlign={{ left: 'left', top: 'bottom' }}
          label='hello'
          icon={<Columns />}
          dropContent={
            <Box pad="medium">
              <Button
                label="Toggle badge"
                onClick={() => setBadge((prev) => !prev)}
              />
            </Box>
          }
        />
      </Box>

```
#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?

Re-rendering the Button when adding a badge or tip causes the DropButton's `buttonRef.current` to change. DropButton passes the initial `buttonRef.current` to DropContainer but doesn't pass the new one when the Button re-renders for the badge.

more comments [here](https://github.com/grommet/grommet/issues/6539)

#### What are the relevant issues?
closes #6539 
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/Drop/DropContainer.js [hunk 1]
```diff
@@ -101,7 +96,7 @@ const DropContainer = forwardRef(
 
     useEffect(() => {
       const notifyAlign = () => {
-        const styleCurrent = (ref || dropRef).current.style;
+        const styleCurrent = dropRef?.current.style;
```
Comment (ericsoderberghp) [inline src/js/components/Drop/DropContainer.js:99]:
```suggestion
        const styleCurrent = dropRef.current.style;
```

Comment (ericsoderberghp) [reply src/js/components/Drop/DropContainer.js:99]: We're going to dereference `styleCurrent` anyway on the next line, so returning undefined won't help.

File: src/js/components/Drop/DropContainer.js [hunk 2]
```diff
@@ -113,8 +108,8 @@ const DropContainer = forwardRef(
       const place = (preserveHeight) => {
         const windowWidth = window.innerWidth;
         const windowHeight = window.innerHeight;
-        const target = dropTarget;
-        const container = (ref || dropRef).current;
+        const target = dropTarget?.current || dropTarget;
+        const container = dropRef?.current;
```
Comment (ericsoderberghp) [inline src/js/components/Drop/DropContainer.js:112]:
```suggestion
        const container = dropRef.current;
```

File: src/js/components/Drop/DropContainer.js [hunk 3]
```diff
@@ -316,18 +311,19 @@ const DropContainer = forwardRef(
       restrictFocus,
       stretch,
       theme.drop,
+      dropRef,
     ]);
 
     useEffect(() => {
       if (restrictFocus) {
-        (ref || dropRef).current.focus();
+        dropRef?.current.focus();
```
Comment (ericsoderberghp) [inline src/js/components/Drop/DropContainer.js:319]:
```suggestion
        dropRef.current.focus();
```

File: src/js/components/Drop/DropContainer.js [hunk 4]
```diff
@@ -316,18 +311,19 @@ const DropContainer = forwardRef(
...
       }
-    }, [ref, restrictFocus]);
+    }, [dropRef, ref, restrictFocus]);
```
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/Drop/DropContainer.js]: good catch also took it out in other `useEffect`

**Review by ericsoderberghp — APPROVED** [review]
