### PR TITLE
Fix infinite eq false behavior

### LINKED ISSUE #1327: Carousel infinite set to false not working
Carousel infinite set to false not working. 

Same issue with #1220.

Any fix for this?

### Your Environment

* Grommet version: 1.3.4
* Operating System and version (desktop or mobile): Android 6.0.1

### PR DESCRIPTION
**Pull request by dgennetten**
#### What does this PR do?
Fix #1327 and #1220 carousel infinite=false behavior so that it doesn't wrap
#### Where should the reviewer start?
https://grommet.github.io/docs/carousel/examples
#### What testing has been done on this PR?
mac/pc edge/chrome
#### How should this be manually tested?
https://grommet.github.io/docs/carousel/examples
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No
#### Is this change backwards compatible or is it a breaking change?
Non-breaking

### CODE REVIEW

File: src/js/components/Carousel.js [hunk 1]
```diff
@@ -224,7 +224,13 @@ export default class Carousel extends Component {
     const { children } = this.props;
     const { activeIndex } = this.state;
     const numSlides = children.length;
-    const index = (activeIndex + numSlides - 1) % numSlides;
```
Comment (alansouzati) [inline src/js/components/Carousel.js]: i believe we can simplify this to

```
const index = !this.props.infinite && activeIndex === 0 ? activeIndex : (activeIndex + numSlides - 1) % numSlides
```

File: src/js/components/Carousel.js [hunk 2]
```diff
@@ -241,7 +247,13 @@ export default class Carousel extends Component {
     const { children } = this.props;
     const { activeIndex } = this.state;
     const numSlides = children.length;
-    const index = (activeIndex + 1) % numSlides;
+    let index = (activeIndex + 1) % numSlides;
```
Comment (alansouzati) [inline src/js/components/Carousel.js]: I believe we can simplify this to:

```
const index = !this.props.infinite && activeIndex === children.length - 1 ? activeIndex : (activeIndex + 1) % numSlides;
```

File: src/js/components/Carousel.js (hunk 1 above)
Comment (dgennetten) [inline src/js/components/Carousel.js]: Thx @alansouzati.   My continuing problem, however, is the coverage fail. Can you suggest fix?

**Comment by alansouzati** [comment]
We are not being strict about the code coverage at this point. so don't worry. thanks for your contribution.
