### PR TITLE
[RadioButton] Isolate the `check` background color

### LINKED ISSUE #5225: RadioButtons: check.background.color is being applied to all the radio buttons and not just the checked radio button
### Actual Behavior: For the code here: 
`radioButton: {    
    check: {
      color: '#fff',
      background:{
        color: '#3b5ed8'
      }
    }
  }`

all the radio buttons show the blue background color and not just the one checked. 

Screen Shot 2021-05-05 at 3 33 16 PM

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Desktop Mac

### PR DESCRIPTION
**Pull request by ramos-ph**
#### What does this PR do?

This PR adds a new style definition to the RadioButton component.
It isolates the `check` style property, making the Button change the background color only when the radio button is checked instead of being the same color.  

#### Where should the reviewer start?

By the RadioButton component and StyledRadioButton changes.

#### What testing has been done on this PR?

Created a new test where it's verified what is the background color of the checked radio button when the `check` style prop is present.

#### How should this be manually tested?

By creating a `radioButton` theme with the `background` and `check` properties:

```js
{
  radioButton: {
    background: { // default style
      color: 'red'
    }
    check: { // only when checked
      background: {
        color: 'red'
      }
    }
  }
}
```

#### Any background context you want to provide?

The `check` property implies on a style that only applies when the radio button is checked. That was what I thought and it was the reason for separating this specific `background` property.

#### What are the relevant issues?

Closes #5225 

#### Screenshots (if appropriate)

Unchecked radio button with `background.color` prop (default `light-1`).
Screenshot from 2021-05-11 11-53-18

Checked radio button with `check.background.color` prop.
Screenshot from 2021-05-11 11-53-23

#### Do the grommet docs need to be updated?

Yes.

#### Should this PR be mentioned in the release notes?

Yes.

#### Is this change backwards compatible or is it a breaking change?

It's not a complete breaking change. However, some radio buttons that used the `check` background theme will revert to `light-1` by default when they are not checked.

### CODE REVIEW

**Comment by ramos-ph** [comment]
@charupasternak25 There is no secret.
I just browsed the general theme file to define the background color outside the `check` object, causing it to split into active and inactive backgrounds.
Then I went to the StyledRadioButton.js file and set the `background-color` to come from the props of the component.
Finally, I went to the RadioButton.js file and created a new `backgroundColor` object that references to the radio button background outside the `check` property if the radio isn't checked, and references to the background inside the `check` object when the radio is checked.

Personally, is not that complicated to implement this. Although it seems to be a lot, most of the changes are snapshot related for testing purposes.
I don't think you need to update your grommet version. I utilize the latest on the master branch, but I'm not quite familiar with Grommet.

**Comment by ramos-ph** [comment]
@charupasternak25 There is no secret.
Basically, you can implement this with the config I just referenced on the PR body. Looks like the following:
```js
{
  radioButton: {
    background: { // applies when radio isn't checked
      color: 'grey'
    }
    check: { // applies only when radio is checked
      background: {
        color: 'red'
      }
    }
  }
}
```
If the PR is accepted, you'll see it on the next version change log :smile:

It's not complicated to do it by hand, though. Even though the PR seems large, the majority of the changes are snapshot related. 
You can use it in your own version of Grommet.

File: src/js/components/RadioButton/RadioButton.js [hunk 1]
```diff
@@ -41,8 +41,20 @@ const RadioButton = forwardRef(
...
+      theme.radioButton.background.color,
+      theme,
+    );
+
     if (checked) {
       borderColor = normalizeColor(theme.radioButton.color || 'control', theme);
+
+      if (theme.radioButton.check.background.color) {
+        backgroundColor = normalizeColor(
+          theme.radioButton.check.background.color || 'light-1',
```
Comment (ShimiSun) [inline src/js/components/RadioButton/RadioButton.js:54]: In case `theme.radioButton.check.background.color` is undefined, why are you assuming we should default to `light-1` instead of not assigning anything and keeping `backgroundColor` as is?

**Review by ShimiSun — COMMENTED** [review]
Thank you for this PR, dropped a small question.

File: src/js/components/RadioButton/RadioButton.js (hunk 1 above)
Comment (ramos-ph) [reply src/js/components/RadioButton/RadioButton.js:54]: I can't remember exactly what was my thought process to that, but I was pretty sure that it was related to the default `theme.radioButton.background.color` on the base theme. I see my mistake now :sweat_smile:

Comment (ramos-ph) [reply src/js/components/RadioButton/RadioButton.js]: So sorry for taking that long. Had to deal with another things.
Anyway, resolved in 5700ce5

File: src/js/components/RadioButton/__tests__/RadioButton-test.js [hunk 2]
```diff
@@ -104,6 +104,25 @@ describe('RadioButton', () => {
...
+      <Grommet theme={customTheme}>
+        <RadioButton name="test" />
+      </Grommet>,
+    );
+
+    const tree = component.toJSON();
+    expect(tree).toMatchSnapshot();
+  });
+
+  test('checked background-color themed', () => {
```
Comment (jcfilben) [inline src/js/components/RadioButton/__tests__/RadioButton-test.js:125]: Thanks for adding tests!

File: src/js/themes/base.js [hunk 3]
```diff
@@ -1119,11 +1119,17 @@ export const generate = (baseSpacing = 24, scale = 6) => {
         },
         width: '2px',
       },
+      background: {
+        color: {
+          dark: 'light-4',
+          light: 'light-1',
+        },
+      },
```
Comment (jcfilben) [inline src/js/themes/base.js:1127]: I'm thinking we could not set defaults for the background color and just leave it as
```
// background: {
//    color: undefined,
//  },
```

File: src/js/themes/base.js [hunk 4]
```diff
@@ -1119,11 +1119,17 @@ export const generate = (baseSpacing = 24, scale = 6) => {
...
       check: {
         radius: '100%',
-        // background: {
-        //  color: undefined,
-        // },
+        background: {
+          color: undefined,
+        },
```
Comment (jcfilben) [inline src/js/themes/base.js:1132]: Could this be left commented out and then just check if it is defined before using it in code?

**Review by jcfilben — COMMENTED** [review]
Looks good, tested with storybook examples and the code is working as expected. I just left some minor comments/questions below

**Comment by jcfilben** [comment]
Hey @ramos-ph just wanted to check back in on this pull request, it has been a while but it is so close to the finish line! Are you still interested in working on this?

**Review by jcfilben — APPROVED** [review]
Looks good!
