### PR TITLE
FormField Focus - Alternate Solution

### LINKED ISSUE #5887: FormField with Select + Search receives double focus
### Expected Behavior

When Select search input is active element, it should be the only element with focus indicator.

### Actual Behavior

For certain themes (such as HPE), focus indicator is being shown on FormField and Select search input.

### URL, screen shot, or Codepen exhibiting the issue

double-focus

https://design-system.hpe.design/components/select?q=select#select-with-search

### Steps to Reproduce

1. Open Search
2. See double focus.

### Your Environment

- Grommet version: Stable
- Browser Name and version: Chrome Version 97.0.4692.71
- Operating System and version (desktop or mobile): MacOS Big Sur

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
This fixes an issue where Select with search receives double focus when it is contained within a FormField. This is an alternate solution to the one proposed in #5890. This solution relies less on knowing the specific component that is the child of FormField and handling focus based on that, but is instead a more general approach.

**Note:**
The chromatic snapshot change is happening because of the code I added on line 277 in FormField.js that sets isFileInputComponent to true when it is defined like this: ` <FormField label="File" name="file" component={FileInput} />`
```
if (component && component.displayName === 'FileInput' && !isFileInputComponent) {
  isFileInputComponent = true;
}
```
Previously the style of a FileInput within a FormField would change based on how it was written:
```javascript
 <FormField label="File" name="file" component={FileInput} />
```
Would result in this:
Screen Shot 2022-01-14 at 12 15 35 PM

Whereas this:
```javascript
 <FormField>
  <FileInput />
</FormField>
```
Would result in this: (Now both options will show up like this)
Screen Shot 2022-01-14 at 12 14 51 PM

#### Where should the reviewer start?
Compare this PR to the approach in #5890 

#### What testing has been done on this PR?
Tested with the following story:
```javascript
import React, { useState } from 'react';
import { FileInput, Form, FormField, Select, DateInput } from 'grommet'

const defaultOptions = ['EMEA', 'Asia/Pacific', 'Americas', 'Polar Regions'];
// Escaping regular expression special characters: [ \ ^ $ . | ? * + ( )
const getEscapedText = (text) => text.replace(/[-\\^$*+?.()|[\]{}]/g, '\\$&');
// Create the regular expression with escaped special characters.
const formatSearchExpression = (text) => new RegExp(getEscapedText(text), 'i');

export const Test = () => {
  const [options, setOptions] = useState(defaultOptions);
  const [selected, setSelected] = useState('');

  const onSearch = (text) => {
    const exp = formatSearchExpression(text);
    setOptions(defaultOptions.filter((option) => exp.test(option)));
  };

  return (
      <Form>
        <FormField
          htmlFor="select-with-search__input"
          name="select-with-search"
          label="Location"
          help="Type to filter the location options"
        >
          <Select
            id="select-with-search"
            name="select-with-search"
            placeholder="Select location"
            searchPlaceholder="Search locations"
            options={options}
            value={selected}
            onChange={({ option }) => setSelected(option)}
            onSearch={(text) => onSearch(text)}
            clear
          />
        </FormField>
        <FormField>
          <DateInput format="mm/dd/yyyy" />
        </FormField>
      </Form>
  );
};

export default {
  title: 'Input/Select/Test',
};
```

#### Do Jest tests follow these best practices?

- [x] `screen` is used for querying.
- [x] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [x] `userEvent` is used in place of `fireEvent`.
- [x] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #5887

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/FormField/FormField.js [hunk 1]
```diff
@@ -451,7 +459,19 @@ const FormField = forwardRef(
...
+          setFocus(containsFocus(formFieldRef.current));
+          const formDescendants =
+            formFieldRef.current.getElementsByTagName('*');
+          let focusableDescendants = 0;
+          for (let i = 0; i < formDescendants.length; i += 1) {
+            const child = formDescendants[i];
+            if (isFocusable(child)) {
+              focusableDescendants += 1;
+            }
+            if (focusableDescendants >= 2 && child === document.activeElement) {
```
Comment (taysea) [inline src/js/components/FormField/FormField.js:471]: maybe adding a small comment around why `2` is the condition would be helpful for folks in future.

suggestion but feel free to alter
```
// FormField descendant could be focusable. If descendant is
// active element in DOM, don't show focus on FormField.
// e.g. DateInput allows Calendar button to receive focus
```

File: src/js/components/FormField/FormField.js [hunk 2]
```diff
@@ -451,7 +459,19 @@ const FormField = forwardRef(
...
+              setFocus(false);
```
Comment (taysea) [inline src/js/components/FormField/FormField.js:472]: I would expect a snapshot change if we had a test case covering this, could be add one here -- maybe using Select + Search or DateInput calendar button as the use case?

**Comment by taysea** [comment]
Overall, I like this approach better

File: src/js/components/FormField/FormField.js (hunk 1 above)
Comment (jcfilben) [reply src/js/components/FormField/FormField.js:474]: Added a comment in the latest push

File: src/js/components/FormField/FormField.js (hunk 2 above)
Comment (jcfilben) [reply src/js/components/FormField/FormField.js:475]: I added a test in the most recent commit for testing focus with DateInput within a FormField

**Comment by jcfilben** [comment]
> Do you have any insight on why a snapshot changed? seems like everything is just shifted down by a pixel or two?

I updated the PR description with an explanation on the chromatic snapshot change

File: src/js/components/FormField/FormField.js [hunk 3]
```diff
@@ -451,7 +459,22 @@ const FormField = forwardRef(
...
         style={outerStyle}
         onFocus={(event) => {
-          setFocus(shouldKeepFocus());
+          setFocus(containsFocus(formFieldRef.current));
+          const formDescendants =
+            formFieldRef.current.getElementsByTagName('*');
+          let focusableDescendants = 0;
+          for (let i = 0; i < formDescendants.length; i += 1) {
+            const child = formDescendants[i];
+            if (isFocusable(child)) {
```
Comment (MikeKingdom) [inline src/js/components/FormField/FormField.js:468]: I like this generic. It seems more generic and more likely to work with random components.

One question I have is how does this work with Drops which may not be a descendent? Is this an issue?

File: src/js/components/FormField/FormField.js [hunk 4]
```diff
@@ -451,7 +459,22 @@ const FormField = forwardRef(
...
+              focusableDescendants += 1;
+            }
+            // FormField descendant could be focusable. If descendant is
+            // active element in DOM, don't show focus on FormField.
+            // e.g. DateInput allows Calendar button to receive focus
+            if (focusableDescendants >= 2 && child === document.activeElement) {
```
Comment (MikeKingdom) [inline src/js/components/FormField/FormField.js:474]: The activeElement check weeds out things that may not actually be visible (e.g. `display:none`) or may be `disabled`?

File: src/js/utils/DOM.js [hunk 5]
```diff
@@ -67,7 +67,12 @@ export const containsFocus = (node) => {
 // Check if the element.tagName is an input, select or textarea
 export const isFocusable = (element) => {
   const tagName = element.tagName.toLowerCase();
-  return tagName === 'input' || tagName === 'select' || tagName === 'textarea';
+  return (
+    tagName === 'input' ||
```
Comment (MikeKingdom) [inline src/js/utils/DOM.js:71]: I think relying on tagName misses a lot of rich or custom components. For example a RangeSelector has two little controls, one of which may have the focus. Those controls are just `div`s with `tabindex="0"`. If a RangeSelector is somehow one of the descendents then it won't get counted. Focusable things include those tags plus basically anything with `tabindex` (even if it is "-1").

File: src/js/components/FormField/FormField.js (hunk 3 above)
Comment (jcfilben) [reply src/js/components/FormField/FormField.js:468]: When focus transfers to content in the Drop this is handled by `setFocus(containsFocus(formFieldRef.current));` (line 462 in FormField.js) so it is not an issue that the Drop isn't included in formDescendants. (Note: I tested with Select and DateInput, both are built using Drop and focus correctly transfers.)

File: src/js/components/FormField/FormField.js (hunk 4 above)
Comment (jcfilben) [reply src/js/components/FormField/FormField.js:474]: Yes, if an element is disabled or if it has `visibility: 'hidden'` it will still show up in the `focusableDescendants` list but the `child === document.activeElement` check makes sure the focus isn't incorrectly removed from the FormField if it contains a disabled or invisible child. Focus will only be removed from the FormField if there is another focusable descendant and that element has focus

File: src/js/utils/DOM.js (hunk 5 above)
Comment (jcfilben) [reply src/js/utils/DOM.js:71]: Currently looking into if there is a better way to handle this

File: src/js/components/FormField/FormField.js (hunk 4 above)
Comment (MikeKingdom) [reply src/js/components/FormField/FormField.js:474]: Thanks. Sounds good.

File: src/js/components/FormField/FormField.js (hunk 3 above)
Comment (MikeKingdom) [reply src/js/components/FormField/FormField.js:468]: Great. Thanks.

File: src/js/utils/DOM.js (hunk 5 above)
Comment (MikeKingdom) [reply src/js/utils/DOM.js:71]: I think adding the tabindex check OR'd with the above tags is promising.

Comment (jcfilben) [reply src/js/utils/DOM.js:71]: Updated in latest commit

File: src/js/components/FormField/FormField.js [hunk 6]
```diff
@@ -451,7 +459,47 @@ const FormField = forwardRef(
...
+            if (
+              (children &&
+                children.type &&
+                grommetInputNames.includes(children.type.displayName)) ||
+              (!children &&
+                component &&
+                grommetInputNames.includes(component.displayName)) ||
+              (!children && !component)
+            )
+              isGrommetInputComponent = true;
```
Comment (MikeKingdom) [inline src/js/components/FormField/FormField.js:483]: I'm not sure if I'm reading this right, but it's trying to decide if the component or child of the formfield is one of the known Grommet input style components but does that mean if the child is a Box that contains a grommet input component it won't notice? And if we add some other grommet input type component we'll have to realize we need to update FormField? It's not clear to me why it really matters if it's a grommet component (ie. that distinction is really complicating this code alot.)

File: src/js/utils/DOM.js [hunk 7]
```diff
@@ -67,25 +67,13 @@ export const containsFocus = (node) => {
...
-export const shouldKeepFocus = () => {
-  const element = document.activeElement;
-  if (isFocusable(element)) return true;
-  return !!getFirstFocusableDescendant(element);
+  return (
+    tagName === 'input' ||
+    tagName === 'select' ||
+    tagName === 'textarea' ||
+    tagName === 'button' ||
+    element.tabIndex >= 0
```
Comment (MikeKingdom) [inline src/js/utils/DOM.js:75]: Why exclude -1? -1 takes it out of the tab order but you can still get focus on it a couple different ways.

Comment (jcfilben) [reply src/js/utils/DOM.js:75]: Including -1 results in too many elements being marked as focusable. For example, with the Select component 9 elements will be marked as focusable including Boxes, Icons, Svgs, and others because they have a tabIndex of -1.

File: src/js/components/FormField/FormField.js (hunk 6 above)
Comment (jcfilben) [reply src/js/components/FormField/FormField.js:483]: If a FormField contains one of the grommet input components, the input components are set up to not have a `focusIndicator` and instead have the focus on the FormField. So for grommet input components even though they have a focusable descendant we don’t want to remove focus from the FormField. For all other components (including custom components) we should handle focus normally and remove focus from the FormField when one of the focusable descendants has focus.

If an input component is wrapped with a Box it won’t be flagged as a grommet input component and focus will be on the FormField. (Tested with Select wrapped in a Box)

As far as updating FormField.js when we add a new grommet input component this is something we would have to do anyway because `grommetInputNames` is being used to determine padding and in other places in FormField.js

Comment (taysea) [reply src/js/components/FormField/FormField.js:480]: @jcfilben -- regarding your point re: Select wrapped in Box, are you saying that if I implemented the following, I would still see the double focus on Select search and formfield?

```
<FormField>
   <Box>
      <Select onSearch={() => {}} />
   </Box>
</FormField>
```

Comment (jcfilben) [reply src/js/components/FormField/FormField.js:480]: Sorry I should have wrote that the Select will have focus and not the FormField in this case. If you have Select wrapped in a Box it wouldn't be flagged as a grommet input component and focus would be handled in this statement: `if(focusableDescendants.length >= 1 && !isGrommetInputComponent && focusableDescendants.includes(document.activeElement)) setFocus(false)` (See line 494 of FormField). The select would count as a focusable descendant and it would be the active element when tabbed to so focus on FormField would be set to false as we would see the focusIndicator on Select like this after tabbing to the field:

Screen Shot 2022-01-20 at 1 58 37 PM

Comment (taysea) [reply src/js/components/FormField/FormField.js:480]: Gotcha, thanks for clarifying. Something I'm noticing here (but a separate issue from what you're doing) is the FormField and Select both are having their border now (creating a double border) -- not sure if we have an issue filed around it. It seems to be an effect of only searching the direct children of the formfield

Comment (jcfilben) [reply src/js/components/FormField/FormField.js:480]: The double border shown in the screenshots above is just a result of wrapping Select in a Box within the FormField. If we have `<FormField> <Select /> </FormField>` there is code in the FormField.js file that removes the border of Select so we don't have 2 borders. If you are wrapping Select in a Box within FormField I think the expectation would be that you are doing some custom thing and I think it is reasonable to still show the Select border

File: src/js/components/FormField/FormField.js [hunk 8]
```diff
@@ -451,7 +459,44 @@ const FormField = forwardRef(
...
+            that has focus. */
+            if (
+              (focusableDescendants.length >= 2 &&
+                isGrommetInputComponent &&
+                child === document.activeElement) ||
+              (focusableDescendants.length >= 1 &&
+                !isGrommetInputComponent &&
+                focusableDescendants.includes(document.activeElement))
+            )
+              setFocus(false);
```
Comment (MikeKingdom) [inline src/js/components/FormField/FormField.js:498]: I think you can actually remove all this if you change `containsFocus` like noted below. I tested the result and it seems to work well

File: src/js/utils/DOM.js [hunk 9]
```diff
@@ -67,25 +67,13 @@ export const containsFocus = (node) => {
...
+  );
```
Comment (MikeKingdom) [inline src/js/utils/DOM.js:76]:
```jsx
return (
  element.tabIndex >= 0 ||
  ((tagName === 'input' ||
    tagName === 'select' ||
    tagName === 'textarea' ||
    tagName === 'button') &&
    element.tabIndex !== -1)
  );
```

**Review by MikeKingdom — APPROVED** [review]
Awesome. Thanks!

**Review by taysea — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]
