### PR TITLE
Fixed date in calendar component  when no time is specified in ISOString

### LINKED ISSUE #6356: Calendar date always selecting previous date incase date field is set without timestamp
Grommet Calendar always picks the previous date to incase the date field is sent in "YYYY-MM-DD" format.

### Expected Behavior
It should select the specified date even without the time being sent. 

### URL, screen shot, or Codepen exhibiting the issue

Screenshot 2022-09-28 at 10 11 36 PM
Screenshot 2022-09-28 at 10 11 10 PM

https://v2.grommet.io/calendar?c=DwYQhgNgpgdgJmATgKAASoM4EsBeUC8ARBgLaQSFqoIAuBA3oQEwAMTTAtAIwsfsBcPfgGYWhAL5UA9jADKUaAGMa+egApaUAJSp8APlT1xkgPR6gA

### Your Environment

- Grommet version: any version (2.21.0)
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac, Windows

### PR DESCRIPTION
**Pull request by KostasTheodoro**
#### What does this PR do?
Fixes #6356 
#### What testing has been done on this PR?
I added a unit test. Tested manually in storybook with ticket's specific timezone problem and seemed to fix the issue. Also i added a snapshot before fixing the underline issue and then tested with issue fixed and had the correct date results.
#### How should this be manually tested?
You can test it locally in storybook by using date without time in ISOstring with different timezones. 
#### Do Jest tests follow these best practices?

- [x] `screen` is used for querying.
- [x] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [x] `userEvent` is used in place of `fireEvent`.
- [x] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
#6356 bug fix
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
yes

### CODE REVIEW

File: src/js/components/Calendar/__tests__/Calendar-test.tsx [hunk 1]
```diff
@@ -38,6 +38,17 @@ describe('Calendar', () => {
...
 
+  test('date without time specified', () => {
+    // correct date displayed if time is not specified in ISOstring
+    const { container } = render(
+      <Grommet>
+        <Calendar date={DATE.split('T')[0]} animate={false} />
+      </Grommet>,
+    );
+
+    expect(container.firstChild).toMatchSnapshot();
```
Comment (jcfilben) [inline src/js/components/Calendar/__tests__/Calendar-test.tsx:49]: I think we can just use an assertion here to verify we have the expected date instead of needing to use a snapshot

Comment (KostasTheodoro) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx]: Hello, i updated the test to not use snapshot.

**Review by jcfilben — APPROVED** [review]
This looks good to me, @taysea or @halocline would one of you be willing to take a look at this as well? I just want extra eyes on this since Calendar has been pretty tricky in the past

**Review by halocline — APPROVED** [review]
This fix is looking good. Thank you, @KostasTheodoro.

@jcfilben - I believe we need this same fix applied to DateInput as well. I have created https://github.com/grommet/grommet/issues/6421 representing that work. I think we can merge this PR and get a separate one for DateInput + consolidate logic.

**Review by ericsoderberghp — APPROVED** [review]
