### PR TITLE
Fix #2906 - Lazy load Layer container for successful use in SSR contexts

### LINKED ISSUE #2906: Layer component Error in Gatsby js
I have a starter for [gatsby js](https://github.com/gatsbyjs/gatsby): [gatsby-starter-blog-grommet](https://github.com/Ganevru/gatsby-starter-blog-grommet) based on Grommet - it has an error described here: [gatsby-starter-blog-grommet/issues/4](https://github.com/Ganevru/gatsby-starter-blog-grommet/issues/4)

I wrote about this error: [Grommet Layer component Error #12467](https://github.com/gatsbyjs/gatsby/issues/12467), but there I was recommended to write here, a quote: 

> @Ganevru Looks like the Layer component is trying to access document.

> It is breaking during build because document is not available in a non browser environment and therefore server side rendering is failing. gatsby develop works because we don't do SSR during develop currently.

> I'd recommend opening an issue in grommet/grommet

The error itself occurs if use [Layer component](https://github.com/grommet/grommet/tree/master/src/js/components/Layer) anywhere in the code:

    <Grommet theme={THEMES[themeByThemeType(themeType)]}>

      <Grommet theme={siteTheme}>

        <Layer />

        <GlobalStyle />

        <Box direction="column" align="center">

        ...

In `develop` everything works fine, but when generating the site `gatsby build` the following error occurs:

    error Building static HTML failed for path "/blog/as-you/"

    See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

    24 |     _this = _Component.call.apply(_Component, [this].concat(args)) || this;

    25 | 

    > 26 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "originalFocusedElement", document.activeElement);

     | ^

    27 | 

    28 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "layerContainer", getNewContainer());
    29 | 

    WebpackError: ReferenceError: document is not defined

    - Layer.js:26 new Layer
    [lib]/[grommet]/es6/components/Layer/Layer.js:26:1

    - bootstrap:22 c
    lib/webpack/bootstrap:22:1

    - bootstrap:25 Sa
    lib/webpack/bootstrap:25:1

    - bootstrap:30 a.render
    lib/webpack/bootstrap:30:1

    - bootstrap:30 a.read
    lib/webpack/bootstrap:30:1

    - bootstrap:42 renderToString
    lib/webpack/bootstrap:42:1

    - static-entry.js:194 Module.default
    lib/.cache/static-entry.js:194:18

    - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

    - gatsby-browser-entry.js:11 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:11:1

    - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

    - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

    - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

    - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

    - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

    error Command failed with exit code 1.

### PR DESCRIPTION
**Pull request by halocline**
#### What does this PR do?
Implements [recommended solution](https://github.com/grommet/grommet/issues/2906#issuecomment-472643372), ensuring that window.document is available before rendering the Layer container. This makes sure the Layer component will succeed in build processes for server side rendering contexts.

Waits for component mount, then accesses dependent document elements, then re-renders Layer component with document elements.

#### Where should the reviewer start?
src/js/components/Layer/Layer.js

- Added state for availability of `layerComponent`.
- Moved `originalFocusedElement` and `layerContainer` into `componentDidMount()`

#### What testing has been done on this PR?

1. Replicated [original issue](https://github.com/grommet/grommet/issues/2906) occurring during Gatsby build
2. Manual testing in Storybook
3. Passes unit tests
4. Performed successful `gatsby build`

#### Any background context you want to provide?
[original issue](https://github.com/grommet/grommet/issues/2906)

#### What are the relevant issues?
1. [#2906](https://github.com/grommet/grommet/issues/2906)
2. This solution might be applicable to Drop.js as well 

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by halocline** [comment]
Yes, @oorestisime, you are correct. Will do. I can add an additional PR in
the coming days.

**Comment by ShimiSun** [comment]
hi @halocline, thanks for jumping in on this one! 
can we add a quick test to this PR? or do you need a few more days?

**Comment by halocline** [comment]
Hi @ShimiSun, another day or two would be great.

File: src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap [hunk 1]
```diff
@@ -2477,3 +2477,5 @@ exports[`Layer position top 1`] = `
 `;
 
 exports[`Layer position top 2`] = `""`;
+
+exports[`Layer should be null prior to mounting, displayed after mount 1`] = `null`;
```
Comment (oorestisime) [inline src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap]: thanks for adding the test! mind just adding a nice id because right now it doesn't look like anything actionable if it breaks later!

Comment (halocline) [reply src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap]: @oorestisime I made the test id more descriptive. Let me know if you were thinking something else.

**Comment by oorestisime** [comment]
i think something went wrong with your rebase. their are a lot of unrelated changes. let me know  if you want me to take this over or if you have time to properly rebase :)
the rest looks perfect and the changes made to the test look good as well!

**Comment by halocline** [comment]
I attempted to rebase again and am seeing Showing 3 changed files with 106
additions and 6 deletions.
https://github.com/grommet/grommet/compare/master...halocline:fix-2906

If that isn't proper, then I could use help getting untangled.

**Comment by oorestisime** [comment]
resetted hard the branch and picked your commits! can you have a look in case i missed something?

**Comment by halocline** [comment]
Looks like what I was expecting. Thank you!

**Comment by oorestisime** [comment]
Thanks for your contribution!
