### PR TITLE
Calendar - 'space' key can be used to select dates

### LINKED ISSUE #7337: Calendar - date should be selectable by pressing 'space'
### Expected Behavior
Dates in the Calendar should be selectable by clicking, pressing 'space' or 'enter'

### Actual Behavior
Pressing 'space' doesn't work to select the date

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/visualizations-calendar-simple--simple

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by anvesh-singh**
#### What does this PR do?
solves Calendar - date should be selectable by pressing 'space' #7337
#### Where should the reviewer start?
calendar.js
#### What testing has been done on this PR?
passes all premade tests
#### How should this be manually tested?
by pressing space it selects the dates
#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #7337

### CODE REVIEW

**Review by jcfilben — COMMENTED** [review]
Almost there, just a few comments. It looks like when we press 'space' on a date in the calendar the date does get selected but the page also scrolls. Can we prevent the page scroll?

Can you also sign your commits so the dco check passes? See https://github.com/grommet/grommet/pull/7357/checks?check_run_id=31364109691 for more details

**Comment by anvesh-singh** [comment]
> Almost there, just a few comments. It looks like when we press 'space' on a date in the calendar the date does get selected but the page also scrolls. Can we prevent the page scroll?
> 
> Can you also sign your commits so the dco check passes? See https://github.com/grommet/grommet/pull/7357/checks?check_run_id=31364109691 for more details

i did commit with -s flag but it still does not pass the dco test please tell me how to do it since i signed off the commit but it does not work

**Comment by jcfilben** [comment]
You will need the -s flag and a remediation commit. See https://github.com/grommet/grommet/pull/7357/checks?check_run_id=31375867254

File: src/js/components/Calendar/Calendar.js [hunk 1]
```diff
@@ -889,6 +889,11 @@ const Calendar = forwardRef(
           {daysOfWeek && renderDaysOfWeek()}
           <Keyboard
             onEnter={() => (active !== undefined ? onClick(active) : undefined)}
+            onSpace={(event) => {
+              event.preventDefault();
+              event.stopPropagation();
```
Comment (jcfilben) [inline src/js/components/Calendar/Calendar.js:894]:
```suggestion
```
I don't think we need to `stopPropagation` here, just `preventDefault`

**Review by jcfilben — COMMENTED** [review]
Could you add a unit test for this behavior?

**Comment by anvesh-singh** [comment]
> Could you add a unit test for this behavior?

i have added the test as well as removed the stoppropogation but still the dco check is not being passed

File: src/js/components/Calendar/Calendar.js [hunk 2]
```diff
@@ -889,6 +889,10 @@ const Calendar = forwardRef(
           {daysOfWeek && renderDaysOfWeek()}
           <Keyboard
             onEnter={() => (active !== undefined ? onClick(active) : undefined)}
+            onSpace={(event) => {
```
Comment (britt6612) [inline src/js/components/Calendar/Calendar.js:892]: this is causing the lint error of 
```
 Expected an assignment or function call and instead saw an expression  no-unused-expressions
```
to fix think we can simplify to be 

```
          onSpace={(event) => {
              event.preventDefault();
              if (active !== undefined) {
                onClick(active);
              }
            }}
```

File: src/js/components/Calendar/Calendar.js [hunk 3]
```diff
@@ -897,6 +901,7 @@ const Calendar = forwardRef(
                 changeReference(addDays(active, -7));
               }
             }}
+
```
Comment (jcfilben) [inline src/js/components/Calendar/Calendar.js:904]:
```suggestion
```

File: src/js/components/Calendar/Calendar.js (hunk 2 above)
Comment (anvesh-singh) [reply src/js/components/Calendar/Calendar.js:892]: thanks for the change fixed it

Comment (britt6612) [reply src/js/components/Calendar/Calendar.js:892]: thank you!

**Review by britt6612 — APPROVED** [review]

File: src/js/components/Calendar/__tests__/Calendar-test.tsx [hunk 4]
```diff
@@ -760,6 +760,33 @@ describe('Calendar Keyboard events', () => {
...
+  test('onSpace', () => {
+    const onSelect = jest.fn();
+    const { getByText } = render(
+      <Grommet>
+        <Calendar date="2020-01-15" onSelect={onSelect} />
+      </Grommet>
+    );
+
+    fireEvent.mouseOver(getByText('15'));
+    fireEvent.click(getByText('15'));
```
Comment (jcfilben) [inline src/js/components/Calendar/__tests__/Calendar-test.tsx:772]:
```suggestion
```
Can we remove these lines since we just want to test the keyboard 'space' behavior?

Comment (anvesh-singh) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: i tried removing it but the test fails if we just test the space event only

Comment (britt6612) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: @anvesh-singh thank you we can try on our end and check!

Comment (britt6612) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: so we can leave the following 
```
   fireEvent.mouseOver(getByText('15'));
   fireEvent.click(getByText('15'));

```

this helps us be able to put the focus within the calendar alot easier and have it other places but to actually test the `space` actions we should also add either a keydown or left or right key then press `space` to confirm that this click the correct date


something like the following

```
    fireEvent.mouseOver(getByText('15'));
    fireEvent.click(getByText('15'));
    fireEvent.keyDown(getByText('15'), {
      key: 'ArrowRight',
      keyCode: 39,
      which: 39,
    });
    // press enter to change date to active
    fireEvent.keyDown(getByText('15'), {
      key: '',
      keyCode: 32,
      which: 32,
    });
    // Jan 16th is set to active
    expect(onSelect).toBeCalledWith(expect.stringMatching(/^2020-01-16T/));
```

Comment (anvesh-singh) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: yeah but i have also added the event listener to check if the default behavior is also prevented which is a scroll down on space

Comment (britt6612) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: Im not sure Im following? so you want to also include to see if `window.scrollTo` has been called? We can use the keydown in the test then twice then press space?

Comment (jcfilben) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: Don't worry about testing the preventDefault behavior in this test, I would just focus on testing the 'space' behavior

Comment (anvesh-singh) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: so should i just remove it ?

Comment (jcfilben) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: Don't remove the prevent default code in Calendar but just don't worry about testing that behavior in the unit test

Comment (anvesh-singh) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: so should i remove these lines ????
@jcfilben 

const preventDefaultSpy = jest.spyOn(spaceKeyDownEvent, 'preventDefault');
expect(preventDefaultSpy).toHaveBeenCalled();

Comment (jcfilben) [reply src/js/components/Calendar/__tests__/Calendar-test.tsx:772]: Yes

**Review by MikeKingdom — APPROVED** [review]

File: .yarn/install-state.gz
Comment (jcfilben) [inline .yarn/install-state.gz:1]: Wasn't expecting this file to be included, it should be ignored since it is listed in `.gitignore`

Comment (britt6612) [reply .yarn/install-state.gz:1]: weird this may have been added in the earlier commits let me see if I can fix

**Review by jcfilben — APPROVED** [review]
Looks good!
