### PR TITLE
Fix/datatable units

### LINKED ISSUE #4610: Add `unit` to DataTable column structure
### Expected Behavior
Allow user to specify a unit value that would appear next to the column label. User should be able to style this value via the theme and provide a custom render if desired. It is a common case that users may have a unit accompany a column label that should receive separate style treatment than the label itself.

### Actual Behavior
Not currently existing.

### URL, screen shot, or Codepen exhibiting the issue
Screen Shot 2020-10-14 at 10 12 14 AM

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by MikeKingdom**
#### What does this PR do?
Adds a `units` string to the column definition for DataTables. This string will be displayed in the header with a default text size of `xsmall` and the same text properties used for the column header. It also will use any properties specified under `datatable.header.units` in the theme for units Text component.

#### Where should the reviewer start?
DataTable/Header.js

#### What testing has been done on this PR?
A 'Units' story has been added to the DataTables storybook.
A Jest test case has been added to the DataTables Jest test.

#### How should this be manually tested?
Look at the Units story in the DataTables storybook.

#### Any background context you want to provide?
See #4610 and #1190

#### What are the relevant issues?
Fixes #4610 

#### Do the grommet docs need to be updated?
Done

#### Should this PR be mentioned in the release notes?
Sure.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/DataTable/doc.js [hunk 1]
```diff
@@ -122,6 +122,7 @@ export const doc = DataTable => {
           ]),
           PropTypes.string,
         ]),
+        units: PropTypes.string,
```
Comment (ShimiSun) [inline src/js/components/DataTable/doc.js:125]: This is actually an object that accepts all props of Text component

File: src/js/components/DataTable/doc.js [hunk 2]
```diff
@@ -393,6 +394,12 @@ export const themeDoc = {
     type: 'string | object',
     defaultValue: undefined,
   },
+  'dataTable.header.units': {
+    description: `The styles for the units display in the header. This
```
Comment (ShimiSun) [inline src/js/components/DataTable/doc.js:398]:
```suggestion
    description: `Any Text component properties for styling the header's units text. This
```
Or something along the lines that implies the user to use Text props for `units`

File: src/js/components/DataTable/doc.js [hunk 3]
```diff
@@ -393,6 +394,12 @@ export const themeDoc = {
...
+    can be any valid Text properties`,
+    type: 'object',
+    defaultValue: '{ size: "xsmall" }',
```
Comment (ShimiSun) [inline src/js/components/DataTable/doc.js:401]: Since you are defining the default properties of the theme, I would have expected to see this default value on base.js and not hardcode on the component file.

File: src/js/components/DataTable/doc.js (hunk 1 above)
Comment (MikeKingdom) [reply src/js/components/DataTable/doc.js:125]: This one is actually the string units rather than props. For example, "(TiB)" or "%" etc.

File: src/js/components/DataTable/Header.js [hunk 4]
```diff
@@ -183,6 +191,15 @@ const Header = ({
               }
             } else content = header;
 
+            if (unitsContent) {
+              content = (
+                <Box direction="row" align="baseline" gap="xsmall">
```
[the remark this answers is not in the document]
Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js:196]: Good point. I'll add the align/gap to the header.units part of the theme. Is there a good place to put defaults other than adding them to the base grommet theme or is that the place?

The reason it's baseline is otherwise it's 'center' which doesn't work well for something with 2 different font sizes like this.

[the remark this answers is not in the document]
Comment (ShimiSun) [reply src/js/components/DataTable/Header.js:196]: >Is there a good place to put defaults other than adding them to the base grommet theme or is that the place?

Since the styling of the unit is retrieved from the theme I think it will be the best place.

File: src/js/components/DataTable/doc.js (hunk 3 above)
Comment (MikeKingdom) [reply src/js/components/DataTable/doc.js:401]: Perfect. Done

**Review by ShimiSun — COMMENTED** [review]
Needs to address changes of index.d.ts and base.d.ts to support typescript users

File: src/js/themes/base.d.ts [hunk 5]
```diff
@@ -625,6 +625,11 @@ export interface ThemeType {
         background?: BackgroundType;
       };
       pad?: PadType;
+      units?: {
+        gap?: GapType;
+        align?: string;
```
Comment (ShimiSun) [inline src/js/themes/base.d.ts:630]: Should this be `AlignType`?

File: src/js/components/DataTable/Header.js [hunk 6]
```diff
@@ -183,6 +193,19 @@ const Header = ({
               }
             } else content = header;
 
+            if (unitsContent) {
+              content = (
+                <Box
+                  direction="row"
+                  align={theme.dataTable.header.units.align}
+                  gap={theme.dataTable.header.units.gap}
```
Comment (ShimiSun) [inline src/js/components/DataTable/Header.js:201]: I think the three of those should be under `theme.dataTable.header.units.container` and let the container accept any BoxProps. hence will clean up this code to:
```
  <Box {...theme.dataTable.header.units.container}> ... </Box>
```

Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js:201]: I like it...

File: src/js/themes/base.d.ts (hunk 5 above)
Comment (MikeKingdom) [reply src/js/themes/base.d.ts:630]: Somewhere else was just doing string but that would be much better

File: src/js/components/DataTable/Header.js (hunk 6 above)
Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js]: Done

File: src/js/themes/base.d.ts (hunk 5 above)
Comment (MikeKingdom) [reply src/js/themes/base.d.ts]: Done

Comment (ShimiSun) [reply src/js/themes/base.d.ts]: Feel free to fix the other place as well.

Comment (MikeKingdom) [reply src/js/themes/base.d.ts]: Can we merge this without updating the other usages, especially since I didn't have to specify it here with the container change? I'm actually supposed to be on FTO since Wednesday.

Comment (ShimiSun) [reply src/js/themes/base.d.ts]: No rush. we rather have all the relevant fixes in one PR, easier to track.

File: src/js/components/DataTable/Header.js [hunk 7]
```diff
@@ -183,6 +191,15 @@ const Header = ({
               }
             } else content = header;
 
+            if (unitsContent) {
+              content = (
+                <Box {...theme.dataTable.header.units.container}>
```
Comment (ericsoderberghp) [inline src/js/components/DataTable/Header.js:196]: Something feels a little odd to have `units.container` driving the Box containing the main header content.

I'm also wondering how this interacts with `columns.align`, since that also has some layout aspects to it.

With the way this PR is structured, the sort icon will be placed between the heading label and the units. I'm wondering if that's the typical design approach. I could see designs wanting the units to be next to the label with the sort icon following the units.

Here are some rough possible designs:
| label units            |
|            label units |
| label            units |
| label units sort    |
|    label units sort |
| label sort    units |

At this point, I'm wondering if the last design should require a custom column.header render function and that the theme should be more focused around just the Text for the units, so the theme could have just a color, size, margin.

Comment (ericsoderberghp) [reply src/js/components/DataTable/Header.js:196]: I think part of my confusion is around the naming of "units.container" compared to what it is affecting.

Would it work to just do: `<Box align="baseline">{content}<Text {...theme.dataTable.units} /></Box>` when there are units and put a left margin on the Text?

Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js:196]: That's certainly possible if that works for you (+ direction="row"). The nice part about having all the box props in the theme under something like container is it gives you full control rather than having the hardcoded parts (kinda Shimi's earlier comment.) Although most of the other layout in Header.js is hardcoded.

Comment (ericsoderberghp) [reply src/js/components/DataTable/Header.js:196]: If we decide to keep it, I think we would need to put it somewhere other than under `units`. For example, if I set `units.container.background = 'brand'`, it will be the background of both the label and the units. Something on the order of `theme.dataTable.labelUnitsContainer` would be more accurate.

However, I tend towards not putting it in the theme at the moment. As you mention, there's a bunch of other styling stuff hardcoded in the Header already. I'd rather bring it all into the theme at the same time, driven by some specific design references.

Comment (MikeKingdom) [reply src/js/components/DataTable/Header.js]: Simplified...Does this look a little better?

Comment (ericsoderberghp) [reply src/js/components/DataTable/Header.js]: yep

File: src/js/themes/base.js [hunk 8]
```diff
@@ -723,6 +723,10 @@ export const generate = (baseSpacing = 24, scale = 6) => {
         //   background: undefined,
         // },
         // pad: undefined,
+        units: {
+          size: 'xsmall',
```
Comment (ericsoderberghp) [inline src/js/themes/base.js:727]: I think we should default to `color = "text-xweak"` to align more with `theme.formField.info` and not change the size.

**Review by ericsoderberghp — COMMENTED** [review]
Structure looks great, just one small style suggestion. Sorry this has dragged on long.

File: src/js/themes/base.js (hunk 8 above)
Comment (MikeKingdom) [reply src/js/themes/base.js:727]: This is the difference with color="text-xweak" and the default header size:
image

**Review by ericsoderberghp — APPROVED** [review]
