### PR TITLE
SelectMultiple - fix object comparison

### LINKED ISSUE #6395: SelectMultiple - pre selected object options not working
### Expected Behavior
Options in `value` should should show as selected

### Actual Behavior
In SelectMultiple if `options` is an array of objects and `value` is initially set to one of the options, the option will not show as selected when the drop is open

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-ftppqe?file=/index.js

### Steps to Reproduce

1. Go to codesandbox link above
2. Open the drop and see that the 'xyz' option is not checked

### Your Environment

- Grommet version: codesandbox example used v2.26.0 of grommet but I also confirmed this behavior on the stable branch
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Fixes an issue in SelectMultiple where objects are not being correctly compared. This PR removes array function instances such as `indexOf` and `includes` which don't work well for arrays containing objects.

Note: marking as a draft, I still need to add jest tests

#### Where should the reviewer start?
See the `getOptionIndex` and `arrayIncludes` functions added in the util file.

#### What testing has been done on this PR?
Tested with existing storybook stories and the following story (see [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-drqodb?file=/index.js) to see before and after):
```javascript
import React, { useState } from 'react';

import { SelectMultiple } from '../SelectMultiple';
const options = [
  { fieldType: 'SYSTEM', value: 'abc', display: 'ABC', other: 123 },
  { fieldType: 'SYSTEM', value: 'xyz', display: 'XYZ', other: 456 },
];
export const Test = () => {
  const [value, setValue] = useState([
    {
      fieldType: 'SYSTEM',
      value: 'abc',
      display: 'ABC',
      other: 123,
    },
  ]);
  return (
    <SelectMultiple
      showSelectedInline
      labelKey="display"
      valueKey="value"
      options={options}
      value={value}
      onChange={({ value }) => setValue(value)}
    />
  );
};

export default {
  title: 'Input/SelectMultiple/Test',
};


```

#### Do Jest tests follow these best practices?

- [x] `screen` is used for querying.
- [x] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #6395 

#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
Yes
#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/Select/utils.js [hunk 1]
```diff
@@ -17,7 +17,25 @@ export const getOptionLabel = (index, options, labelKey) =>
 export const getOptionValue = (index, options, valueKey) =>
   applyKey(options[index], valueKey);
 
-export const useDisabled = (disabled, disabledKey, options, valueKey) =>
+export const getOptionIndex = (options, i) => {
+  if (options) {
+    if (typeof i === 'object')
+      return options.findIndex((x) => JSON.stringify(x) === JSON.stringify(i));
```
Comment (taysea) [inline src/js/components/Select/utils.js:23]: Is there any possibility that the key/value pairs of the object might be ordered differently between `x` and `i`? Wondering if a `deepEquals` type function would be more reliable than JSON.stringify

Comment (jcfilben) [reply src/js/components/Select/utils.js:23]: Good point! Would you be okay if I created a separate issue for this instead of handling it in this PR? I think the JSON.stringify will cover the 80% case, but I agree it would be nice to have a more robust method for object comparison. I'm thinking the `deepEquals` type of function will take a bit of time writing and testing to make sure it is working as expected and feel like it would be better to create a separate issue rather than push back the release

Comment (ericsoderberghp) [reply src/js/components/Select/utils.js:23]: I'm wondering if this is being too strict. For instance, if the object in options has something unrelated to the value, like the label changes. I think we should be using valueKey for comparison whenever possible when we have object options.

Comment (jcfilben) [reply src/js/components/Select/utils.js:23]: That's fair, I will go back and make that change

**Review by taysea — APPROVED** [review]
Nice, looks good to me!

**Review by ericsoderberghp — APPROVED** [review]

File: src/js/components/Select/utils.js (hunk 1 above)
Comment (ericsoderberghp) [reply src/js/components/Select/utils.js]: that feels better, thanks

**Comment by taysea** [comment]
Related to https://github.com/grommet/grommet/issues/5198
