### PR TITLE
Select - Fixes behavior when valueKey not specified

### LINKED ISSUE #6368: Select change in behavior when valueKey not specified
### Expected Behavior

Using code like
```
const options = [
  { fieldType: "SYSTEM", value: "abc", display: "ABC", other: 123 },
  { fieldType: "SYSTEM", value: "xyz", display: "XYZ", other: 456 }
];

export default function App() {
  const [value, setValue] = useState(options[1]);
  return (
    <Grommet theme={hpe}>
      <Select
        labelKey="display"
        options={options}
        value={value}
        onChange={({ option }) => setValue(option)}
      />
    </Grommet>
  );
}
```
In version 2.25.1  and earlier this render a select box correctly... behaving like valueKey defaults to 'value'.

### Actual Behavior
In version 2.25.2 and later, this now renders incorrectly.  The value shown as selected (when drop is closed) is 'multiple' and no value appears selected when you expand the drop.

Explicitly setting valueKey='value' fixes the issue, but because it changed behavior, I wanted to notify you of the breaking change.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/objective-sara-dlc5es?file=/src/App.js

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.25.1 vs 2.25.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac

### PR DESCRIPTION
**Pull request by halocline**
#### What does this PR do?

Closes #6368 by consolidating and aligning treatment of valueKey and labelKey throughout Select. Extends work done in #6299.

#### Where should the reviewer start?

Select.js

#### What testing has been done on this PR?

- Storybook modifying ObjectOptions story with combinations listed under manual testing.
- Expanded Jest test coverage
  - adding snapshots for all end states
  - added missing labelKey scenarios

#### How should this be manually tested?

Storybook modifying ObjectOptions story with:
- valueKey present, labelKey missing
- valueKey missing, labelKey present
- valueKey missing, labelKey missing
- valueKey present, labelKey present
- valueKey as object with reduce = true, labelKey missing
- valueKey as object with reduce = true, labelKey present
- valueKey as object with reduce = false, labelKey missing
- valueKey as object with reduce = false, labelKey present

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [x] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?

https://github.com/grommet/grommet/pull/6299

#### What are the relevant issues?

https://github.com/grommet/grommet/issues/6368

#### Do the grommet docs need to be updated?

No.

#### Should this PR be mentioned in the release notes?

Yes.

#### Is this change backwards compatible or is it a breaking change?

Backwards compatible.

### CODE REVIEW

File: src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap [hunk 1]
```diff
@@ -2194,8 +2194,9 @@ exports[`Select Controlled multiple onChange with valueKey string 3`] = `
 }"
 `;
 
-exports[`Select Controlled multiple onChange without valueKey 1`] = `
```
Comment (halocline) [inline src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap:2197]: Note: These snapshots still exist, but have been displaced in order with the additional tests.

**Comment by jcfilben** [comment]
Code looks good, going to look through tests and snapshots tomorrow morning

**Review by ericsoderberghp — APPROVED** [review]
Nice unit test additions!
