### PR TITLE
TextInput onSelect and onSuggestionSelect handlers

### LINKED ISSUE #3118: TextInput makes it difficult to listen for select events on input element
`<TextInput />` has an `onSelect` prop used for the suggestions feature which overrides the `<input />`s `onSelect` prop for listening to [`select`](https://developer.mozilla.org/en-US/docs/Web/API/Element/select_event) events. This makes listening to `select` events on the input more difficult than it should be.

As a solution, I purpose changing the current `onSelect` prop to `onSuggestionSelect` and allow `onSelect` to resume it's default behaviour on the `<input />`.

### Expected Behavior

`<TextInput onSelect={/* ...  */} />` should add the provided function as an event handler for `select` events.

### Actual Behavior

Grommet overrides the `onSelect` prop for suggestion selection events.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-5rcuj (includes a workaround).

### Steps to Reproduce

1. Define an `onSelect` event handler on a `<TextInput />`
2. Notice that it does not listen for `select` events on the `<input />`.

### Your Environment

- Grommet version: 2.7.0

### PR DESCRIPTION
**Pull request by IanKBovard**
#### What does this PR do?
Allows the use of default onSelect event for textInput.

#### Where should the reviewer start?
TextInput.js

#### What testing has been done on this PR?
Within storybook using this.

```javascript
import React from 'react';

import { Box, Grommet, TextInput } from 'grommet';
import { grommet } from 'grommet/themes';

const suggestions = Array(100)
  .fill()
  .map((_, i) => `suggestion ${i + 1}`);

const App = () => {
  const [value, setValue] = React.useState('');

  const onChange = event => setValue(event.target.value);

  const onSelect = event => setValue(event.suggestion);
  const onHightlight = event =>
    console.log(
      event.target.value.substring(
        event.target.selectionStart,
        event.target.selectionEnd,
      ),
    );
  return (
    <Grommet full theme={grommet}>
      <Box fill align="center" justify="start" pad="large">
        <Box width="medium">
          <TextInput
            value={value}
            onChange={onChange}
           // i tested with a combination of onSelect and onSuggestionSelect being present and 
           absent
            onSelect={onHightlight}
            onSuggestionSelect={onSelect}
            suggestions={suggestions}
          />
        </Box>
      </Box>
    </Grommet>
  );
};

export default App;
```
#### How should this be manually tested?
Same as above. 

#### Any background context you want to provide?
Grommets onSelect was overriding the html onSelect.

#### What are the relevant issues?
closes #3118 

#### Do the grommet docs need to be updated?
Yes

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by IanKBovard** [comment]
this issue has not been addressed yet

ericsoderberghp on May 26 Member
The way these are being used seems like they should be using useMemo instead of useRef + useEffect.

IanKBovard 17 days ago Author Member
I'm a little confused about this. My understanding of useMemo is to optimize the performance of complex functions. How can I use it to replace useRef and useEffect?

File: src/js/components/TextInput/TextInput.js [hunk 1]
```diff
@@ -119,6 +119,26 @@ const TextInput = forwardRef(
     const [focus, setFocus] = useState();
     const [showDrop, setShowDrop] = useState();
 
+    const handleTextSelect = useRef();
+    const handleSuggestionSelect = useRef();
+
+    // assigns select handlers
+    useEffect(() => {
```
Comment (ericsoderberghp) [inline src/js/components/TextInput/TextInput.js:126]: Would memo hooks be simpler than ref hooks?
```
const handleSuggestionSelect = useMemo(onSelect && !onSuggestionSelect ? onSelect : onSuggestionSelect, [onSelect, onSuggestionsSelect]);
const handleTextSelect = useMemo(onSelect && onSuggestionSelect ? onSelect : undefined, [onSelect, onSuggestionsSelect]);
```
just wondering

File: src/js/components/TextInput/TextInput.js [hunk 2]
```diff
@@ -308,12 +331,12 @@ const TextInput = forwardRef(
...
                             inputRef.current.focus();
                             closeDrop();
-                            if (onSelect) {
+                            if (handleSuggestionSelect.current) {
                               event.persist();
                               const adjustedEvent = event;
                               adjustedEvent.suggestion = suggestion;
-                              adjustedEvent.target = inputRef.current;
-                              onSelect(adjustedEvent);
+                              adjustedEvent.target = (ref || inputRef).current;
```
Comment (ericsoderberghp) [inline src/js/components/TextInput/TextInput.js:338]: Don't need `ref ||`, `useForwardedRef` already does the right thing

File: src/js/components/TextInput/TextInput.js [hunk 3]
```diff
@@ -232,6 +252,9 @@ const TextInput = forwardRef(
       placeholder && typeof placeholder !== 'string' && !value;
 
     let drop;
+    const extraProps = {
```
Comment (ericsoderberghp) [inline src/js/components/TextInput/TextInput.js:255]: Why do we need this variable, since it's only used once, it would be cleaner to just have it inline: `onSelect={handleTextSelect.current}`

**Comment by ericsoderberghp** [comment]
> this issue has not been addressed yet
> 
> ericsoderberghp on May 26 Member
> The way these are being used seems like they should be using useMemo instead of useRef + useEffect.
> 
> IanKBovard 17 days ago Author Member
> I'm a little confused about this. My understanding of useMemo is to optimize the performance of complex functions. How can I use it to replace useRef and useEffect?

`useMemo` provides a simple way to create variables derived from props and state without having to repeat the logic to create them if they are used in multiple places. It's also similar to `useCallback`. I suggest it as we don't want the logic inline, as that will create new callbacks on each render, and the `useRef` approach seems like it takes more code.

**Comment by IanKBovard** [comment]
> `useMemo` provides a simple way to create variables derived from props and state without having to repeat the logic to create them if they are used in multiple places. It's also similar to `useCallback`. I suggest it as we don't want the logic inline, as that will create new callbacks on each render, and the `useRef` approach seems like it takes more code.

Thanks for that! Very clear, and easy to understand.

File: src/js/components/TextInput/TextInput.js (hunk 2 above)
Comment (IanKBovard) [reply src/js/components/TextInput/TextInput.js]: changes made

File: src/js/components/TextInput/TextInput.js (hunk 1 above)
Comment (IanKBovard) [reply src/js/components/TextInput/TextInput.js]: changes made

File: src/js/components/TextInput/TextInput.js (hunk 3 above)
Comment (IanKBovard) [reply src/js/components/TextInput/TextInput.js:245]: I had that initially, but this was added to keep the tests from updating.

File: src/js/components/TextInput/TextInput.js [hunk 4]
```diff
@@ -346,14 +359,14 @@ const TextInput = forwardRef(
...
-            if (activeSuggestionIndex >= 0 && onSelect) {
+            if (activeSuggestionIndex >= 0 && handleSuggestionSelect) {
               // prevent submitting forms when choosing a suggestion
               event.preventDefault();
               event.persist();
               const adjustedEvent = event;
               adjustedEvent.suggestion = suggestions[activeSuggestionIndex];
-              adjustedEvent.target = inputRef.current;
-              onSelect(adjustedEvent);
+              adjustedEvent.target = (ref || inputRef).current;
```
Comment (ericsoderberghp) [inline src/js/components/TextInput/TextInput.js:368]: This should just be `inputRef.current`.

Comment (IanKBovard) [reply src/js/components/TextInput/TextInput.js]: changes made
