### PR TITLE
Fix modal layer auto-focus bug - esc exit layer without Tab into layer first

### LINKED ISSUE #7564: Modal Layer doesn't seem to capture focus any more
Modal Layers used to capture focus when they opened, I think via the `FocusedContainer` component. Recently, I'm finding that keyboard focus doesn't move automatically to a modal layer when it opens. This, in turn, means that Esc to close an open layer doesn't seem to work any more.

To reproduce:

In the storybook visit either of these stories:
- https://storybook.grommet.io/?path=/story/layout-layer-corner--corner-layer
- https://storybook.grommet.io/?path=/story/layout-layer-center--center-layer

Click the button to open a modal popup, then press Esc to close it.

Tab then Esc does work, indicating that focus is initially outside the layer, until you tab into it.

Tested in the latest Firefox and Chrome on MacOS 14.7.

See also:
- https://github.com/zooniverse/front-end-monorepo/issues/6790
- https://github.com/zooniverse/front-end-monorepo/pull/6796

### PR DESCRIPTION
**Pull request by Sulaymon333**
#### What does this PR do?
- This is DRAFT PR to explore alternative solution to the issue #7564 
- Fix modal layer auto-focus issue - esc can now exit layer
- closes #7564 

#### How should this be manually tested?

In the storybook visit either of these stories:
- https://storybook.grommet.io/?path=/story/layout-layer-center--center-layer
- https://storybook.grommet.io/?path=/story/layout-layer-form--form-layer
- https://storybook.grommet.io/?path=/story/layout-layer-target--target-layer
- https://storybook.grommet.io/?path=/story/layout-layer-custom-themed-border-radius--round-layer&globals=theme:base
- Non modal - https://storybook.grommet.io/?path=/story/layout-layer-notification--notification-layer&globals=theme:base

- Click the button to open a modal popup, then press Esc to close it. It works!
- No need to Tab into Layer first, indicating that focus is initially INSIDE the layer, and no need to Tab into it first

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

### CODE REVIEW

File: src/js/components/Layer/LayerContainer.js [hunk 1]
```diff
@@ -79,16 +91,14 @@ const LayerContainer = forwardRef(
         }
       };
     }, [sendAnalytics, layerRef, position]);
-
     useEffect(() => {
-      if (position !== 'hidden') {
+      if (position !== 'hidden' && modal) {
         const node = layerRef.current || containerRef.current || ref.current;
         if (node && node.scrollIntoView) node.scrollIntoView();
```
Comment (taysea) [inline src/js/components/Layer/LayerContainer.js:101]: It feels like with how you've adjusted the condition that if something is non-modal, it won't scroll the layer into view if it's off screen. Is that intentional?

File: src/js/components/Layer/LayerContainer.js [hunk 2]
```diff
@@ -215,6 +211,7 @@ const LayerContainer = forwardRef(
         // or outside of the layer
         data-g-portal-id={portalId}
       >
+        <HiddenAnchor ref={anchorRef} tabIndex="-1" />
```
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/Layer/LayerContainer.js]: @Sulaymon333 did you check if the hiddenAnchor was invisible to screen reader in this case?

File: src/js/components/Layer/LayerContainer.js (hunk 1 above)
Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js:101]: Based on offline conversation, it is better to retain `scrollIntoView` logic for all layers since a layer target can be offscreen (which then can be accessed programmatically) and not limited to only modal layers.

File: src/js/components/Layer/LayerContainer.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js]: yes, it was invisible to screen reader. so we don't need the `aria-hidden`


https://github.com/user-attachments/assets/0d97df08-6095-47cd-ab3a-6a62784d5e7a

File: src/js/components/Layer/LayerContainer.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js]: this is resolved. we keep `scrollIntoView` for all layer types

File: src/js/components/Layer/LayerContainer.js [hunk 3]
```diff
@@ -5,24 +5,37 @@ import React, {
...
   backgroundIsDark,
   findVisibleParent,
   PortalContext,
+  styledComponentsConfig,
 } from '../../utils';
 
 import { StyledLayer, StyledContainer, StyledOverlay } from './StyledLayer';
 import { useThemeValue } from '../../utils/useThemeValue';
 
+const HiddenAnchor = styled.a.withConfig(styledComponentsConfig)`
```
[the remark this answers is not in the document]
Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js]: There was no announcement in screen reader

File: src/js/components/Layer/LayerContainer.js [hunk 4]
```diff
@@ -5,24 +5,37 @@ import React, {
...
+  width: 0;
+  height: 0;
+  overflow: hidden;
+  position: absolute;
+  clip: rect(0, 0, 0, 0);
```
Comment (britt6612) [inline src/js/components/Layer/LayerContainer.js]: can you look into using `  clip: rect(0, 0, 0, 0);` vs `clip-path`

File: src/js/components/Layer/LayerContainer.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/Layer/LayerContainer.js]: did you look into co pilots comment here changing the element?

File: src/js/components/Layer/LayerContainer.js (hunk 4 above)
Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js]: For extra DOM element, yes we do have an extra DOM element but the other approach focusing the container seems to be announcing the entire content.

For  `clip: rect(0, 0, 0, 0);` vs `clip-path`. Generally `clip-path` is more modern while `clip: rect(0, 0, 0, 0)` is [no longer recommended](https://developer.mozilla.org/en-US/docs/Web/CSS/clip). So, it is now replaced with `clip-path`.

I also changed anchor tag to a span and renamed the component to strike the best balance between clarity, brevity, and semantic intent.

PS. I noticed only `width: 0; height: 0;` works well enough in this case to hide the element from the UI but the extra styling might come in handy for edge cases that might arise.

image

File: src/js/components/Layer/LayerContainer.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js]: > yes, it was invisible to screen reader. so we don't need the `aria-hidden`
> 
>  layer.anchor.invisible.to.SR.mov

https://github.com/user-attachments/assets/b73c0434-c176-4c13-a081-4ff45670f35d

**Comment by Sulaymon333** [comment]
> did you look into co pilots comment here changing the element?

Yes I changed anchor tag to a span and renamed the component to strike the best balance between clarity, brevity, and semantic intent.

**Review by britt6612 — APPROVED** [review]

File: src/js/components/Layer/LayerContainer.js [hunk 5]
```diff
@@ -5,24 +5,41 @@ import React, {
...
 } from '../../utils';
 
 import { StyledLayer, StyledContainer, StyledOverlay } from './StyledLayer';
 import { useThemeValue } from '../../utils/useThemeValue';
 
+// The FocusAnchor ensures the LayerContainer has focus when
+// it is opened for user to start tabbing inside it.
+// It helps for escaping the LayerContainer using the keyboard.
+// It is hidden visually but still part of the accessibility tree.
+const FocusAnchor = styled.span.withConfig(styledComponentsConfig)`
```
Comment (taysea) [inline src/js/components/Layer/LayerContainer.js]: nit pick -- should we call this FocusSpan and focusSpanRef since it's a span?

Comment (britt6612) [reply src/js/components/Layer/LayerContainer.js]: good point ☝️

Comment (taysea) [reply src/js/components/Layer/LayerContainer.js]: To speed up reviews, I'll just push this change to the branch. The behavior looks good to me otherwise.

Comment (taysea) [reply src/js/components/Layer/LayerContainer.js]: Maybe in the naming, it was intended to meaning "This is the place the focus should anchor onto", but I think since it's a "span" let's just refer to is as that.

Comment (Sulaymon333) [reply src/js/components/Layer/LayerContainer.js]: Yes exactly, the intent for the naming is describe where the focus anchors to inside the layer. I think the confusion comes from the fact that standard web Anchor tag name is same.

Happy to change it to what bring more clarity for other developers.

File: src/js/components/Layer/LayerContainer.js [hunk 6]
```diff
@@ -79,16 +95,14 @@ const LayerContainer = forwardRef(
...
     useEffect(() => {
       if (position !== 'hidden') {
         const node = layerRef.current || containerRef.current || ref.current;
         if (node && node.scrollIntoView) node.scrollIntoView();
         // Once layer is open we make sure it has focus so that you
         // can start tabbing inside the layer. If the caller put focus
         // on an element already, we honor that. Otherwise, we put
-        // the focus within the layer. Look at FocusedContainer.js for
-        // more details.
+        // the focus in the hidden anchor.
```
Comment (jcfilben) [inline src/js/components/Layer/LayerContainer.js]: Should this say span instead of anchor
```suggestion
        // the focus on the hidden span.
```

Comment (jcfilben) [reply src/js/components/Layer/LayerContainer.js]: Going to go ahead and commit suggestion since it is just a commit change. Everything else looked good on the PR so after tests run I'll merge.

**Review by jcfilben — APPROVED** [review]
Looks good!
