### PR TITLE
fix anchor so if size is passed in prop

### LINKED ISSUE #5205: Custom sizes don't work with Anchor
### Expected Behavior

This should work fine, same as with `Text`:

```
<Anchor size="20px" label="link text" />
```

### Actual Behavior

Throws an error.

### URL, screen shot, or Codepen exhibiting the issue

Screen Shot 2021-05-01 at 9 52 44 AM
Screen Shot 2021-05-01 at 9 52 53 AM

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Firefox v88
- Operating System and version (desktop or mobile): MacOS

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
fixes string to be passed to `size`  in `anchor`
#### Where should the reviewer start?
anchor.js
#### What testing has been done on this PR?
added a test 
storybook
#### How should this be manually tested?
pass a string to `size`
#### What are the relevant issues?
closes #5205 
#### Do the grommet docs need to be updated?
no 
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/Anchor/__tests__/Anchor-test.js [hunk 1]
```diff
@@ -153,6 +153,7 @@ describe('Anchor', () => {
   test('size renders', () => {
     const component = renderer.create(
       <Grommet>
+        <Anchor size="10px" />
```
Comment (ShimiSun) [inline src/js/components/Anchor/__tests__/Anchor-test.js:156]: Can you add this new Anchor line at the end of the list of anchors so it won't impact all the snapshots of the following anchors?

Comment (britt6612) [reply src/js/components/Anchor/__tests__/Anchor-test.js:156]: yes! :)

**Comment by ShimiSun** [comment]
Updating to the master branch to remove clutter from Chromatic.

File: src/js/components/Anchor/StyledAnchor.js [hunk 2]
```diff
@@ -13,9 +13,15 @@ const sizeStyle = props => {
...
+      return css`
+        font-size: ${data.size};
+        line-height: ${data.height};
+      `;
+    }
     return css`
-      font-size: ${data.size};
-      line-height: ${data.height};
+      font-size: ${size};
+      line-height: normal;
```
Comment (ShimiSun) [inline src/js/components/Anchor/StyledAnchor.js:24]: How is this change backward compatible?

Comment (britt6612) [reply src/js/components/Anchor/StyledAnchor.js:24]: Orginally it was setting the `font-size` and `line-height` to the `data.size`  and the `data.height` but what I added was if `data` is not defined then it would set 
```
   font-size: ${size};
      line-height: normal;
```

`size` was never being set to anything before.. I was referencing the `text` size.
https://github.com/grommet/grommet/blob/master/src/js/components/Text/StyledText.js#L6

Comment (britt6612) [reply src/js/components/Anchor/StyledAnchor.js:24]: mabe instead of setting it to `data.size` we can check if data exists then set that or else set it to just `size`

File: src/js/components/Anchor/stories/Size.js [hunk 3]
```diff
@@ -11,6 +11,9 @@ const SizeAnchor = () => (
           <Anchor size={size} label={size} href="#" />
         </Box>
       ))}
+      <Box margin="small">
```
Comment (taysea) [inline src/js/components/Anchor/stories/Size.js:14]: Minor comment, but any reason not to just add `10px` as another index in the array at line 9?

Comment (britt6612) [reply src/js/components/Anchor/stories/Size.js]: good point!

**Review by taysea — APPROVED** [review]

**Review by ShimiSun — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]
