### PR TITLE
Button - Added justify prop for justification of content

### LINKED ISSUE #5542: Button - add support for justification of content
### Expected Behavior

Caller should have option to have icon + label left justified in the button as opposed to justify between / center.

### Actual Behavior

Justification of icon + label is decided by the Button itself. When used in Menu, if the Menu is wide the icon and label (supplied via array of objects to Menu) are justified in between each other.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/menu-justification-typ03

### Steps to Reproduce

Open Menu and observe justification of icon and label. No ability to justify it to the start.

### Your Environment

- Grommet version: Latest
- Browser Name and version: Mac Chrome
- Operating System and version (desktop or mobile): Mac OS Big Sur

### PR DESCRIPTION
**Pull request by g4rry420**
#### What does this PR do?
Added the `justify` prop so that it can support justification of button content specifically when a button contains a icon with it.

#### Where should the reviewer start?
components => Button.js, Menu.js

#### How should this be manually tested?
Added the stories in the `Nav` and `Menu` components.

#### Any background context you want to provide?
N/A

#### What are the relevant issues?
Closes #5542 

#### Do the grommet docs need to be updated?
Yes

#### Is this change backwards compatible or is it a breaking change?
Backwards Compatible

### CODE REVIEW

File: src/js/components/Button/Button.js [hunk 1]
```diff
@@ -274,7 +275,7 @@ const Button = forwardRef(
         <Box
           direction="row"
           align="center"
-          justify={align === 'center' ? 'center' : 'between'}
+          justify={justify}
```
Comment (jcfilben) [inline src/js/components/Button/Button.js:278]: For backwards compatibility maybe we could do something where if justify is not defined it defaults to `align === 'center' ? 'center' : 'between'`

File: src/js/components/Menu/stories/Justify.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+        items={[
+          { label: 'Hey', icon: <User />, justify: 'center' },
+          { label: 'Hello', icon: <User />, justify: 'end' },
+          { label: 'Hii', icon: <User /> },
+        ]}
+      />
+    </Box>
+  </Grommet>
+);
+
```
Comment (jcfilben) [inline src/js/components/Menu/stories/Justify.js:22]: I think we should disable this story from chromatic snapshot tests since the behavior we want to test is happening when you click on the menu button.
```suggestion
Justify.parameters = {
  chromatic: { disable: true },
};
```

**Review by jcfilben — APPROVED** [review]
Looks good to me!

**Comment by ericsoderberghp** [comment]
Looking good. Still need `propTypes.js` and `index.d.ts` changes.

**Review by ericsoderberghp — APPROVED** [review]
