### PR TITLE
Changed responsive to address breakpoint fix

### LINKED ISSUE #4196: Overwriting breakpoints in theme leads to malfunctions
WHEN adding custom breakpoints in `theme.global.breakpoints`,
THEN the two objects should be merged, with the custom ones overwriting the default values;
INSTEAD the `medium` breakpoint is NOT being overwritten
AND is still being resolved as the default, instead of the overwritten value.

### Expected Behavior
Custom breakpoints are resolved with both the provided value and the configuration, and the default values are being overwritten;

### Actual Behavior
`ResponsiveContext` resolves to `medium` on screen sizes that should provide custom breakpoint values; 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-breakpoints-14zbx

### Steps to Reproduce
1. Provide Grommet a theme with `global.breakpoints` that creates new breakpoints and overwrites existing ones (e.g.: `xsmall`, `small`, `medium`, `large`, `xlarge`)
2. Wrap your component in ResponsiveContext and log its result
3. Start resizing the window and see the logs

### Your Environment
- Grommet version: 2.14.0
- Browser Name and version: Chrome 83.0.4103.97
- Operating System and version (desktop or mobile): OSX Catalina 10.15.5, desktop

### PR DESCRIPTION
**Pull request by ShimiSun**
#### What does this PR do?
Changed responsive to address breakpoint fix along with splitting the stories of Responsive Context.

The current logic to resolve the size of the breakpoint is NOT because of a bad theme merge. The size defaults to medium once the value of the breakpoint is bigger than the window size (returned as undefined).
The last size i.e. the largest breakpoint should have no boundary of windowWidth, and the breakpoint should default to it.

#### Where should the reviewer start?
responsive.js
#### What testing has been done on this PR?
Storybook -> Responsive -> Custime Breakpoint story.
Jest.
#### How should this be manually tested?
Storybook -> Responsive -> Custime Breakpoint story.
#### What are the relevant issues?
#3212
Fixes #4196 
Might be related to #3161 
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
Yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible.

### CODE REVIEW

File: src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap [hunk 1]
```diff
@@ -265,7 +265,7 @@ exports[`Grommet ssr rendering Mozilla/5.0 (iPad; CPU OS 1`] = `
   <h1
     className="c1"
   >
-    Received size medium for Mozilla/5.0 (iPad; CPU OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C153 [FBAN/FBIOS;FBAV/156.0.0.41.97;FBBV/89172188;FBDV/iPad5,3;FBMD/iPad;FBSN/iOS;FBSV/11.2.1;FBSS/2;FBCR/;FBID/tablet;FBLC/en_GB;FBOP/5;FBRV/0]
+    Received size large for Mozilla/5.0 (iPad; CPU OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C153 [FBAN/FBIOS;FBAV/156.0.0.41.97;FBBV/89172188;FBDV/iPad5,3;FBMD/iPad;FBSN/iOS;FBSV/11.2.1;FBSS/2;FBCR/;FBID/tablet;FBLC/en_GB;FBOP/5;FBRV/0]
```
Comment (ericsoderberghp) [inline src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap:268]: Should these have changed?

Comment (ShimiSun) [reply src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap:268]: I agree it doesn't look right for the iPad to receive the `large` vs `medium` breakpoint. I'll have to take a deeper look into the SSR role and its impact on the logic. 
@oorestisime, any insights could be helpful here.

File: src/js/utils/responsive.js [hunk 2]
```diff
@@ -1,25 +1,32 @@
...
-        if (!breakpoint.value || breakpoint.value >= windowWidth) {
-          result = name;
-          return true;
-        }
+    },
+  );
+  const lastBreakpoint = sortedBreakpoints[sortedBreakpoints.length - 1];
+
+  sortedBreakpoints.some(name => {
+    const breakpoint = theme.global.breakpoints[name];
```
Comment (oorestisime) [inline src/js/utils/responsive.js:17]: I am not sure i understand what is going on here :/
what is lastBreakpoint and why we use this. Probably this is what lead to the snapshot changes?

I think this whole part is a bit confusing because we use array.some to not do anything here just set the result. maybe this was better as a filter? Do we need the last value?

Comment (ShimiSun) [reply src/js/utils/responsive.js:17]: The condition in line 22 `breakpoint.value >= windowWidth` requests the value of the breakpoint to be larger than the windowWidth.

Let's say the last breakpoint size is `xlarge: { value: 1000 }`, and the client is using a monitor that has 2000 of windowWidth, our logic, in that case, should be to return the `xlarge` size, but instead we are returning `undefined` (due to `breakpoint.value >= windowWidth` returns `false`) that eventually default the breakpoint to be `medium`.
I think the last breakpoint should have no boundary with its value, and that is what this PR is suggesting. I'm not sure how it impacts the SSR tests and wanted your inputs.

**Comment by oorestisime** [comment]
So i might have understood why snapshots are failing. i haven't really tested my assumption but here it is:

we were relying on getting an undefined on the first run of https://github.com/grommet/grommet/blob/master/src/js/components/Grommet/Grommet.js#L90

because at that point we were enterring this part https://github.com/grommet/grommet/blob/master/src/js/components/Grommet/Grommet.js#L138 and hence taking the user agent endpoint.

Now that getBreakpoint was changed to always return something then on mount we already get the large endpoint and we don't really execute the get device breakpoint with the user agent anymore.

What we could do to fix is call the deviceBreakpoint here https://github.com/grommet/grommet/blob/master/src/js/components/Grommet/Grommet.js#L90 if we don't have the responsive state variable set. that way on mount (on SSR) it will take the user agent breakpoint. 

 Hope this helps

**Comment by ShimiSun** [comment]
Thank you for the findings @oorestisime ! 
I've incorporated your feedback along with additional fine-tuning for breakpoint calculation on the initial first load, and both the jest-snapshots and Chromatic are happy with the updates.
