### PR TITLE
Don't let Layer elevation leak to DOM, don't apply elevation when plain

### LINKED ISSUE #5129: Layer with plain set now produces elevation shadow
A Layer with the `plain` property set now puts a box shadow on its container div and the `elevation` property on the container is leaking through to the `<div>` in the DOM.

### Expected Behavior

The plain property should result in no extra border or elevation on the layer.

### Actual Behavior

`<Layer plain>` results in:

image

### URL, screen shot, or Codepen exhibiting the issue

image

### Steps to Reproduce

 ```
<Layer
        position="bottom"
        modal={false}
        margin={{ vertical: 'medium', horizontal: 'small' }}
        responsive={false}
        plain
  >
       <Text> example layer </Text>
  </Layer>
```
### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?
Checks if Layer is plain before applying elevation. Also, used styled-components `withConfig` to ensure that the elevation prop doesn't leak to the DOM.

#### Where should the reviewer start?
src/js/components/Layer/StyledLayer.js

#### What testing has been done on this PR?
Tested with this code snippet, no elevation was applied. Updated jest test.

```
<Layer
       position="bottom"
       modal={false}
       margin={{ vertical: 'medium', horizontal: 'small' }}
       responsive={false}
       plain
 >
      <Text> example layer </Text>
 </Layer>
```

#### How should this be manually tested?
With code snippet above, make a theme that has a value for `theme.layer.container.elevation`.

#### What are the relevant issues?
Closes #5129 

#### Do the grommet docs need to be updated?
Updated here to clarify that Layer `plain` will not apply elevation.

#### Should this PR be mentioned in the release notes?
Fixed Layer elevation styling, should not apply when plain.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Review by MikeKingdom — COMMENTED** [review]
Awesome. Thanks Taylor!

File: src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap [hunk 1]
```diff
@@ -1005,7 +1005,6 @@ exports[`Layer custom theme 1`] = `
   <div
     class="c2"
     data-g-portal-id="0"
-    elevation="large"
```
Comment (ShimiSun) [inline src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap:1008]: Is this line removal from snapshot due to using Layer `plain` on the test?

**Review by ShimiSun — COMMENTED** [review]
Does this PR fixes a regression or was it always working this way?

File: src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap (hunk 1 above)
Comment (taysea) [reply src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap:1008]: This line removal is due to an existing behavior where elevation was leaking to the DOM but shouldn't.

We did not have an existing test with elevation + plain combination. I can add one to this PR for future.

Comment (taysea) [reply src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap:1008]: Done.

**Review by ShimiSun — APPROVED** [review]
Perfect! Thanks!
