### PR TITLE
Data Array Enhancement

### LINKED ISSUE #6701: Data Enhancement with Array
### Expected Behavior
On properties that contain array values, `Data` should:
1. recognize array
2. do matching for values **inside** the array, not try to match the filter's value to the array object directly

image
Ex: Filtering on the "Categories" object above, selecting "Machine learning" OR "Developer tools" should cause this object to be returned when filtering.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by JCoder121**
[Complex Story Deploy Preview](https://deploy-preview-6704--sad-tereshkova-173d07.netlify.app/?path=/story/data-data-complex--complex)

#### What does this PR do?
Add functionality to Data's `filter()` for when a property is a `list`, rather than a `string`, `bool`, or nested object. Allow the user to select filter values that filter upon list objects.

#### Where should the reviewer start?
src/js/components/Data/filter.js
src/js/components/Data/stories/Complex.js

#### What testing has been done on this PR?
Manual and visual testing to ensure filtering upon list elements works as intended.

#### How should this be manually tested?
Check that existing filtering works as expected in addition to the new list filtering capabilities.

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #6701

#### Do the grommet docs need to be updated?
Yes - update after initial code review to include example case.

### CODE REVIEW

File: src/js/components/Data/filter.js [hunk 1]
```diff
@@ -60,10 +60,19 @@ export const filter = (data, view, properties) => {
           );
 
         // options case
-        if (Array.isArray(filterValue)) return !filterValue.includes(value);
+        if (Array.isArray(filterValue)) {
+          // value is array case
+          if (Array.isArray(value))
+            // from https://stackoverflow.com/a/39893636
```
Comment (taysea) [inline src/js/components/Data/filter.js:66]:
```suggestion
```
It is fine to use the `.some` without referencing the stack overflow source since it's a generic method.

File: src/js/components/Data/filter.js [hunk 2]
```diff
@@ -60,10 +60,19 @@ export const filter = (data, view, properties) => {
           );
 
         // options case
-        if (Array.isArray(filterValue)) return !filterValue.includes(value);
+        if (Array.isArray(filterValue)) {
```
Comment (taysea) [inline src/js/components/Data/filter.js:63]: Can we simplify format to:
```
if (Array.isArray(filterValue)) return Array.isArray(value) ? !value.some((v) => filterValue.includes(v)) : !filterValue.includes(value);
```

File: yarn.lock [hunk 3]
```diff
@@ -1280,16 +1280,16 @@
   integrity sha512-OWORNpfjMsSSUBVrRBVGECkhWcULOAJz9ZW8uK9qgxD+87M7jHRcvh/A96XXNhXTLmKcoYSQtBEX7lHMO7YRwg==
 
 "@eslint-community/eslint-utils@^4.2.0":
-  version "4.3.0"
-  resolved "https://registry.yarnpkg.com/@eslint-community/eslint-utils/-/eslint-utils-4.3.0.tgz#a556790523a351b4e47e9d385f47265eaaf9780a"
-  integrity sha512-v3oplH6FYCULtFuCeqyuTd9D2WKO937Dxdq+GmHOLL72TTRriLxz2VLlNfkZRsvj6PKnOPAtuT6dwrs/pA5DvA==
+  version "4.4.0"
```
Comment (taysea) [inline yarn.lock:1283]: For PRs on grommet, we don't want to adjust the yarn.lock. Can you undo the changes here?

**Review by taysea — COMMENTED** [review]
Functionality looks good! Couple small cleanup comments.

File: src/js/components/Data/filter.js (hunk 1 above)
Comment (JCoder121) [reply src/js/components/Data/filter.js:66]: Originally included it because it was the exact code needed to directly solve the issue.

File: src/js/components/Data/stories/Complex.js [hunk 4]
```diff
@@ -10,19 +10,32 @@ const data = [
...
+    colors: ['Red', 'Yellow', 'Black'],
   },
 ];
 
 const properties = {
   name: { label: 'Name', search: true },
   'location.city': { label: 'City' },
   'economy.GDP': { label: 'GDP' },
+  colors: {
+    label: 'Flag Colors',
```
Comment (taysea) [inline src/js/components/Data/stories/Complex.js:36]:
```suggestion
    label: 'Flag colors',
```
sentence casing to align with DataTable column header/best practices.

**Comment by ericsoderberghp** [comment]
Screenshot 2023-03-24 at 12 21 52 PM

Something looks off with the vertical alignment here. I don't think this is related to the changes in this pull request but wondering if you can take a quick look.

**Comment by ericsoderberghp** [comment]
Can you enhance the story so that searching matches on the color names, in addition to the filtering?

**Comment by ericsoderberghp** [comment]
I think we should consider using `verticalAlign` for the columns to align them to the top instead of centering the cell contents.

**Comment by JCoder121** [comment]
> Screenshot 2023-03-24 at 12 21 52 PM
> 
> Something looks off with the vertical alignment here. I don't think this is related to the changes in this pull request but wondering if you can take a quick look.

image
This screenshot is from the Views story [here](https://storybook.grommet.io/?path=/story/data-data-views--views). It's looking like whenever the `Clear Filters` button is inserted in the toolbar, it isn't centered inside its parent Box (maybe aligned to start?). Additionally, when tabbing through the controls, the Filter button's focus indicator box seems to be very slightly larger than the DataSearch component (and in this case the Select component as well).

**Review by ericsoderberghp — APPROVED** [review]
