### PR TITLE
RangeSelector - add hidden input for safari screen reader

### LINKED ISSUE #7027: RangeSelector - screenreader issues
### Expected Behavior
When navigating with a keyboard and using a screenreader the screenreader should read out the value of the RangeSelector as it changes.

### Actual Behavior
Instead the screenreader reads out the previous value when the RangeSelector changes.

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/input-rangeselector-label--label

### Steps to Reproduce

1. Go to the story above
2. Using a screenreader and keyboard change the value of the RangeSelector

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR adds a `hiddenInput` in which provides the native range semantics that Safari voice over needs in order to announce slider values. 
#### Where should the reviewer start?
edgeControl.js
#### What testing has been done on this PR?
local stories 
#### How should this be manually tested?
local stories in Safari
#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
Safari has voiceover limitation. Safari has specific requirements for recognizing slider controls. It need the native `<input type="range">` to properly announce. 

The input is marked as `readOnly` to prevent interference with existing interaction logic so this input does not trigger the `onChange` that could interfere with the existing `onIncrease` and `onDecrease` logic 

The `aria-label` is moved now to the hiddenInput since that is what is used for the screen reader experience. The aria roles were taken off from the edgeControl since that control is just primary now used for the mouse interactions. 
#### What are the relevant issues?
closes #7027 
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: src/js/components/RangeSelector/EdgeControl.js [hunk 1]
```diff
@@ -93,6 +117,19 @@ const EdgeControl = forwardRef(
           justify="center"
           alignSelf="stretch"
         >
+          {/* Add visually hidden range input for Safari VoiceOver */}
+          <VisuallyHiddenInput
```
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js:123]: good point here thinking if we use the same message from RangeSelector aria-label
@taysea @jcfilben thoughts?

[the remark this answers is not in the document]
Comment (taysea) [reply src/js/components/RangeSelector/EdgeControl.js:123]: I like the existing wording of "Lower bounds", "Upper bounds" -- can we stick with that? key off of `edge` for which one?

File: src/js/components/RangeSelector/EdgeControl.js [hunk 2]
```diff
@@ -107,7 +144,7 @@ const EdgeControl = forwardRef(
               minHeight: size,
               zIndex: 1,
             }}
-            tabIndex={0}
+            tabIndex={-1} // Remove from tab order
             onFocus={() => setFocus(true)}
```
Comment (taysea) [inline src/js/components/RangeSelector/EdgeControl.js]: If this now has tabIndex -1, does it need onFocus/onBlur?

Comment (taysea) [reply src/js/components/RangeSelector/EdgeControl.js]: Also how is the focus styling still going around the edge control even though the input has focus? just making sure I understand

Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: yes we still want the `onFocus` `onBlur`

Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: The `hiddenInput` is what gains the browser focus, but since the `onFocus` is called the `focus` state becomes true since this is true the styles then are applied on the StyledBox so we visually see the focus styles. 

So the thing that changed it that the `hiddenInput` is the focus target but the user will still see the focus style on the visible handle because of the StyledBox.

Comment (jcfilben) [reply src/js/components/RangeSelector/EdgeControl.js]: So the `onFocus` still gets called even though the Box isn't in the tabindex?

Comment (jcfilben) [reply src/js/components/RangeSelector/EdgeControl.js]: Still a little confused I guess, why do we have `onFocus` and `onBlur` on both this Box and the `VisuallyHiddenInput`?

**Review by jcfilben — COMMENTED** [review]
Tested in safari, chrome, and firefox and screenreader behavior looks good! Just have some questions on the code (see thread above)

File: src/js/components/RangeSelector/EdgeControl.js (hunk 2 above)
Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: Sorry for the confusion — I was referring to the `StyledBox` that has the focus styling. But @taysea , you’re correct — we no longer need the `onFocus` and `onBlur` on the Box with tabIndex={-1} since it’s no longer the element that gains focus. The `onFocus` and `onBlur` now only on the VisuallyHiddenInput. The hidden input is what actually receives browser focus, and when that happens, we set the focus state to true, which gets passed as focus={true} to the StyledBox to apply the visible focus styles on the handle.

File: src/js/components/RangeSelector/EdgeControl.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (jcfilben) [reply src/js/components/RangeSelector/EdgeControl.js:123]: @britt6612 looks like the aria-label is still "slider control", do we want to go ahead and change it to "Lower bounds" or "Upper bounds". Also we should allow for internationalization here

File: src/js/components/RangeSelector/RangeSelector.js [hunk 3]
```diff
@@ -331,16 +328,14 @@ const RangeSelector = forwardRef(
...
-          role="slider"
-          aria-valuenow={upper}
-          aria-valuemin={min}
-          aria-valuemax={max}
-          tabIndex={0}
           color={color}
           direction={direction}
           thickness={thickness}
           edge="upper"
+          min={min}
```
[the remark this answers is not in the document]
Comment (britt6612) [reply src/js/components/RangeSelector/RangeSelector.js:335]: Im only passing the `messages` prop once because in the edgeControl.js Im checking to see which message is lower and upper 

```
     aria-label={format({
              id:
                edge === 'lower'
                  ? 'rangeSelector.lower'
                  : 'rangeSelector.upper',
              messages,
            })}
```

File: src/js/components/RangeSelector/EdgeControl.js [hunk 4]
```diff
@@ -93,6 +119,29 @@ const EdgeControl = forwardRef(
           justify="center"
           alignSelf="stretch"
         >
+          {/* Add visually hidden range input for Safari VoiceOver */}
+          <VisuallyHiddenInput
+            type="range"
+            role="slider"
```
Comment (jcfilben) [inline src/js/components/RangeSelector/EdgeControl.js]: Do we need both `type="range"` and `role="slider"`, from a quick google search it seems like one or the other should be used

Comment (britt6612) [reply src/js/components/RangeSelector/EdgeControl.js]: yes you are correct thank you removed `role="slider"` since we need the `type="range"` for Safari voice over!

**Review by jcfilben — APPROVED** [review]
Looks good!
