### PR TITLE
Select — Add `theme.select.clear.container.hover`

### LINKED ISSUE #7342: Select -- add `theme.select.clear.hover
### Expected Behavior

Should be able to theme the hover styling of the "Clear selection" button in Select.

### Actual Behavior

No theme object.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

Adds ability for caller to define hover styling for Clear selection container.

Adds `plain` to Button to maintain previous "plain" functionality of the Button once we switch into the function notation.

#### Where should the reviewer start?
src/js/components/Select/SelectContainer.js

#### What testing has been done on this PR?
Local in storybook and test added:

https://github.com/user-attachments/assets/e0d2c671-0099-4ded-aa2b-3f499d0ad075

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #7342 

#### Do the grommet docs need to be updated?
Yes.

#### Should this PR be mentioned in the release notes?
Yes.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Review by halocline — APPROVED** [review]

File: src/js/components/Select/SelectContainer.js [hunk 1]
```diff
@@ -51,12 +51,19 @@ const ClearButton = forwardRef(
...
+        plain
         {...passThemeFlag}
         {...rest}
       >
-        <Box {...theme.select.clear.container} align={align}>
-          <Text {...theme.select.clear.text}>{buttonLabel}</Text>
-        </Box>
+        {({ hover }) => (
+          <Box
+            {...theme.select.clear.container}
```
Comment (MikeKingdom) [inline src/js/components/Select/SelectContainer.js:60]: Won't this accidentally put a `hover=[object, object]` on the Box?

Comment (MikeKingdom) [reply src/js/components/Select/SelectContainer.js:60]: image

Comment (taysea) [reply src/js/components/Select/SelectContainer.js]: It wasn't passing it to the DOM so originally I was okay with that, but I've added one more step to avoid it being passed in React props as well:

Screenshot 2024-10-24 at 2 22 42 PM

**Review by MikeKingdom — APPROVED** [review]
Thanks!
