### PR TITLE
Fix: TextInput suggestions closing incorrectly

### LINKED ISSUE #5426: TextInput suggestions dropdown issue
Hi, i use the Textinput with suggestions from api calls. 
As my limit of results is always 5, the dropdown is not opening after i doubleclick inside to remove the value and type something new. I figured out that there is this suggestionsAtClose check, which might be the reason for this. 
```
if (focus && !showDrop && suggestions && suggestions.length && (!suggestionsAtClose || suggestionsAtClose.length !== suggestions.length)) {
      openDrop();
    }
```

You can also see the issue in the storybook : 
https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion

- type in sug, the dropdown is open
- double click inside and delete
- type again sug => no dropdown opens anymore.
=> You need to click outside and click inside again to make it work.

I am using the latest grommet version 2.17.3

### LINKED ISSUE #5440: TextInput with suggestions Drop will close when TextInput is re-selected
There is a bug when using a TextInput with a suggestions Drop. If the user clicks on the TextInput field to show the suggestions, a 2nd click of the TextInput will close the suggestions. The 2nd mouse click triggers the Drops onClickOutside() event, which subsequently closes the suggestions.

Use case: The user selects the TextInput to start a search, but then tries to move their cursor via a mouse click.

### Expected Behavior

TextInput suggestions should stay open as long as the TextInput has focus.

### Actual Behavior

TextInput suggestions show up on initial click when receiving focus; however, re-selecting the TextField causes suggestions to close despite the TextField never loosing focus.

### Examples

The [Grommet Default Suggestion story](https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion) and [Grommet Custom Suggestion story](https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions) serve as a nice starting point
for demonstrating the issue.

- https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion
- https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions

### Steps to Reproduce

1. navigate to one of the examples above
1. click on TextInput and type "a" to show names
1. click TextInput a 2nd time
1. notice suggestions have closed

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: All browsers (using Chrome)
- Operating System and version (desktop or mobile): All systems, using OSX

### LINKED ISSUE #5790: TextInput suggestions drop does not respect user input
### Expected Behavior

Use the TextInput for searching stuff:

1. type `a`
2. the suggestions drop opens with
```
all are great!
all are great?
```
3. you select one of them with your keyboard
4. the drop closes but you are still focused on the input.
5. you backspace and remove the punctuation character in the end
6. should show the 2 same suggestions again

### Actual Behavior

you use the TextInput for searching stuff:

1. type `a`
2. the suggestions drop opens with
```
all are great!
all are great?
```
3. you select one of them with your keyboard
4. the drop closes but you are still focused on the input.
5. you backspace and remove the punctuation character in the end
6. nothing happens because when you selected there were 2 suggestions and again now there are 2 suggestions

### URL, screen shot, or Codepen exhibiting the issue

[This](https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions) for example: Type `alan` -> one suggestion comes up -> focus again, select the text and just replace it with `j`, drop won't open even though the suggestion (again just one) is completely different.

### Steps to Reproduce

Check above

### Your Environment

- Grommet version: 2.18.0
- Browser Name and version: Chrome Version 94.0.4606.81 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): MacOS Big Sur 11.6 desktop

p.s. I tried to fix that [here](https://github.com/grommet/grommet/pull/5625) by adding a test showing the issue and the solution, but it's not acceptable, so since this is a blocker for me and as I could see for other people as well (i.e. [5426](https://github.com/grommet/grommet/issues/5426)) could we find a solution? Thank you

### PR DESCRIPTION
**Pull request by jlaluces123**
#### What does this PR do?
This PR addresses issues with the TextInput suggestion dropdown closing and suggestions not reappearing upon further user input or after regaining focus.

#### Where should the reviewer start?
- Changes made in `TextInput.js`

#### What testing has been done on this PR?
Manual testing with a focus on TextInput suggestion behavior after losing / regaining focus through various methods

#### How should this be manually tested?
- Example given with the `TextInput/Default suggestion` story

Part 1:
- Type in sug, the dropdown is open
- Double click inside and delete
- Type again sug --> dropdown remains open after deletion and is ready to scan for new suggestions

Part 2:
- Type in sug, dropdown opens
- Click on the TextInput box --> dropdown remains open after the click and is still actively listening for suggestions

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
- Resolves #5426
- Resolves #5440
- Resolves #5790 

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
Can be included for TextInput fixes

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

File: src/js/components/TextInput/TextInput.js [hunk 1]
```diff
@@ -313,7 +316,14 @@ const TextInput = forwardRef(
...
           target={dropTarget || inputRef.current}
-          onClickOutside={closeDrop}
+          onClickOutside={({ target }) => {
+            if (
+              target !== containerRef.current &&
+              !containerRef.current.contains(target)
+            ) {
+              closeDrop();
+            }
+          }}
```
Comment (jcfilben) [inline src/js/components/TextInput/TextInput.js:326]:
```suggestion
          onClickOutside={({ target }) => {
            if (target !== inputRef.current) {
              closeDrop();
            }
          }}
```

**Comment by jcfilben** [comment]
I believe this also fixes this issue https://github.com/grommet/grommet/issues/5790 (I added to the PR description that this PR resolves it)

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by ericsoderberghp — APPROVED** [review]
