### PR TITLE
Use &:focus to drive button focus

### LINKED ISSUE #4389: Multiple buttons can have focus at a time
image

The first button disables itself
The second button enables the first.

1) Click the first
2) Click the second
3) Notice both are active and focused.

https://codesandbox.io/s/youthful-cartwright-hj28u?initialpath=/text&module=%2Fsrc%2FText.js

### LINKED ISSUE #4393: Button focus style gets "stuck" when disabled while focused
As the title says, Buttons have an issue when they are disabled while focused that causes them to retain the focus styling.

### Expected Behavior

The focus styling should either clear when the button is disabled, or at least when another element subsequently takes focus.

### Actual Behavior

The focus styling remains stuck on the button even after a new element takes focus.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/pensive-shirley-ebrt9?file=/src/Home.js

### Steps to Reproduce

See Code sandbox. Click a button, wait for the buttons to disable and re-enable. Click other button.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 Desktop

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

This PR updates what triggers hover styling on Button. Previously, we were internally tracking `focus` via a prop. However, in recent grommet changes we are pushing to rely on css :hover, :focus, etc. as was implemented recently for [List](https://github.com/grommet/grommet/pull/4364).

#### Where should the reviewer start?
src/js/components/Button/StyledButton.js

#### What testing has been done on this PR?
Replicated this use case and confirmed that the double focus was not possible: https://codesandbox.io/s/youthful-cartwright-hj28u?initialpath=/text&module=%2Fsrc%2FText.js

Additionally, engaged with the components in the affected snapshots that rely on button to ensure that were no changes.

#### How should this be manually tested?
Use tab to focus on button.

#### What are the relevant issues?
Closes #4389 
Closes #4393 
Related to https://github.com/hpe-design/design-system/issues/1051

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
No.

#### Is this change backwards compatible or is it a breaking change?
Yes, this is backwards compatible.

### CODE REVIEW

File: src/js/components/Button/StyledButton.js [hunk 1]
```diff
@@ -206,8 +206,11 @@ const StyledButton = styled.button`
     props.theme.button &&
     props.theme.button.disabled &&
     disabledButtonStyle(props)}
-  ${props =>
-    props.focus && (!props.plain || props.focusIndicator) && focusStyle()}
+  
+  &:focus {
+    ${props => (!props.plain || props.focusIndicator) && focusStyle()}
+  }
```
Comment (ShimiSun) [inline src/js/components/Button/StyledButton.js:212]: Interesting, I thought the problem isn't reproducing on the regular Button.

Comment (taysea) [reply src/js/components/Button/StyledButton.js:212]: It is occurring on both, just confirmed locally
