### PR TITLE
Reset DateInput textValue on form reset

### LINKED ISSUE #6818: DateInput in uncontrolled form - form reset - ui not reseted
Using the DateInput component in an uncontrolled form, does not reset the UI (but the value) on reset of the form.

### Expected Behavior

After form reset event the DateInput should show the placeholder or format again (same as if value is undefined). The value is set correctly to undefined.

### Actual Behavior

Date is still displayed instead of placeholder or format and value is undefined as expected.

### URL, screen shot, or Codepen exhibiting the issue

```JS
<Form
  onChange={(value) => {console.log(JSON.stringify(value))}}
>
  <DateInput
    format="mm/dd/yyyy"
    name="date"
  />
  <TextInput name="text" />
  <Button label="clear" type="reset" />
</Form>
```
I just wrote the code in the DateInput documentation. https://v2.grommet.io/dateinput
You can just copy it there.

### Steps to Reproduce
1. Open a console, because output will be logged there.
2. Select a date in the date picker
3. Write a text in the TextInput
4. Check the console, you will see the form value like:
  - {"date":"2023-05-16T22:00:00.000Z"}
  - {"date":"2023-05-16T22:00:00.000Z","text":"123"}
5. Now click the reset button
6. Check the console, it will show an empty object: {}
7. TextInput will be empty, but DateInput still shows the date.

### Your Environment
- Grommet version:  "^2.29.0",
- Browser Name and version: Firefox 113.0.2 (64-bit) (Windows), but also occurs for colleauges
- Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?
The MaskedInput inside of DateInput is controlled. Therefore, in an uncontrolled form, when the form is reset, the text value in the DateInput isn't. This PR updates DateInput to listen for the `reset` event to reset the textValue.

#### Where should the reviewer start?
src/js/components/DateInput/DateInput.js

#### What testing has been done on this PR?
Tested with code snippet provided in #6818 

Also tested with:

```
import React from 'react';

import { DateInput, Form, TextInput, Button } from 'grommet';

export const Simple = () => (
  <>
    <Form
      onChange={(value) => {
        console.log(JSON.stringify(value));
      }}
      onReset={(e) => {
        console.log('my reset');
        e.stopPropagation();
      }}
    >
      <DateInput format="mm/dd/yyyy" name="date" />
      <TextInput name="text" />
      <Button label="clear" type="reset" />
    </Form>

    <Form
      onChange={(value) => {
        console.log(JSON.stringify(value));
      }}
    >
      <DateInput format="mm/dd/yyyy" name="date-2" />
      <TextInput name="text-2" />
      <Button label="clear" type="reset" />
    </Form>
  </>
);

Simple.parameters = {
  chromatic: { disable: true },
};

export default {
  title: 'Input/DateInput/Simple',
};

```
Added jest test.

#### Do Jest tests follow these best practices?

- [x] `screen` is used for querying.
- [x] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [x] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #6818 

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
Yes. Fixed bug where DateInput text value did not reset with Form reset.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Comment by taysea** [comment]
Converted to draft -- this is a little too generic where any reset event is clearing the field (should be isolated to the form)

**Comment by taysea** [comment]
This is ready for review again, I've added a check to make sure the DateInput is part of the form that was reset.

**Review by jcfilben — APPROVED** [review]
Looks good! Thanks for adding a test

File: src/js/components/DateInput/DateInput.js [hunk 1]
```diff
@@ -149,6 +149,20 @@ Use the icon prop instead.`,
...
+    // resets the textValue
+    useEffect(() => {
+      const handleFormReset = (e) => {
+        if (schema && ref.current && e.target.contains(ref.current)) {
+          setTextValue('');
+        }
+      };
+
+      window.addEventListener('reset', handleFormReset);
+      return () => window.removeEventListener('reset', handleFormReset);
```
Comment (MikeKingdom) [inline src/js/components/DateInput/DateInput.js:163]: It's a bit of a corner case, but because this expects the event to bubble up, if the Form's onReset stops the event propagation this won't get called. For example I broke this with:
```jsx
<Form onReset={(e) => {
  console.log('MyReset');
  e.stopPropagation();
}}>
```

Comment (taysea) [reply src/js/components/DateInput/DateInput.js:163]: Hmm -- that's a good note, even if a corner case. I was trying to just rely on native HTML events, but I suppose one option would be to fire a custom event within form. and listen for that within DateInput?

Comment (taysea) [reply src/js/components/DateInput/DateInput.js]: I adjusted the scope of the event listener to be placed on the form as opposed to the window. I checked with the code you shared (with custom reset function) and it worked.

File: src/js/components/DateInput/DateInput.js [hunk 2]
```diff
@@ -149,6 +149,23 @@ Use the icon prop instead.`,
       }
     }, [range, schema, textValue, reference, value]);
 
+    // textValue of MaskedInput is controlled.
+    // for uncontrolled forms, ensure the reset event
+    // resets the textValue
+    useEffect(() => {
+      const form = ref?.current.form;
```
Comment (taysea) [inline src/js/components/DateInput/DateInput.js:156]:
```suggestion
      const form = ref?.current?.form;
```

File: src/js/components/DateInput/DateInput.js [hunk 3]
```diff
@@ -149,6 +149,23 @@ Use the icon prop instead.`,
...
+    // resets the textValue
+    useEffect(() => {
+      const form = ref?.current?.form;
+      const handleFormReset = (e) => {
+        if (schema && ref.current && e.target.contains(ref.current)) {
+          setTextValue('');
+        }
+      };
+      // place the listener on the form directly. if listener is on window,
+      // the event could get blocked if caller has e.stopPropogation(), etc. in
```
Comment (taysea) [inline src/js/components/DateInput/DateInput.js:163]:
```suggestion
      // the event could get blocked if caller has e.stopPropagation(), etc. in
```

**Review by MikeKingdom — APPROVED** [review]
Coolness. Thanks!
