### PR TITLE
Enforce readonly on range calendar when missing onSelect

### LINKED ISSUE #7720: Calendar — `range` without `onSelect` shouldn't change value
### Is this something you or your team is interested in contributing a pull request towards?

None

### Expected Behavior

If Calendar doesn't have `onSelect`, it should be read only: https://v2.grommet.io/calendar#onSelect

### Actual Behavior

Right now, for single dates this behaves as expected. However, for `range` cases, the value still updates: https://storybook.grommet.io/?path=/story/visualizations-calendar-range--range

### URL, Screenshot, or CodeSandbox

_No response_

### Steps to Reproduce

1. Go to story
2. Click on calendar day
3. See how range changes

### Your Environment

_No response_

### PR DESCRIPTION
**Pull request by NOMADE55**
#### What does this PR do?
Prevents the use of the calendar when no `onSelect` function was passed as prop.

#### Where should the reviewer start?
- [src/js/components/Calendar/Calendar.js](https://github.com/grommet/grommet/blob/d4519a42e4423dd88ed838ea2d999ce197d1b582/src/js/components/Calendar/Calendar.js#L229)

#### What testing has been done on this PR?
- Tested on Storybook
- Tested on a dummy project

#### How should this be manually tested?
1. Create a range calendar component
2. onSelect should be undefined or not set.
3. Calendar should be 'read only'

#### What are the relevant issues?
- Fixes #7720

### CODE REVIEW

File: src/js/components/Calendar/Calendar.js [hunk 1]
```diff
@@ -876,10 +876,16 @@ const Calendar = forwardRef(
               day={day}
               key={day.getTime()}
               disabledProp={dayDisabled}
-              buttonProps={{
-                a11yTitle: day.toDateString(),
-                onClick: dayDisabled ? () => {} : () => onClick(dateObject),
-              }}
+              buttonProps={
```
Comment (britt6612) [inline src/js/components/Calendar/Calendar.js]: @NOMADE55 

Lets update the selectDate function above to prevent state changes:

```
const selectDate = useCallback(
  (selectedDate) => {
    // If no onSelect prop is provided, the calendar should be read-only
    if (!onSelect) return;
    
    let nextValue;

    if (range || Array.isArray(value?.[0])) {
      nextValue = handleRange(selectedDate);
    } else {
      nextValue = selectedDate;
    }

    nextValue = normalizeOutput(nextValue, outputFormat);
    onSelect(nextValue);
  },
  [handleRange, onSelect, outputFormat, range, value],
);
```

**Comment by britt6612** [comment]
> Hello, thank you for working on this. The changes looks good to me.
> 
> The only thing I notice is that the aria-labels are missing on the buttons from the snapshot.
> 
> @jcfilben @britt6612 is this an expected change?

I left one comment as well but I think the `aria-label` should always be there

maybe we can do 

```
buttonProps={{
  a11yTitle: day.toDateString(),
  ...(onSelect && !dayDisabled && { onClick: () => onClick(dateObject) }),
}}
```

**Comment by NOMADE55** [comment]
Got it @britt6612 , @Sulaymon333.

On the aria topic, there is another ticket which has an open PR https://github.com/grommet/grommet/issues/7721 regarding `aria-disabled`.

Want this PR to also address that issue?

**Comment by britt6612** [comment]
@NOMADE55 you are correct we can take a look at that PR separate then do not worry about it in here.

**Comment by britt6612** [comment]
@NOMADE55 PR looks good I need to look at why the test is failing on https://app.circleci.com/jobs/github/grommet/grommet/90599

@jcfilben ideas?

**Comment by jcfilben** [comment]
Thanks for working on this! A few thoughts here...

If we want the component to be 'readonly' if someone doesn't pass `onSelect` then it seems like we should use the readonly and aria-readonly attributes to indicate to screenreader users that this component is not interactive.

In the original ticket it says "If Calendar doesn't have onSelect, it should be read only... Right now, for single dates this behaves as expected. However, for range cases, the value still updates". However this doesn't seem to always be the case, in this storybook example we have a single select calendar where we do not pass `onSelect`, but the Calendar is not read only and is still interactive.
https://storybook.grommet.io/?path=/story/visualizations-calendar-custom-day--custom-day-calendar

@grommet/devs We should align on the desired behavior here to ensure we don't break existing functionality and move in a direction that feels correct for the long term. Ideally I think that `readonly` should be a separate prop. Not passing `onSelect` shouldn't necessarily default you to read only mode. Open to other thoughts on this though/

Our current documentation for the prop does say that not passing `onSelect` should result in a readonly Calendar, but I'm not sure that this feels correct to me and doesn't align with the components behavior.
Screenshot 2025-11-03 at 4 10 59 PM

**Comment by NOMADE55** [comment]
Agree with @jcfilben thoughts, a readonly prop is more intuitive, I'd keep current behavior with onSelect or be very clear about the new changes in the patch notes though.

**Comment by britt6612** [comment]
> Agree with @jcfilben thoughts, a readonly prop is more intuitive, I'd keep current behavior with onSelect or be very clear about the new changes in the patch notes though.

We are planning to discuss more as a dev group next week will keep you updated!

File: src/js/components/Calendar/Calendar.js [hunk 2]
```diff
@@ -897,18 +903,18 @@ const Calendar = forwardRef(
             <CalendarCustomDay
               key={day.getTime()}
               aria-selected={selected}
-              buttonProps={
-                onSelect
+              buttonProps={{
+                a11yTitle: day.toDateString(),
+                ...(onSelect
```
Comment (jcfilben) [inline src/js/components/Calendar/Calendar.js:908]: Nice fix!

**Comment by jcfilben** [comment]
Discussed as a dev group and we are going to align with the documented behavior, so not passing `onSelect` will result in readOnly behavior. With that I think we are good to move forward with this PR

**Review by jcfilben — COMMENTED** [review]
In the Calendar/CustomDay example I am still able to select a date even though `onSelect` is not defined

**Comment by NOMADE55** [comment]
> In the Calendar/CustomDay example I am still able to select a date even though `onSelect` is not defined

Weird, I'll check and push a fix!

**Comment by NOMADE55** [comment]
@jcfilben:  the `Calendar` component is not the one handling selection behavior, but the Box within it:

https://github.com/grommet/grommet/blob/11f7778a3098a201db5918c2c1057abf38b538e4/src/js/components/Calendar/stories/CustomDay.stories.js#L10-L28

**Comment by jcfilben** [comment]
> @jcfilben: the Calendar component is not the one handling selection behavior, but the Box within it:

Ah okay, that makes sense

**Comment by NOMADE55** [comment]
🫡
