### PR TITLE
RadioButton - add backgroundColor option in theme

### LINKED ISSUE #4187: Would like RadioButton input background color to be specified via theme
### Expected Behavior

Able to set the background color of the check input in my theme.

### Actual Behavior

Currently need to specify this via `extend`

Background: https://github.com/grommet/grommet-theme-hpe/pull/75#discussion_r437616833

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by netochaves**
#### What does this PR do?
Adds backgroundColor option in radioInput theme.
#### Where should the reviewer start?
src/js/components/RadioButton/StyledRadioButton.js
#### What testing has been done on this PR?
Unit
#### How should this be manually tested?
change theme on src/js/components/RadioButton/stories/Theme.js
#### What are the relevant issues?
Fixes #4187 
#### Do the grommet docs need to be updated?
Yes
#### Should this PR be mentioned in the release notes?
Yes
#### Is this change backwards compatible or is it a breaking change?
It is backward compatible

### CODE REVIEW

File: src/js/components/RadioButton/doc.js [hunk 1]
```diff
@@ -68,6 +68,11 @@ export const themeDoc = {
     type: 'string',
     defaultValue: '2px',
   },
+  'radioButton.check.backgroundColor': {
```
Comment (ShimiSun) [inline src/js/components/RadioButton/doc.js:71]:
```suggestion
  'radioButton.check.background.color': {
```
For consistency, we usually name background with simply just `background` vs `backgroundColor`. This change help us scale under the umbrella of background. so ultimately, you'll have:
```
 'radioButton.check.background': {...}
 'radioButton.check.background.color': ''

radioButton: {
   check: {
      background: {
         color: ' ',
      }
   }
}
``` 

This change may affect the rest of the PR, but it should be an easy fix.

File: src/js/components/RadioButton/doc.js [hunk 2]
```diff
@@ -68,6 +68,11 @@ export const themeDoc = {
...
+    description: 'The background color of the checked icon in the RadioButton.',
+    type: 'string',
```
Comment (ShimiSun) [inline src/js/components/RadioButton/doc.js:73]:
```suggestion
    type: 'string | {dark: string, light: string}',
```
The color could also be a dark/light object.

File: src/js/components/RadioButton/__tests__/RadioButton-test.js [hunk 3]
```diff
@@ -67,4 +67,23 @@ describe('RadioButton', () => {
     const tree = component.toJSON();
     expect(tree).toMatchSnapshot();
   });
+
+  test('bgColor', () => {
+    const customTheme = {
+      radioButton: {
+        check: {
+          backgroundColor: 'red',
```
Comment (ShimiSun) [inline src/js/components/RadioButton/__tests__/RadioButton-test.js:75]:
```suggestion
          background: {
             color: 'red'
          }
```

File: src/js/components/RadioButton/doc.js (hunk 1 above)
Comment (netochaves) [reply src/js/components/RadioButton/doc.js:71]: Thanks, I'll fix it.

**Comment by netochaves** [comment]
Hey @ShimiSun Thanks for your review, I think I addressed all your comments.

**Comment by ShimiSun** [comment]
@halocline, since you filed the original issue, I'd love your feedback and confirmation whether this PR approach solves the use case for your design-system requirements. Feel free to leave a review comment.

**Comment by halocline** [comment]
> @halocline, since you filed the original issue, I'd love your feedback and confirmation whether this PR approach solves the use case for your design-system requirements. Feel free to leave a review comment.

I'd be happy to. Will do.

File: src/js/components/RadioButton/doc.js [hunk 4]
```diff
@@ -65,9 +65,14 @@ export const themeDoc = {
   },
   'radioButton.border.width': {
     description: 'The width size of the border of the RadioButton.',
-    type: 'string',
+    type: 'string | {dark: string, light: string}',
```
Comment (halocline) [inline src/js/components/RadioButton/doc.js:68]: This looks like the type modification is being applied to the wrong property here. I think we want to leave `radioButton.border.width` as it was and instead apply the ` | {dark: string, light: string}` to `radioButton.check.background.color`

```suggestion
    type: 'string',
```

File: src/js/components/RadioButton/doc.js [hunk 5]
```diff
@@ -65,9 +65,14 @@ export const themeDoc = {
...
     defaultValue: '2px',
   },
+  'radioButton.check.background.color': {
+    description: 'The background color of the checked icon in the RadioButton.',
+    type: 'string',
```
Comment (halocline) [inline src/js/components/RadioButton/doc.js:73]: Per comment above, I think this color object was applied in the wrong location.

```suggestion
    type: 'string | {dark: string, light: string}',
```

File: src/js/themes/base.js [hunk 6]
```diff
@@ -880,6 +880,9 @@ export const generate = (baseSpacing = 24, scale = 6) => {
       },
       check: {
         radius: '100%',
+        background: {
+          // color: undefined,
+        },
```
Comment (halocline) [inline src/js/themes/base.js:885]: @ShimiSun from a convention standpoint, do you want the entire `background` property commented out since none of the object properties are defined?

```
        // background: {
          // color: undefined,
        // },
```

Comment (ShimiSun) [reply src/js/themes/base.js:885]: Yes, I agree it should be commented out.

File: src/js/components/RadioButton/doc.js (hunk 5 above)
Comment (ShimiSun) [reply src/js/components/RadioButton/doc.js:73]: Good catch.

Comment (netochaves) [reply src/js/components/RadioButton/doc.js:73]: Good catch @halocline, thanks.

File: src/js/themes/base.js (hunk 6 above)
Comment (netochaves) [reply src/js/themes/base.js:885]: Makes sense, thanks.

Comment (netochaves) [reply src/js/themes/base.js:885]: If we comment the entire `background` this line will throw an error because background will be `undefined`
https://github.com/grommet/grommet/blob/1a7e69e8406342456152dc4e840e9a20faea7959/src/js/components/RadioButton/StyledRadioButton.js#L63

So, we have to add some condition, e.g.:
```js
 background-color: ${props =>
    props.theme.radioButton.check.background &&
    props.theme.radioButton.check.background.color};
```

Do you want to follow this path?

Comment (halocline) [reply src/js/themes/base.js:885]: Good call. That seems reasonable to me and would be consistent with approaches elsewhere in Grommet.

File: src/js/themes/base.d.ts [hunk 7]
```diff
@@ -852,6 +852,7 @@ export interface ThemeType {
     };
     check?: {
       radius?: string;
+      background?: Object;
```
Comment (halocline) [inline src/js/themes/base.d.ts:855]: Small adjustment for additional type specificity. 

```suggestion
      background?: BackgroundType;
```

Comment (ShimiSun) [reply src/js/themes/base.d.ts:855]: I had a similar thought at the beginning, but I don't think this suggestion is accurate.
In this case, the background is not treated as a BackgroundType, we are not handling any other background props such as `image`, `repeat` `opacity`, or anything other than the background `color`.
I would agree that the type should be more explicit to the color prop as follows:
```suggestion
      background?: {
          color?: ColorType;
      }
```
