### PR TITLE
(Collapsible) fix: enable animation when initial open prop is true

### LINKED ISSUE #6523: Opened by default, collapsible does not do the animation
### Expected Behavior

It should be closed with the smooth animation

### Actual Behavior

It should be closed with the smooth animation, however it is closed roughly (only the first time)

### URL, screen shot, or Codepen exhibiting the issue
`

    const CustomCollapsible= ({
        totalQuestionsCount,
        questionSummaries,
    }) => {
    const [open, setOpen] = useState(true);

    return (
        <Box>
            <BasicButton
                basic
                onClick={() => setOpen((prevState) => !prevState)}
            />
            <Collapsible open={open}>
                {questionSummaries.map(({ description }, index) => (
                    <ExamResultsTabDetailsQuestionDetails
                        key={uniqueId()}
                        idQuestionSummaries={index + 1}
                        description={description}
                        totalQuestionsCount={totalQuestionsCount}
                        isTopHr
                    />
                ))}
            </Collapsible>
        </Box>
    );
  };

`

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Microsoft Edge, Version 107.0.1418.62 (Official build) (64-bit)
- Operating System and version (desktop or mobile): Windows 11 Home,  Version 21H2

### PR DESCRIPTION
**Pull request by buberdds**
#### What does this PR do?
Fixes animation speed value. When component is open on init `nextSpeed` value is `NaN` because sizeRef returns undefined at this point and this value is used in nextSpeed computation.

#### Where should the reviewer start?
Collapsible.js

#### What testing has been done on this PR?
manual

#### How should this be manually tested?
set initial open prop to true

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Closes #6523
 
#### Do the grommet docs need to be updated?
no

#### Should this PR be mentioned in the release notes?
yes

#### Is this change backwards compatible or is it a breaking change?
no

### CODE REVIEW

**Review by jcfilben — APPROVED** [review]
Looks good!

File: src/js/components/Collapsible/Collapsible.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ const Collapsible = forwardRef(
           collapsible: { minSpeed, baseline },
         } = theme;
         const nextSpeed = Math.max(
-          (sizeRef.current / baseline) * minSpeed,
+          ((sizeRef.current || 0) / baseline) * minSpeed,
```
Comment (ericsoderberghp) [inline src/js/components/Collapsible/Collapsible.js:80]: I think a cleaner way to do this would be to adjust the useRef to be `useRef(0)`, that way it starts with an initial value.

**Review by jcfilben — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]
