### PR TITLE
Bug in Form Validate Fix

### LINKED ISSUE #3803: Bug in Form Validate
In a form, when we have a TextInput formField & a checkbox formField & the form's validate prop is onBlur.
Now, when the formField comes to an error state & when we focus on checkbox, the earlier error state  disappears.

Please check the following codesandbox link,
https://codesandbox.io/s/bold-cray-8n2mf

Please do check the gif where I reproduced the same,
issues1

### PR DESCRIPTION
**Pull request by IanKBovard**
#### What does this PR do?
Fixes #3803 
Added conditionals to form validation so only the specific field is affected by onBlur and onChange effects.

#### Where should the reviewer start?
Form.js update function in the form component.

#### What testing has been done on this PR?
Added a checkbox to validateOnBlur storybook example.

#### How should this be manually tested?
Using the same example should work. I would check if validation behaves as expected.

#### What are the relevant issues?
#3803 

#### Screenshots (if appropriate)
Kapture 2020-03-18 at 12 07 05

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by IanKBovard** [comment]
ill see what i can do. in this pr or a new one?

**Comment by ShimiSun** [comment]
@IanKBovard This PR. thanks.

**Comment by IanKBovard** [comment]
tests added

File: src/js/components/Form/Form.js [hunk 1]
```diff
@@ -85,15 +85,21 @@ const Form = forwardRef(
...
         // re-run any validations, in case the validation
         // is checking across fields
         setErrors(prevErrors => {
           const nextErrors = { ...prevErrors };
           Object.keys(prevErrors).forEach(errName => {
             if (validations.current[errName]) {
-              const nextError = validations.current[errName](data, nextValue);
-              updateErrors(nextErrors, errName, nextError);
+              const nextError = validations.current[errName](nextValue, data);
+              if (!nextError && nextErrors[name]) {
```
Comment (ericsoderberghp) [inline src/js/components/Form/Form.js]: Isn't `nextErrors[name]` always going to be true, since we built `nextErrors` from `prevErrors` at line 91 and are only going through the keys in `prevErrors` at line 92?

Comment (IanKBovard) [reply src/js/components/Form/Form.js]: ill double check

File: src/js/components/Form/Form.js [hunk 2]
```diff
@@ -85,15 +85,21 @@ const Form = forwardRef(
...
-
         // re-run any validations, in case the validation
         // is checking across fields
         setErrors(prevErrors => {
           const nextErrors = { ...prevErrors };
           Object.keys(prevErrors).forEach(errName => {
             if (validations.current[errName]) {
-              const nextError = validations.current[errName](data, nextValue);
-              updateErrors(nextErrors, errName, nextError);
+              const nextError = validations.current[errName](nextValue, data);
```
Comment (ericsoderberghp) [inline src/js/components/Form/Form.js]: This seems backwards, the two arguments to the validation should be `(data, nextValue)`.

File: src/js/components/Form/Form.js (hunk 1 above)
Comment (IanKBovard) [reply src/js/components/Form/Form.js]: No not always. It can come out as undefined.

File: src/js/components/Form/Form.js (hunk 2 above)
Comment (IanKBovard) [reply src/js/components/Form/Form.js]: console.log of validations.current 
```
name: ƒ validateField(value2, data)
email: ƒ validateField(value2, data)
```

i could be misunderstanding something.

Comment (ericsoderberghp) [reply src/js/components/Form/Form.js]: Take a look at all of the other calls, such as `validations.current[name](value[name], value)`. At line 94, `nextValue` is the same kind of thing as `value` and `value[name]` is the same thing a `data` in this context.

Comment (IanKBovard) [reply src/js/components/Form/Form.js]: gotcha, thanks for clearing that up.

Comment (IanKBovard) [reply src/js/components/Form/Form.js]: changes made

File: src/js/components/Form/Form.js [hunk 3]
```diff
@@ -85,15 +85,21 @@ const Form = forwardRef(
...
         // re-run any validations, in case the validation
         // is checking across fields
         setErrors(prevErrors => {
           const nextErrors = { ...prevErrors };
           Object.keys(prevErrors).forEach(errName => {
             if (validations.current[errName]) {
               const nextError = validations.current[errName](data, nextValue);
-              updateErrors(nextErrors, errName, nextError);
+              if (!nextError && nextErrors[name]) {
+                updateErrors(nextErrors, name, nextErrors[name]);
```
Comment (ericsoderberghp) [inline src/js/components/Form/Form.js]: I think `nextErrors[name]` is already set before we make this call. Do we need this?

File: src/js/components/Form/Form.js [hunk 4]
```diff
@@ -85,15 +85,21 @@ const Form = forwardRef(
...
+              } else if (nextError) {
+                updateErrors(nextErrors, errName, nextError);
+              }
+            }
+            if (nextValue[name]) {
+              updateErrors(nextErrors, name, undefined);
```
Comment (ericsoderberghp) [inline src/js/components/Form/Form.js]: Why do we clear any errors just because there is a value? Won't this potentially clear a validation error set at line 98?

**Comment by IanKBovard** [comment]
working on a new iteration of this. will update you when i have it up

**Comment by IanKBovard** [comment]
Updated logic, added a check so the validate wont for each field on input.

File: src/js/components/Form/__tests__/Form-test.js [hunk 5]
```diff
@@ -481,6 +481,85 @@ describe('Form', () => {
       }),
     );
   });
+  test('validate on blur', () => {
+    const Test = () => (
+      <Form
+        validate="blur"
+        onReset={event => console.log(event)}
```
Comment (ShimiSun) [inline src/js/components/Form/__tests__/Form-test.js:488]: we can remove this event, since it's not being used.

File: src/js/components/Form/__tests__/Form-test.js [hunk 6]
```diff
@@ -481,6 +481,85 @@ describe('Form', () => {
...
+        onSubmit={({ value }) => console.log('Submit', value)}
```
Comment (ShimiSun) [inline src/js/components/Form/__tests__/Form-test.js:489]: remove console log

File: src/js/components/Form/__tests__/Form-test.js [hunk 7]
```diff
@@ -481,6 +481,85 @@ describe('Form', () => {
...
+    });
+    fireEvent.click(getByText('submit'));
+    expect(queryAllByText('required')).toHaveLength(1);
+
+    // fields reset to required error message
+    fireEvent.change(getByPlaceholderText('name'), {
+      target: { value: '' },
+    });
+    fireEvent.click(getByText('submit'));
+    expect(queryAllByText('required')).toHaveLength(2);
```
Comment (ShimiSun) [inline src/js/components/Form/__tests__/Form-test.js:546]: Check if this is needed since it is referring to reset.

Comment (IanKBovard) [reply src/js/components/Form/__tests__/Form-test.js]: changes made

File: src/js/components/Form/Form.js [hunk 8]
```diff
@@ -90,7 +91,7 @@ const Form = forwardRef(
           setErrors(prevErrors => {
             const nextErrors = { ...prevErrors };
             Object.keys(prevErrors).forEach(errName => {
-              if (validations.current[errName]) {
+              if (validations.current[errName] && errName === name) {
```
Comment (ericsoderberghp) [inline src/js/components/Form/Form.js:94]: I'm OK with this, since it works.

But, it might be cleaner to:
```
if (prevErrors[name] && validations.current[name]) {
  const nextErrors = { ...prevErrors };
  ...
}
```
rather than looping though all `prevErrors`.

Comment (IanKBovard) [reply src/js/components/Form/Form.js:94]: changes made

File: src/js/components/Form/Form.js [hunk 9]
```diff
@@ -88,14 +89,22 @@ const Form = forwardRef(
...
-            Object.keys(prevErrors).forEach(errName => {
-              if (validations.current[errName]) {
-                const nextError = validations.current[errName](data, nextValue);
-                updateErrors(nextErrors, errName, nextError);
-              }
-            });
-            return nextErrors;
+            if (prevErrors[name] && validations.current[name]) {
+              console.log(prevErrors[name], validations.current[name]);
+              console.log('hello');
```
Comment (ShimiSun) [inline src/js/components/Form/Form.js:94]: should be removed.

Comment (IanKBovard) [reply src/js/components/Form/Form.js]: removed

File: src/js/components/Form/Form.js [hunk 10]
```diff
@@ -88,14 +89,20 @@ const Form = forwardRef(
...
-            Object.keys(prevErrors).forEach(errName => {
-              if (validations.current[errName]) {
-                const nextError = validations.current[errName](data, nextValue);
-                updateErrors(nextErrors, errName, nextError);
-              }
-            });
-            return nextErrors;
+            if (prevErrors[name] && validations.current[name]) {
+              const nextErrors = { ...prevErrors };
+              Object.keys(prevErrors).forEach(errName => {
```
Comment (ericsoderberghp) [inline src/js/components/Form/Form.js:94]: I don't think we need to iterate over the errors, since we already know the name in question:
```
if (prev && current) {
  const next = { ...prev };
  updateErrors(next, name, validations.current[name](data, nextValue));
  return next;
}
```

Comment (IanKBovard) [reply src/js/components/Form/Form.js]: gotcha, made changes and tested.
